/*
 * lungo.h: the C interface of the lungo runtime.
 *
 * Programs generated by lungo's C backend include this header and link the lungo runtime
 * library. The object representation is the one of Lean's `lean.h`: an 8-byte header (reference
 * count, other, tag) followed by the object's fields; scalars are tagged pointers with the low
 * bit set. The inline functions below are the fast paths of object access and reference
 * counting over that layout; everything else is implemented by the runtime library.
 *
 * The header and the library must be of the same lungo version: generated programs call
 * `lungo_abi_v1`, which only a runtime with this ABI defines.
 *
 * Copyright the lungo authors. Licensed under the Apache License, Version 2.0.
 */

#ifndef LUNGO_H
#define LUNGO_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------------------------------ */
/* Version and portability                                                                     */
/* ------------------------------------------------------------------------------------------ */

#define LUNGO_ABI_VERSION 1

/* Defined only by a runtime library with ABI version 1; returns LUNGO_ABI_VERSION. */
uint32_t lungo_abi_v1(void);

#if defined(_MSC_VER) && !defined(__clang__)
#include <intrin.h>
#define LUNGO_INLINE static __forceinline
#define LUNGO_NORETURN __declspec(noreturn)
#define LUNGO_LIKELY(x) (x)
#define LUNGO_UNLIKELY(x) (x)
#else
#define LUNGO_INLINE static inline __attribute__((always_inline))
#define LUNGO_NORETURN __attribute__((noreturn))
#define LUNGO_LIKELY(x) __builtin_expect(!!(x), 1)
#define LUNGO_UNLIKELY(x) __builtin_expect(!!(x), 0)
#endif

/* Atomic access to reference counts and cells, with the orderings of the Rust runtime. */
#if defined(_MSC_VER) && !defined(__clang__)
#define LUNGO_LOAD_RELAXED_I32(p) (*(volatile int32_t *)(p))
#define LUNGO_STORE_RELAXED_I32(p, v) (*(volatile int32_t *)(p) = (v))
#define LUNGO_FETCH_SUB_I32(p, n) _InterlockedExchangeAdd((volatile long *)(p), -(long)(n))
#define LUNGO_LOAD_ACQUIRE_U32(p) ((uint32_t)_InterlockedCompareExchange((volatile long *)(p), 0, 0))
#define LUNGO_LOAD_ACQUIRE_PTR(p) _InterlockedCompareExchangePointer((void *volatile *)(p), NULL, NULL)
#else
#define LUNGO_LOAD_RELAXED_I32(p) __atomic_load_n((p), __ATOMIC_RELAXED)
#define LUNGO_STORE_RELAXED_I32(p, v) __atomic_store_n((p), (v), __ATOMIC_RELAXED)
#define LUNGO_FETCH_SUB_I32(p, n) __atomic_fetch_sub((p), (n), __ATOMIC_RELAXED)
#define LUNGO_LOAD_ACQUIRE_U32(p) __atomic_load_n((p), __ATOMIC_ACQUIRE)
#define LUNGO_LOAD_ACQUIRE_PTR(p) __atomic_load_n((p), __ATOMIC_ACQUIRE)
#endif

/* ------------------------------------------------------------------------------------------ */
/* Objects                                                                                     */
/* ------------------------------------------------------------------------------------------ */

typedef struct lungo_object {
    /* > 0: owned by one thread; < 0: shared between threads; 0: persistent. */
    int32_t rc;
    uint16_t cs_sz;
    uint8_t other;
    uint8_t tag;
} lungo_object;

/* A Lean value: an object pointer, or a scalar when the low bit is set. */
typedef lungo_object *lungo_obj;

#define LUNGO_MAX_CTOR_TAG 243
#define LUNGO_CLOSURE_MAX_ARGS 16
#define LUNGO_RC_STICKY ((int32_t)(INT32_MIN + 0x10000000))
#define LUNGO_RC_INC_MAX ((size_t)0x10000)

typedef struct lungo_closure_object {
    lungo_object header;
    void *fun;
    uint16_t arity;
    uint16_t num_fixed;
    lungo_obj objs[];
} lungo_closure_object;

LUNGO_INLINE bool lungo_is_scalar(lungo_obj o) { return ((uintptr_t)o & 1) == 1; }
LUNGO_INLINE lungo_obj lungo_box(size_t n) { return (lungo_obj)(((uintptr_t)n << 1) | 1); }
LUNGO_INLINE size_t lungo_unbox(lungo_obj o) { return (size_t)((uintptr_t)o >> 1); }
LUNGO_INLINE uint8_t lungo_ptr_tag(lungo_obj o) { return o->tag; }
LUNGO_INLINE uint32_t lungo_obj_tag(lungo_obj o) {
    return lungo_is_scalar(o) ? (uint32_t)lungo_unbox(o) : (uint32_t)lungo_ptr_tag(o);
}
LUNGO_INLINE int32_t lungo_get_rc(lungo_obj o) { return LUNGO_LOAD_RELAXED_I32(&o->rc); }
LUNGO_INLINE bool lungo_is_exclusive(lungo_obj o) { return lungo_get_rc(o) == 1; }

/* Slow paths, implemented by the runtime library. */
void lungo_inc_ref_n_cold(lungo_obj o, size_t n);
void lungo_dec_ref_cold(lungo_obj o);
void lungo_free_object(lungo_obj o);

LUNGO_INLINE void lungo_inc_ref_n(lungo_obj o, size_t n) {
    if (LUNGO_UNLIKELY(n > LUNGO_RC_INC_MAX)) {
        lungo_inc_ref_n_cold(o, n);
        return;
    }
    int32_t rc = lungo_get_rc(o);
    if (LUNGO_LIKELY(rc > 0)) {
        /* Wraps into the sticky range on overflow, as in lean.h. */
        LUNGO_STORE_RELAXED_I32(&o->rc, (int32_t)((uint32_t)rc + (uint32_t)n));
    } else if ((uint32_t)rc > (uint32_t)LUNGO_RC_STICKY) {
        LUNGO_FETCH_SUB_I32(&o->rc, (int32_t)n);
    }
}
LUNGO_INLINE void lungo_inc_ref(lungo_obj o) { lungo_inc_ref_n(o, 1); }
LUNGO_INLINE void lungo_inc(lungo_obj o) {
    if (!lungo_is_scalar(o)) lungo_inc_ref(o);
}
LUNGO_INLINE void lungo_inc_n(lungo_obj o, size_t n) {
    if (!lungo_is_scalar(o)) lungo_inc_ref_n(o, n);
}
LUNGO_INLINE void lungo_dec_ref(lungo_obj o) {
    int32_t rc = lungo_get_rc(o);
    if (LUNGO_LIKELY(rc > 1)) {
        LUNGO_STORE_RELAXED_I32(&o->rc, rc - 1);
    } else if (rc != 0) {
        lungo_dec_ref_cold(o);
    }
}
LUNGO_INLINE void lungo_dec(lungo_obj o) {
    if (!lungo_is_scalar(o)) lungo_dec_ref(o);
}
LUNGO_INLINE void lungo_del_object(lungo_obj o) {
    if (!lungo_is_scalar(o)) lungo_free_object(o);
}

/* Constructor objects. Scalar fields are addressed by byte offset from the first object field. */
LUNGO_INLINE lungo_obj *lungo_ctor_obj_cptr(lungo_obj o) {
    return (lungo_obj *)((char *)o + sizeof(lungo_object));
}
LUNGO_INLINE lungo_obj lungo_ctor_get(lungo_obj o, uint32_t i) { return lungo_ctor_obj_cptr(o)[i]; }
LUNGO_INLINE void lungo_ctor_set(lungo_obj o, uint32_t i, lungo_obj v) { lungo_ctor_obj_cptr(o)[i] = v; }
LUNGO_INLINE void lungo_ctor_set_tag(lungo_obj o, uint8_t tag) { o->tag = tag; }
LUNGO_INLINE void lungo_ctor_release(lungo_obj o, uint32_t i) {
    lungo_obj *slot = lungo_ctor_obj_cptr(o) + i;
    lungo_dec(*slot);
    *slot = lungo_box(0);
}
LUNGO_INLINE size_t lungo_ctor_get_usize(lungo_obj o, uint32_t i) {
    size_t v;
    memcpy(&v, lungo_ctor_obj_cptr(o) + i, sizeof v);
    return v;
}
LUNGO_INLINE void lungo_ctor_set_usize(lungo_obj o, uint32_t i, size_t v) {
    memcpy(lungo_ctor_obj_cptr(o) + i, &v, sizeof v);
}
#define LUNGO_SCALAR_FIELD(name, type)                                                           \
    LUNGO_INLINE type lungo_ctor_get_##name(lungo_obj o, size_t offset) {                        \
        type v;                                                                                  \
        memcpy(&v, (char *)lungo_ctor_obj_cptr(o) + offset, sizeof v);                          \
        return v;                                                                                \
    }                                                                                            \
    LUNGO_INLINE void lungo_ctor_set_##name(lungo_obj o, size_t offset, type v) {                \
        memcpy((char *)lungo_ctor_obj_cptr(o) + offset, &v, sizeof v);                          \
    }
LUNGO_SCALAR_FIELD(uint8, uint8_t)
LUNGO_SCALAR_FIELD(uint16, uint16_t)
LUNGO_SCALAR_FIELD(uint32, uint32_t)
LUNGO_SCALAR_FIELD(uint64, uint64_t)
LUNGO_SCALAR_FIELD(float, double)
LUNGO_SCALAR_FIELD(float32, float)
#undef LUNGO_SCALAR_FIELD

lungo_obj lungo_alloc_ctor(uint32_t tag, uint32_t num_objs, size_t scalar_sz);

/* Closures. `fun` takes `arity` object arguments, or for arities above 16 a pointer to them. */
lungo_obj lungo_alloc_closure(void *fun, uint32_t arity, uint32_t num_fixed);
LUNGO_INLINE void lungo_closure_set(lungo_obj o, uint32_t i, lungo_obj v) {
    ((lungo_closure_object *)o)->objs[i] = v;
}

/* Application of a closure, consuming it and the arguments. */
lungo_obj lungo_apply_1(lungo_obj f, lungo_obj a1);
lungo_obj lungo_apply_2(lungo_obj f, lungo_obj a1, lungo_obj a2);
lungo_obj lungo_apply_3(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3);
lungo_obj lungo_apply_4(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4);
lungo_obj lungo_apply_5(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4, lungo_obj a5);
lungo_obj lungo_apply_6(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4, lungo_obj a5,
                        lungo_obj a6);
lungo_obj lungo_apply_7(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4, lungo_obj a5,
                        lungo_obj a6, lungo_obj a7);
lungo_obj lungo_apply_8(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4, lungo_obj a5,
                        lungo_obj a6, lungo_obj a7, lungo_obj a8);
lungo_obj lungo_apply_9(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4, lungo_obj a5,
                        lungo_obj a6, lungo_obj a7, lungo_obj a8, lungo_obj a9);
lungo_obj lungo_apply_10(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4, lungo_obj a5,
                         lungo_obj a6, lungo_obj a7, lungo_obj a8, lungo_obj a9, lungo_obj a10);
lungo_obj lungo_apply_11(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4, lungo_obj a5,
                         lungo_obj a6, lungo_obj a7, lungo_obj a8, lungo_obj a9, lungo_obj a10, lungo_obj a11);
lungo_obj lungo_apply_12(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4, lungo_obj a5,
                         lungo_obj a6, lungo_obj a7, lungo_obj a8, lungo_obj a9, lungo_obj a10, lungo_obj a11,
                         lungo_obj a12);
lungo_obj lungo_apply_13(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4, lungo_obj a5,
                         lungo_obj a6, lungo_obj a7, lungo_obj a8, lungo_obj a9, lungo_obj a10, lungo_obj a11,
                         lungo_obj a12, lungo_obj a13);
lungo_obj lungo_apply_14(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4, lungo_obj a5,
                         lungo_obj a6, lungo_obj a7, lungo_obj a8, lungo_obj a9, lungo_obj a10, lungo_obj a11,
                         lungo_obj a12, lungo_obj a13, lungo_obj a14);
lungo_obj lungo_apply_15(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4, lungo_obj a5,
                         lungo_obj a6, lungo_obj a7, lungo_obj a8, lungo_obj a9, lungo_obj a10, lungo_obj a11,
                         lungo_obj a12, lungo_obj a13, lungo_obj a14, lungo_obj a15);
lungo_obj lungo_apply_16(lungo_obj f, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4, lungo_obj a5,
                         lungo_obj a6, lungo_obj a7, lungo_obj a8, lungo_obj a9, lungo_obj a10, lungo_obj a11,
                         lungo_obj a12, lungo_obj a13, lungo_obj a14, lungo_obj a15, lungo_obj a16);
lungo_obj lungo_apply_m(lungo_obj f, size_t n, const lungo_obj *args);

/* Boxing of scalars that do not fit a tagged pointer. */
lungo_obj lungo_box_uint32(uint32_t v);
lungo_obj lungo_box_uint64(uint64_t v);
lungo_obj lungo_box_usize(size_t v);
lungo_obj lungo_box_float(double v);
lungo_obj lungo_box_float32(float v);
LUNGO_INLINE uint32_t lungo_unbox_uint32(lungo_obj o) {
#if UINTPTR_MAX == 0xffffffffu
    return lungo_ctor_get_uint32(o, 0);
#else
    return (uint32_t)lungo_unbox(o);
#endif
}
LUNGO_INLINE uint64_t lungo_unbox_uint64(lungo_obj o) { return lungo_ctor_get_uint64(o, 0); }
LUNGO_INLINE size_t lungo_unbox_usize(lungo_obj o) { return lungo_ctor_get_usize(o, 0); }
LUNGO_INLINE double lungo_unbox_float(lungo_obj o) { return lungo_ctor_get_float(o, 0); }
LUNGO_INLINE float lungo_unbox_float32(lungo_obj o) { return lungo_ctor_get_float32(o, 0); }

/* Literals. */
lungo_obj lungo_mk_string_unchecked(const uint8_t *bytes, size_t size, size_t len);
lungo_obj lungo_usize_to_nat(size_t n);
lungo_obj lungo_cstr_to_nat(const char *digits);

void lungo_mark_persistent(lungo_obj o);
void lungo_mark_mt(lungo_obj o);
LUNGO_NORETURN void lungo_panic_unreachable(void);

/* ------------------------------------------------------------------------------------------ */
/* Constants and initialization cells                                                         */
/* ------------------------------------------------------------------------------------------ */

/* A lazily evaluated constant: zero-initialized; the value is persistent once evaluated. */
typedef struct lungo_lazy_obj {
    lungo_obj value;
} lungo_lazy_obj;
typedef struct lungo_lazy_bits {
    uint64_t bits;
    uint32_t ready;
} lungo_lazy_bits;

lungo_obj lungo_lazy_obj_force(lungo_lazy_obj *cell, lungo_obj (*init)(void));
uint64_t lungo_lazy_bits_force(lungo_lazy_bits *cell, uint64_t (*init)(void));

LUNGO_INLINE lungo_obj lungo_lazy_obj_get(lungo_lazy_obj *cell, lungo_obj (*init)(void)) {
    lungo_obj v = (lungo_obj)LUNGO_LOAD_ACQUIRE_PTR(&cell->value);
    return LUNGO_LIKELY(v != NULL) ? v : lungo_lazy_obj_force(cell, init);
}
LUNGO_INLINE uint64_t lungo_lazy_bits_get(lungo_lazy_bits *cell, uint64_t (*init)(void)) {
    return LUNGO_LIKELY(LUNGO_LOAD_ACQUIRE_U32(&cell->ready) != 0) ? cell->bits : lungo_lazy_bits_force(cell, init);
}

/* Scalars are stored in the 64-bit cells of constants and initialization cells as their bits;
   integers are converted, floating-point values keep their representation. */
LUNGO_INLINE uint64_t lungo_bits_of_double(double v) {
    uint64_t b;
    memcpy(&b, &v, sizeof b);
    return b;
}
LUNGO_INLINE double lungo_double_of_bits(uint64_t b) {
    double v;
    memcpy(&v, &b, sizeof v);
    return v;
}
LUNGO_INLINE uint64_t lungo_bits_of_float(float v) {
    uint32_t b;
    memcpy(&b, &v, sizeof b);
    return b;
}
LUNGO_INLINE float lungo_float_of_bits(uint64_t b) {
    uint32_t u = (uint32_t)b;
    float v;
    memcpy(&v, &u, sizeof v);
    return v;
}

/* The value of an `initialize` declaration: `{0, 0, "Decl.name"}`, set by its module's
   initializer. */
typedef struct lungo_init_obj {
    lungo_obj value;
    uint32_t ready;
    const char *name;
} lungo_init_obj;
typedef struct lungo_init_bits {
    uint64_t bits;
    uint32_t ready;
    const char *name;
} lungo_init_bits;

#define LUNGO_INIT_SET 2u
void lungo_init_obj_set(lungo_init_obj *cell, lungo_obj v);
void lungo_init_bits_set(lungo_init_bits *cell, uint64_t bits);
LUNGO_NORETURN void lungo_panic_uninitialized(const char *name);

LUNGO_INLINE lungo_obj lungo_init_obj_get(lungo_init_obj *cell) {
    if (LUNGO_UNLIKELY(LUNGO_LOAD_ACQUIRE_U32(&cell->ready) != LUNGO_INIT_SET)) lungo_panic_uninitialized(cell->name);
    return cell->value;
}
LUNGO_INLINE uint64_t lungo_init_bits_get(lungo_init_bits *cell) {
    if (LUNGO_UNLIKELY(LUNGO_LOAD_ACQUIRE_U32(&cell->ready) != LUNGO_INIT_SET)) lungo_panic_uninitialized(cell->name);
    return cell->bits;
}

/* ------------------------------------------------------------------------------------------ */
/* Programs                                                                                    */
/* ------------------------------------------------------------------------------------------ */

/* Registers the compiled Lean definition the runtime calls as `symbol` (for example
   `lean_io_error_to_string`). */
void lungo_register_export(const char *symbol, void *f);
/* The value of a successful `IO` initializer result (consumed); a failure terminates the
   process after reporting it. */
lungo_obj lungo_check_initializer(const char *decl, lungo_obj r);
/* Ends module initialization and starts the task manager; idempotent. */
void lungo_end_initialization(void);
/* Runs a Lean `main`; `argv` holds `argc` UTF-8 arguments without the program name. */
int32_t lungo_run_main(void (*initialize)(void), void *main, bool takes_args, bool returns_exit_code, size_t argc,
                       const char *const *argv);

/* ------------------------------------------------------------------------------------------ */
/* The boundary with language bindings (see the wire-format reference)                         */
/* ------------------------------------------------------------------------------------------ */

/* Bytes owned by the runtime: filled by the runtime, or allocated with lungo_buffer_alloc; freed
   with lungo_buffer_free. */
typedef struct lungo_buffer {
    uint8_t *data;
    size_t len;
    size_t capacity;
} lungo_buffer;

/* A program's type table, loaded once. */
typedef struct lungo_types lungo_types;
/* Decoding a call's arguments and encoding its result. */
typedef struct lungo_call lungo_call;
/* Encoding the arguments of a call to a host function and decoding its result. */
typedef struct lungo_hostcall lungo_hostcall;

/* Status of calls: the output holds the result, or the reason the input was rejected; with the
   value API, also: the function failed (an IO or EIO error). */
#define LUNGO_OK 0
#define LUNGO_MALFORMED 1
#define LUNGO_FAILED 2

const lungo_types *lungo_types_load(const uint8_t *bytes, size_t len);

lungo_call *lungo_call_begin(const lungo_types *types, const uint8_t *input, size_t len);
lungo_obj lungo_call_read(lungo_call *call, const uint8_t *type, size_t type_len);
bool lungo_call_complete(lungo_call *call);
void lungo_call_write(lungo_call *call, lungo_obj v, const uint8_t *type, size_t type_len);
void lungo_call_write_io(lungo_call *call, lungo_obj r, const uint8_t *type, size_t type_len);
void lungo_call_write_eio(lungo_call *call, lungo_obj r, const uint8_t *error, size_t error_len, const uint8_t *value,
                          size_t value_len);
int32_t lungo_call_end(lungo_call *call, lungo_buffer *out);
int32_t lungo_closure_call(const lungo_types *types, uint64_t handle, const uint8_t *type, size_t type_len,
                           const uint8_t *input, size_t len, lungo_buffer *out);

lungo_hostcall *lungo_hostcall_begin(const lungo_types *types, uint64_t callback, const char *declaration);
void lungo_hostcall_write(lungo_hostcall *call, lungo_obj v, const uint8_t *type, size_t type_len);
lungo_obj lungo_hostcall_finish(lungo_hostcall *call, const uint8_t *type, size_t type_len);
lungo_obj lungo_hostcall_finish_io(lungo_hostcall *call, const uint8_t *type, size_t type_len);
lungo_obj lungo_hostcall_finish_eio(lungo_hostcall *call, const uint8_t *error, size_t error_len,
                                    const uint8_t *value, size_t value_len);

/* The host's entry points, installed once per process by the binding's support library: the
   runtime calls host functions through `dispatch`, and counts its references to them with
   `retain` and `release`. */
typedef int32_t (*lungo_host_dispatch)(uint64_t callback, const uint8_t *input, size_t len, lungo_buffer *out);
typedef void (*lungo_host_ref)(uint64_t callback);
void lungo_set_host(lungo_host_dispatch dispatch, lungo_host_ref retain, lungo_host_ref release);

LUNGO_NORETURN void lungo_panic_host_extern_missing(const char *declaration);
void lungo_check_layout(const char *lean_type, const char *provider, const char *expected, const char *actual);
void lungo_handle_release(uint64_t handle);
uint64_t lungo_handle_clone(uint64_t handle);
uint8_t *lungo_buffer_alloc(lungo_buffer *out, size_t len);
void lungo_buffer_free(lungo_buffer *buffer);

/* ------------------------------------------------------------------------------------------ */
/* The C value API (see the C binding reference)                                               */
/* ------------------------------------------------------------------------------------------ */

/* A Lean value: owned by whoever the API returned it to, freed with lungo_value_free.
   Constructors of composite values take ownership of their parts; accessors return borrowed
   pointers. A value owns the handles and host functions in it. */
typedef struct lungo_value lungo_value;
/* A type expression, freed with lungo_type_free. */
typedef struct lungo_type lungo_type;
/* An error of a call, freed with lungo_error_free. */
typedef struct lungo_error lungo_error;

/* Kinds of values and types without parameters. */
#define LUNGO_NAT 0
#define LUNGO_INT 1
#define LUNGO_BOOL 2
#define LUNGO_UINT8 3
#define LUNGO_UINT16 4
#define LUNGO_UINT32 5
#define LUNGO_UINT64 6
#define LUNGO_USIZE 7
#define LUNGO_INT8 8
#define LUNGO_INT16 9
#define LUNGO_INT32 10
#define LUNGO_INT64 11
#define LUNGO_ISIZE 12
#define LUNGO_FLOAT 13
#define LUNGO_FLOAT32 14
#define LUNGO_CHAR 15
#define LUNGO_STRING 16
#define LUNGO_UNIT 17
#define LUNGO_BYTE_ARRAY 18
#define LUNGO_FLOAT_ARRAY 19
#define LUNGO_OPTION 20
#define LUNGO_LIST 21
#define LUNGO_ARRAY 22
#define LUNGO_PROD 23
#define LUNGO_EXCEPT 24
#define LUNGO_FUNCTION 25
#define LUNGO_INDUCTIVE 27
#define LUNGO_OPAQUE 28

/* Kinds of errors. */
#define LUNGO_ERROR_IO 0
#define LUNGO_ERROR_VALUE 1
#define LUNGO_ERROR_MALFORMED 2

/* A host function: runs with its context and `n` borrowed arguments; returns LUNGO_OK and
   stores its result (owned) in `*result`, or returns LUNGO_FAILED and stores an error (owned)
   in `*error`. */
typedef int32_t (*lungo_function)(void *ctx, const lungo_value *const *args, size_t n, lungo_value **result,
                                  lungo_error **error);
typedef void (*lungo_drop)(void *ctx);

lungo_type *lungo_type_simple(uint8_t kind);
lungo_type *lungo_type_option(const lungo_type *t);
lungo_type *lungo_type_list(const lungo_type *t);
lungo_type *lungo_type_array(const lungo_type *t);
lungo_type *lungo_type_prod(const lungo_type *a, const lungo_type *b);
lungo_type *lungo_type_except(const lungo_type *error, const lungo_type *value);
lungo_type *lungo_type_function(const lungo_type *const *params, size_t n, const lungo_type *result);
lungo_type *lungo_type_inductive(const lungo_types *types, uint32_t index, const lungo_type *const *args, size_t n);
lungo_type *lungo_type_clone(const lungo_type *t);
void lungo_type_free(lungo_type *t);

uint8_t lungo_value_kind(const lungo_value *v);
lungo_value *lungo_value_nat(uint64_t x);
lungo_value *lungo_value_nat_parse(const char *digits);
bool lungo_value_get_nat(const lungo_value *v, uint64_t *out);
lungo_value *lungo_value_int(int64_t x);
lungo_value *lungo_value_int_parse(const char *digits);
bool lungo_value_get_int(const lungo_value *v, int64_t *out);
char *lungo_value_number_string(const lungo_value *v);
lungo_value *lungo_value_bool(bool x);
bool lungo_value_get_bool(const lungo_value *v);
lungo_value *lungo_value_uint8(uint8_t x);
uint8_t lungo_value_get_uint8(const lungo_value *v);
lungo_value *lungo_value_uint16(uint16_t x);
uint16_t lungo_value_get_uint16(const lungo_value *v);
lungo_value *lungo_value_uint32(uint32_t x);
uint32_t lungo_value_get_uint32(const lungo_value *v);
lungo_value *lungo_value_uint64(uint64_t x);
uint64_t lungo_value_get_uint64(const lungo_value *v);
lungo_value *lungo_value_usize(uint64_t x);
uint64_t lungo_value_get_usize(const lungo_value *v);
lungo_value *lungo_value_int8(int8_t x);
int8_t lungo_value_get_int8(const lungo_value *v);
lungo_value *lungo_value_int16(int16_t x);
int16_t lungo_value_get_int16(const lungo_value *v);
lungo_value *lungo_value_int32(int32_t x);
int32_t lungo_value_get_int32(const lungo_value *v);
lungo_value *lungo_value_int64(int64_t x);
int64_t lungo_value_get_int64(const lungo_value *v);
lungo_value *lungo_value_isize(int64_t x);
int64_t lungo_value_get_isize(const lungo_value *v);
lungo_value *lungo_value_float(double x);
double lungo_value_get_float(const lungo_value *v);
lungo_value *lungo_value_float32(float x);
float lungo_value_get_float32(const lungo_value *v);
lungo_value *lungo_value_char(uint32_t c);
uint32_t lungo_value_get_char(const lungo_value *v);
lungo_value *lungo_value_string(const char *utf8, size_t len);
lungo_value *lungo_value_cstring(const char *utf8);
const char *lungo_value_get_string(const lungo_value *v, size_t *len);
char *lungo_value_string_dup(const lungo_value *v);
void lungo_string_free(char *s);
lungo_value *lungo_value_unit(void);
lungo_value *lungo_value_byte_array(const uint8_t *data, size_t len);
const uint8_t *lungo_value_get_bytes(const lungo_value *v, size_t *len);
lungo_value *lungo_value_float_array(const double *data, size_t len);
const double *lungo_value_get_floats(const lungo_value *v, size_t *len);
lungo_value *lungo_value_none(void);
lungo_value *lungo_value_some(lungo_value *x);
const lungo_value *lungo_value_get_option(const lungo_value *v);
lungo_value *lungo_value_list(lungo_value **items, size_t n);
lungo_value *lungo_value_array(lungo_value **items, size_t n);
size_t lungo_value_count(const lungo_value *v);
const lungo_value *lungo_value_item(const lungo_value *v, size_t i);
lungo_value *lungo_value_prod(lungo_value *a, lungo_value *b);
const lungo_value *lungo_value_first(const lungo_value *v);
const lungo_value *lungo_value_second(const lungo_value *v);
lungo_value *lungo_value_ok(lungo_value *x);
lungo_value *lungo_value_error(lungo_value *e);
bool lungo_value_is_ok(const lungo_value *v);
const lungo_value *lungo_value_get_except(const lungo_value *v);
lungo_value *lungo_value_ctor(uint32_t index, lungo_value **fields, size_t n);
uint32_t lungo_value_ctor_index(const lungo_value *v);
size_t lungo_value_field_count(const lungo_value *v);
const lungo_value *lungo_value_field(const lungo_value *v, size_t i);
const lungo_value *lungo_value_ctor_field(const lungo_value *v, uint32_t ctor, size_t i);
lungo_value *lungo_value_function(const lungo_type *fn_type, lungo_function f, void *ctx, lungo_drop drop);
int32_t lungo_value_call(const lungo_value *f, const lungo_type *fn_type, const lungo_value *const *args, size_t n,
                         lungo_value **result, lungo_error **error);
lungo_value *lungo_value_clone(const lungo_value *v);
bool lungo_value_equal(const lungo_value *a, const lungo_value *b);
void lungo_value_free(lungo_value *v);

uint32_t lungo_error_kind(const lungo_error *e);
const char *lungo_error_message(const lungo_error *e);
const lungo_value *lungo_error_value(const lungo_error *e);
lungo_error *lungo_error_io(const char *message);
lungo_error *lungo_error_from_value(lungo_value *v);
lungo_error *lungo_error_clone(const lungo_error *e);
void lungo_error_free(lungo_error *e);

/* Used by generated packages. */
typedef int32_t (*lungo_entry)(const uint8_t *input, size_t len, lungo_buffer *out);
int32_t lungo_invoke(const lungo_types *types, lungo_entry entry, const uint8_t *sig, size_t sig_len,
                     const lungo_type *const *type_args, size_t n_types, const lungo_value *const *args, size_t n_args,
                     lungo_value **result, lungo_error **error);
uint64_t lungo_host_function_new(const lungo_types *types, const uint8_t *sig, size_t sig_len, lungo_function f,
                                 void *ctx, lungo_drop drop);

/* ------------------------------------------------------------------------------------------ */
/* Runtime primitives                                                                          */
/* ------------------------------------------------------------------------------------------ */

/* BEGIN GENERATED: runtime primitives (do not edit; see lungo-runtime/tests/header.rs) */
double lungo_acos(double a0);
float lungo_acosf(float a0);
double lungo_acosh(double a0);
float lungo_acoshf(float a0);
double lungo_asin(double a0);
float lungo_asinf(float a0);
double lungo_asinh(double a0);
float lungo_asinhf(float a0);
double lungo_atan(double a0);
double lungo_atan2(double a0, double a1);
float lungo_atan2f(float a0, float a1);
float lungo_atanf(float a0);
double lungo_atanh(double a0);
float lungo_atanhf(float a0);
double lungo_cbrt(double a0);
float lungo_cbrtf(float a0);
double lungo_ceil(double a0);
float lungo_ceilf(float a0);
double lungo_cos(double a0);
float lungo_cosf(float a0);
double lungo_cosh(double a0);
float lungo_coshf(float a0);
double lungo_exp(double a0);
double lungo_exp2(double a0);
float lungo_exp2f(float a0);
float lungo_expf(float a0);
double lungo_fabs(double a0);
float lungo_fabsf(float a0);
double lungo_floor(double a0);
float lungo_floorf(float a0);
lungo_obj lungo_lean_array_fget(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_array_fget_borrowed(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_array_fset(lungo_obj a0, lungo_obj a1 /* borrowed */, lungo_obj a2);
lungo_obj lungo_lean_array_fswap(lungo_obj a0, lungo_obj a1 /* borrowed */, lungo_obj a2 /* borrowed */);
lungo_obj lungo_lean_array_get(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */, lungo_obj a2 /* borrowed */);
lungo_obj lungo_lean_array_get_borrowed(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */, lungo_obj a2 /* borrowed */);
lungo_obj lungo_lean_array_get_size(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_array_mk(lungo_obj a0);
lungo_obj lungo_lean_array_pop(lungo_obj a0);
lungo_obj lungo_lean_array_push(lungo_obj a0, lungo_obj a1);
lungo_obj lungo_lean_array_set(lungo_obj a0, lungo_obj a1 /* borrowed */, lungo_obj a2);
size_t lungo_lean_array_size(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_array_swap(lungo_obj a0, lungo_obj a1 /* borrowed */, lungo_obj a2 /* borrowed */);
lungo_obj lungo_lean_array_to_list(lungo_obj a0);
lungo_obj lungo_lean_array_uget(lungo_obj a0 /* borrowed */, size_t a1);
lungo_obj lungo_lean_array_uget_borrowed(lungo_obj a0 /* borrowed */, size_t a1);
lungo_obj lungo_lean_array_uset(lungo_obj a0, size_t a1, lungo_obj a2);
uint16_t lungo_lean_bool_to_int16(uint8_t a0);
uint32_t lungo_lean_bool_to_int32(uint8_t a0);
uint64_t lungo_lean_bool_to_int64(uint8_t a0);
uint8_t lungo_lean_bool_to_int8(uint8_t a0);
size_t lungo_lean_bool_to_isize(uint8_t a0);
uint16_t lungo_lean_bool_to_uint16(uint8_t a0);
uint32_t lungo_lean_bool_to_uint32(uint8_t a0);
uint64_t lungo_lean_bool_to_uint64(uint8_t a0);
uint8_t lungo_lean_bool_to_uint8(uint8_t a0);
size_t lungo_lean_bool_to_usize(uint8_t a0);
lungo_obj lungo_lean_byte_array_copy_slice(lungo_obj a0 /* borrowed */, lungo_obj a1, lungo_obj a2, lungo_obj a3, lungo_obj a4, uint8_t a5);
lungo_obj lungo_lean_byte_array_data(lungo_obj a0);
uint8_t lungo_lean_byte_array_fget(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_byte_array_fset(lungo_obj a0, lungo_obj a1 /* borrowed */, uint8_t a2);
uint8_t lungo_lean_byte_array_get(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint64_t lungo_lean_byte_array_hash(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_byte_array_mk(lungo_obj a0);
lungo_obj lungo_lean_byte_array_push(lungo_obj a0, uint8_t a1);
lungo_obj lungo_lean_byte_array_set(lungo_obj a0, lungo_obj a1 /* borrowed */, uint8_t a2);
lungo_obj lungo_lean_byte_array_size(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_byte_array_uget(lungo_obj a0 /* borrowed */, size_t a1);
lungo_obj lungo_lean_byte_array_uset(lungo_obj a0, size_t a1, uint8_t a2);
uint8_t lungo_lean_byteslice_beq(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_chmod(lungo_obj a0 /* borrowed */, uint32_t a1);
lungo_obj lungo_lean_dbg_sleep(uint32_t a0, lungo_obj a1);
lungo_obj lungo_lean_dbg_stack_trace(lungo_obj a0);
lungo_obj lungo_lean_dbg_trace(lungo_obj a0, lungo_obj a1);
lungo_obj lungo_lean_dbg_trace_if_shared(lungo_obj a0 /* borrowed */, lungo_obj a1);
float lungo_lean_float32_add(float a0, float a1);
uint8_t lungo_lean_float32_beq(float a0, float a1);
uint8_t lungo_lean_float32_decLe(float a0, float a1);
uint8_t lungo_lean_float32_decLt(float a0, float a1);
float lungo_lean_float32_div(float a0, float a1);
lungo_obj lungo_lean_float32_frexp(float a0);
uint8_t lungo_lean_float32_isfinite(float a0);
uint8_t lungo_lean_float32_isinf(float a0);
uint8_t lungo_lean_float32_isnan(float a0);
float lungo_lean_float32_mul(float a0, float a1);
float lungo_lean_float32_negate(float a0);
float lungo_lean_float32_of_bits(uint32_t a0);
float lungo_lean_float32_scaleb(float a0, lungo_obj a1 /* borrowed */);
float lungo_lean_float32_sub(float a0, float a1);
uint32_t lungo_lean_float32_to_bits(float a0);
double lungo_lean_float32_to_float(float a0);
uint16_t lungo_lean_float32_to_int16(float a0);
uint32_t lungo_lean_float32_to_int32(float a0);
uint64_t lungo_lean_float32_to_int64(float a0);
uint8_t lungo_lean_float32_to_int8(float a0);
size_t lungo_lean_float32_to_isize(float a0);
lungo_obj lungo_lean_float32_to_string(float a0);
uint16_t lungo_lean_float32_to_uint16(float a0);
uint32_t lungo_lean_float32_to_uint32(float a0);
uint64_t lungo_lean_float32_to_uint64(float a0);
uint8_t lungo_lean_float32_to_uint8(float a0);
size_t lungo_lean_float32_to_usize(float a0);
double lungo_lean_float_add(double a0, double a1);
lungo_obj lungo_lean_float_array_data(lungo_obj a0);
double lungo_lean_float_array_fget(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_float_array_fset(lungo_obj a0, lungo_obj a1 /* borrowed */, double a2);
double lungo_lean_float_array_get(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_float_array_mk(lungo_obj a0);
lungo_obj lungo_lean_float_array_push(lungo_obj a0, double a1);
lungo_obj lungo_lean_float_array_set(lungo_obj a0, lungo_obj a1 /* borrowed */, double a2);
lungo_obj lungo_lean_float_array_size(lungo_obj a0 /* borrowed */);
double lungo_lean_float_array_uget(lungo_obj a0 /* borrowed */, size_t a1);
lungo_obj lungo_lean_float_array_uset(lungo_obj a0, size_t a1, double a2);
uint8_t lungo_lean_float_beq(double a0, double a1);
uint8_t lungo_lean_float_decLe(double a0, double a1);
uint8_t lungo_lean_float_decLt(double a0, double a1);
double lungo_lean_float_div(double a0, double a1);
lungo_obj lungo_lean_float_frexp(double a0);
uint8_t lungo_lean_float_isfinite(double a0);
uint8_t lungo_lean_float_isinf(double a0);
uint8_t lungo_lean_float_isnan(double a0);
double lungo_lean_float_mul(double a0, double a1);
double lungo_lean_float_negate(double a0);
double lungo_lean_float_of_bits(uint64_t a0);
double lungo_lean_float_scaleb(double a0, lungo_obj a1 /* borrowed */);
double lungo_lean_float_sub(double a0, double a1);
uint64_t lungo_lean_float_to_bits(double a0);
float lungo_lean_float_to_float32(double a0);
uint16_t lungo_lean_float_to_int16(double a0);
uint32_t lungo_lean_float_to_int32(double a0);
uint64_t lungo_lean_float_to_int64(double a0);
uint8_t lungo_lean_float_to_int8(double a0);
size_t lungo_lean_float_to_isize(double a0);
lungo_obj lungo_lean_float_to_string(double a0);
uint16_t lungo_lean_float_to_uint16(double a0);
uint32_t lungo_lean_float_to_uint32(double a0);
uint64_t lungo_lean_float_to_uint64(double a0);
uint8_t lungo_lean_float_to_uint8(double a0);
size_t lungo_lean_float_to_usize(double a0);
lungo_obj lungo_lean_get_current_time(void);
lungo_obj lungo_lean_get_githash(lungo_obj a0);
lungo_obj lungo_lean_get_set_stderr(lungo_obj a0);
lungo_obj lungo_lean_get_set_stdin(lungo_obj a0);
lungo_obj lungo_lean_get_set_stdout(lungo_obj a0);
lungo_obj lungo_lean_get_stderr(void);
lungo_obj lungo_lean_get_stdin(void);
lungo_obj lungo_lean_get_stdout(void);
lungo_obj lungo_lean_get_windows_local_timezone_id_at(uint64_t a0);
uint16_t lungo_lean_int16_abs(uint16_t a0);
uint16_t lungo_lean_int16_add(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_int16_complement(uint16_t a0);
uint8_t lungo_lean_int16_dec_eq(uint16_t a0, uint16_t a1);
uint8_t lungo_lean_int16_dec_le(uint16_t a0, uint16_t a1);
uint8_t lungo_lean_int16_dec_lt(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_int16_div(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_int16_land(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_int16_lor(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_int16_mod(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_int16_mul(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_int16_neg(uint16_t a0);
uint16_t lungo_lean_int16_of_int(lungo_obj a0 /* borrowed */);
uint16_t lungo_lean_int16_of_nat(lungo_obj a0 /* borrowed */);
uint16_t lungo_lean_int16_shift_left(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_int16_shift_right(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_int16_sub(uint16_t a0, uint16_t a1);
double lungo_lean_int16_to_float(uint16_t a0);
float lungo_lean_int16_to_float32(uint16_t a0);
lungo_obj lungo_lean_int16_to_int(uint16_t a0);
uint32_t lungo_lean_int16_to_int32(uint16_t a0);
uint64_t lungo_lean_int16_to_int64(uint16_t a0);
uint8_t lungo_lean_int16_to_int8(uint16_t a0);
size_t lungo_lean_int16_to_isize(uint16_t a0);
uint16_t lungo_lean_int16_xor(uint16_t a0, uint16_t a1);
uint32_t lungo_lean_int32_abs(uint32_t a0);
uint32_t lungo_lean_int32_add(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_int32_complement(uint32_t a0);
uint8_t lungo_lean_int32_dec_eq(uint32_t a0, uint32_t a1);
uint8_t lungo_lean_int32_dec_le(uint32_t a0, uint32_t a1);
uint8_t lungo_lean_int32_dec_lt(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_int32_div(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_int32_land(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_int32_lor(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_int32_mod(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_int32_mul(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_int32_neg(uint32_t a0);
uint32_t lungo_lean_int32_of_int(lungo_obj a0 /* borrowed */);
uint32_t lungo_lean_int32_of_nat(lungo_obj a0 /* borrowed */);
uint32_t lungo_lean_int32_shift_left(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_int32_shift_right(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_int32_sub(uint32_t a0, uint32_t a1);
double lungo_lean_int32_to_float(uint32_t a0);
float lungo_lean_int32_to_float32(uint32_t a0);
lungo_obj lungo_lean_int32_to_int(uint32_t a0);
uint16_t lungo_lean_int32_to_int16(uint32_t a0);
uint64_t lungo_lean_int32_to_int64(uint32_t a0);
uint8_t lungo_lean_int32_to_int8(uint32_t a0);
size_t lungo_lean_int32_to_isize(uint32_t a0);
uint32_t lungo_lean_int32_xor(uint32_t a0, uint32_t a1);
uint64_t lungo_lean_int64_abs(uint64_t a0);
uint64_t lungo_lean_int64_add(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_int64_complement(uint64_t a0);
uint8_t lungo_lean_int64_dec_eq(uint64_t a0, uint64_t a1);
uint8_t lungo_lean_int64_dec_le(uint64_t a0, uint64_t a1);
uint8_t lungo_lean_int64_dec_lt(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_int64_div(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_int64_land(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_int64_lor(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_int64_mod(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_int64_mul(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_int64_neg(uint64_t a0);
uint64_t lungo_lean_int64_of_int(lungo_obj a0 /* borrowed */);
uint64_t lungo_lean_int64_of_nat(lungo_obj a0 /* borrowed */);
uint64_t lungo_lean_int64_shift_left(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_int64_shift_right(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_int64_sub(uint64_t a0, uint64_t a1);
double lungo_lean_int64_to_float(uint64_t a0);
float lungo_lean_int64_to_float32(uint64_t a0);
uint16_t lungo_lean_int64_to_int16(uint64_t a0);
uint32_t lungo_lean_int64_to_int32(uint64_t a0);
uint8_t lungo_lean_int64_to_int8(uint64_t a0);
lungo_obj lungo_lean_int64_to_int_sint(uint64_t a0);
size_t lungo_lean_int64_to_isize(uint64_t a0);
uint64_t lungo_lean_int64_xor(uint64_t a0, uint64_t a1);
uint8_t lungo_lean_int8_abs(uint8_t a0);
uint8_t lungo_lean_int8_add(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_int8_complement(uint8_t a0);
uint8_t lungo_lean_int8_dec_eq(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_int8_dec_le(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_int8_dec_lt(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_int8_div(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_int8_land(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_int8_lor(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_int8_mod(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_int8_mul(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_int8_neg(uint8_t a0);
uint8_t lungo_lean_int8_of_int(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_int8_of_nat(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_int8_shift_left(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_int8_shift_right(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_int8_sub(uint8_t a0, uint8_t a1);
double lungo_lean_int8_to_float(uint8_t a0);
float lungo_lean_int8_to_float32(uint8_t a0);
lungo_obj lungo_lean_int8_to_int(uint8_t a0);
uint16_t lungo_lean_int8_to_int16(uint8_t a0);
uint32_t lungo_lean_int8_to_int32(uint8_t a0);
uint64_t lungo_lean_int8_to_int64(uint8_t a0);
size_t lungo_lean_int8_to_isize(uint8_t a0);
uint8_t lungo_lean_int8_xor(uint8_t a0, uint8_t a1);
lungo_obj lungo_lean_int_add(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint8_t lungo_lean_int_dec_eq(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint8_t lungo_lean_int_dec_le(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint8_t lungo_lean_int_dec_lt(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint8_t lungo_lean_int_dec_nonneg(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_int_div(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_int_div_exact(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_int_ediv(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_int_emod(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_int_mod(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_int_mul(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_int_neg(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_int_neg_succ_of_nat(lungo_obj a0);
lungo_obj lungo_lean_int_sub(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint32_t lungo_lean_internal_get_hardware_concurrency(lungo_obj a0);
uint8_t lungo_lean_internal_has_llvm_backend(lungo_obj a0);
uint8_t lungo_lean_internal_is_stage0(lungo_obj a0);
lungo_obj lungo_lean_io_allocprof(lungo_obj a0 /* borrowed */, lungo_obj a1);
lungo_obj lungo_lean_io_app_path(void);
lungo_obj lungo_lean_io_as_task(lungo_obj a0, lungo_obj a1);
lungo_obj lungo_lean_io_basemutex_lock(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_basemutex_new(void);
uint8_t lungo_lean_io_basemutex_try_lock(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_basemutex_unlock(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_baserecmutex_lock(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_baserecmutex_new(void);
uint8_t lungo_lean_io_baserecmutex_try_lock(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_baserecmutex_unlock(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_basesharedmutex_new(void);
lungo_obj lungo_lean_io_basesharedmutex_read(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_io_basesharedmutex_try_read(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_io_basesharedmutex_try_write(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_basesharedmutex_unlock_read(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_basesharedmutex_unlock_write(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_basesharedmutex_write(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_bind_task(lungo_obj a0, lungo_obj a1, lungo_obj a2, uint8_t a3);
lungo_obj lungo_lean_io_cancel(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_io_check_canceled(void);
lungo_obj lungo_lean_io_condvar_new(void);
lungo_obj lungo_lean_io_condvar_notify_all(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_condvar_notify_one(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_condvar_wait(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_io_create_dir(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_create_tempdir(void);
lungo_obj lungo_lean_io_create_tempfile(void);
lungo_obj lungo_lean_io_current_dir(void);
lungo_obj lungo_lean_io_exit(uint8_t a0);
lungo_obj lungo_lean_io_force_exit(uint8_t a0);
lungo_obj lungo_lean_io_get_num_heartbeats(void);
lungo_obj lungo_lean_io_get_random_bytes(size_t a0);
uint8_t lungo_lean_io_get_task_state(lungo_obj a0 /* borrowed */);
uint64_t lungo_lean_io_get_tid(void);
lungo_obj lungo_lean_io_getenv(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_hard_link(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint8_t lungo_lean_io_initializing(void);
lungo_obj lungo_lean_io_map_task(lungo_obj a0, lungo_obj a1, lungo_obj a2, uint8_t a3);
lungo_obj lungo_lean_io_metadata(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_mono_ms_now(void);
lungo_obj lungo_lean_io_mono_nanos_now(void);
lungo_obj lungo_lean_io_prim_handle_flush(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_prim_handle_get_line(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_io_prim_handle_is_tty(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_prim_handle_lock(lungo_obj a0 /* borrowed */, uint8_t a1);
lungo_obj lungo_lean_io_prim_handle_mk(lungo_obj a0 /* borrowed */, uint8_t a1);
lungo_obj lungo_lean_io_prim_handle_put_str(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_io_prim_handle_read(lungo_obj a0 /* borrowed */, size_t a1);
lungo_obj lungo_lean_io_prim_handle_rewind(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_prim_handle_truncate(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_prim_handle_try_lock(lungo_obj a0 /* borrowed */, uint8_t a1);
lungo_obj lungo_lean_io_prim_handle_unlock(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_prim_handle_write(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_io_process_child_kill(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint32_t lungo_lean_io_process_child_pid(lungo_obj a0 /* borrowed */, lungo_obj a1);
lungo_obj lungo_lean_io_process_child_take_stdin(lungo_obj a0 /* borrowed */, lungo_obj a1);
lungo_obj lungo_lean_io_process_child_try_wait(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_io_process_child_wait(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_io_process_get_current_dir(void);
uint32_t lungo_lean_io_process_get_pid(void);
lungo_obj lungo_lean_io_process_set_current_dir(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_process_spawn(lungo_obj a0);
lungo_obj lungo_lean_io_promise_new(void);
lungo_obj lungo_lean_io_promise_resolve(lungo_obj a0, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_io_promise_result_opt(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_read_dir(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_realpath(lungo_obj a0);
lungo_obj lungo_lean_io_remove_dir(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_remove_file(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_rename(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_io_set_heartbeats(lungo_obj a0);
lungo_obj lungo_lean_io_symlink_metadata(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_io_timeit(lungo_obj a0 /* borrowed */, lungo_obj a1);
lungo_obj lungo_lean_io_wait(lungo_obj a0);
lungo_obj lungo_lean_io_wait_any(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_is_exclusive_obj(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_is_scalar(lungo_obj a0 /* borrowed */);
size_t lungo_lean_isize_abs(size_t a0);
size_t lungo_lean_isize_add(size_t a0, size_t a1);
size_t lungo_lean_isize_complement(size_t a0);
uint8_t lungo_lean_isize_dec_eq(size_t a0, size_t a1);
uint8_t lungo_lean_isize_dec_le(size_t a0, size_t a1);
uint8_t lungo_lean_isize_dec_lt(size_t a0, size_t a1);
size_t lungo_lean_isize_div(size_t a0, size_t a1);
size_t lungo_lean_isize_land(size_t a0, size_t a1);
size_t lungo_lean_isize_lor(size_t a0, size_t a1);
size_t lungo_lean_isize_mod(size_t a0, size_t a1);
size_t lungo_lean_isize_mul(size_t a0, size_t a1);
size_t lungo_lean_isize_neg(size_t a0);
size_t lungo_lean_isize_of_int(lungo_obj a0 /* borrowed */);
size_t lungo_lean_isize_of_nat(lungo_obj a0 /* borrowed */);
size_t lungo_lean_isize_shift_left(size_t a0, size_t a1);
size_t lungo_lean_isize_shift_right(size_t a0, size_t a1);
size_t lungo_lean_isize_sub(size_t a0, size_t a1);
double lungo_lean_isize_to_float(size_t a0);
float lungo_lean_isize_to_float32(size_t a0);
lungo_obj lungo_lean_isize_to_int(size_t a0);
uint16_t lungo_lean_isize_to_int16(size_t a0);
uint32_t lungo_lean_isize_to_int32(size_t a0);
uint64_t lungo_lean_isize_to_int64(size_t a0);
uint8_t lungo_lean_isize_to_int8(size_t a0);
size_t lungo_lean_isize_xor(size_t a0, size_t a1);
lungo_obj lungo_lean_mk_array(lungo_obj a0, lungo_obj a1);
lungo_obj lungo_lean_mk_empty_array_with_capacity(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_mk_empty_byte_array(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_mk_empty_float_array(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_mk_thunk(lungo_obj a0);
uint8_t lungo_lean_name_eq(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_abs(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_nat_add(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint8_t lungo_lean_nat_dec_eq(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint8_t lungo_lean_nat_dec_le(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint8_t lungo_lean_nat_dec_lt(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_div(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_div_exact(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_gcd(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_land(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_log2(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_nat_lor(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_lxor(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_mod(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_mul(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_pow(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_pred(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_nat_shiftl(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_shiftr(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_sub(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_nat_to_int(lungo_obj a0);
lungo_obj lungo_lean_option_get_or_block(lungo_obj a0);
lungo_obj lungo_lean_panic_fn_borrowed(lungo_obj a0 /* borrowed */, lungo_obj a1);
size_t lungo_lean_ptr_addr(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_runtime_forget(lungo_obj a0);
lungo_obj lungo_lean_runtime_hold(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_runtime_mark_multi_threaded(lungo_obj a0);
lungo_obj lungo_lean_runtime_mark_persistent(lungo_obj a0);
uint8_t lungo_lean_sarray_dec_eq(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
size_t lungo_lean_sarray_size(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_sharecommon_eq(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint64_t lungo_lean_sharecommon_hash(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_sharecommon_quick(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_slice_dec_lt(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint64_t lungo_lean_slice_hash(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_sorry(uint8_t a0);
lungo_obj lungo_lean_st_mk_ref(lungo_obj a0);
lungo_obj lungo_lean_st_ref_get(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_st_ref_ptr_eq(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_st_ref_set(lungo_obj a0 /* borrowed */, lungo_obj a1);
lungo_obj lungo_lean_st_ref_swap(lungo_obj a0 /* borrowed */, lungo_obj a1);
lungo_obj lungo_lean_st_ref_take(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_state_sharecommon(lungo_obj a0 /* borrowed */, lungo_obj a1, lungo_obj a2);
uint8_t lungo_lean_strict_and(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_strict_or(uint8_t a0, uint8_t a1);
lungo_obj lungo_lean_string_append(lungo_obj a0, lungo_obj a1 /* borrowed */);
uint8_t lungo_lean_string_compare(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_string_data(lungo_obj a0);
uint8_t lungo_lean_string_dec_eq(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint8_t lungo_lean_string_dec_lt(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_string_from_utf8_unchecked(lungo_obj a0);
uint8_t lungo_lean_string_get_byte_fast(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint64_t lungo_lean_string_hash(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_string_is_valid_pos(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_string_length(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_string_memcmp(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */, lungo_obj a2 /* borrowed */, lungo_obj a3 /* borrowed */, lungo_obj a4 /* borrowed */);
lungo_obj lungo_lean_string_mk(lungo_obj a0);
lungo_obj lungo_lean_string_of_usize(size_t a0);
lungo_obj lungo_lean_string_push(lungo_obj a0, uint32_t a1);
lungo_obj lungo_lean_string_to_utf8(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_string_uget_byte_fast(lungo_obj a0 /* borrowed */, size_t a1);
uint8_t lungo_lean_string_utf8_at_end(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_string_utf8_byte_size(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_string_utf8_extract(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */, lungo_obj a2 /* borrowed */);
lungo_obj lungo_lean_string_utf8_extract_fast(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */, lungo_obj a2 /* borrowed */);
uint32_t lungo_lean_string_utf8_get(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint32_t lungo_lean_string_utf8_get_bang(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
uint32_t lungo_lean_string_utf8_get_fast(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_string_utf8_get_opt(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_string_utf8_next(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_string_utf8_next_fast(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_string_utf8_prev(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_string_utf8_set(lungo_obj a0, lungo_obj a1 /* borrowed */, uint32_t a2);
uint8_t lungo_lean_string_validate_utf8(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_system_platform_emscripten(lungo_obj a0);
uint8_t lungo_lean_system_platform_linux(lungo_obj a0);
lungo_obj lungo_lean_system_platform_nbits(lungo_obj a0);
uint8_t lungo_lean_system_platform_osx(lungo_obj a0);
lungo_obj lungo_lean_system_platform_target(lungo_obj a0);
uint8_t lungo_lean_system_platform_windows(lungo_obj a0);
lungo_obj lungo_lean_task_bind(lungo_obj a0, lungo_obj a1, lungo_obj a2, uint8_t a3);
lungo_obj lungo_lean_task_get_own(lungo_obj a0);
lungo_obj lungo_lean_task_map(lungo_obj a0, lungo_obj a1, lungo_obj a2, uint8_t a3);
lungo_obj lungo_lean_task_pure(lungo_obj a0);
lungo_obj lungo_lean_task_spawn(lungo_obj a0, lungo_obj a1);
lungo_obj lungo_lean_thunk_get_own(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_thunk_pure(lungo_obj a0);
uint16_t lungo_lean_uint16_add(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_uint16_complement(uint16_t a0);
uint8_t lungo_lean_uint16_dec_eq(uint16_t a0, uint16_t a1);
uint8_t lungo_lean_uint16_dec_le(uint16_t a0, uint16_t a1);
uint8_t lungo_lean_uint16_dec_lt(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_uint16_div(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_uint16_land(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_uint16_log2(uint16_t a0);
uint16_t lungo_lean_uint16_lor(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_uint16_mod(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_uint16_mul(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_uint16_neg(uint16_t a0);
uint16_t lungo_lean_uint16_of_nat(lungo_obj a0 /* borrowed */);
uint16_t lungo_lean_uint16_of_nat_mk(lungo_obj a0);
uint16_t lungo_lean_uint16_shift_left(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_uint16_shift_right(uint16_t a0, uint16_t a1);
uint16_t lungo_lean_uint16_sub(uint16_t a0, uint16_t a1);
double lungo_lean_uint16_to_float(uint16_t a0);
float lungo_lean_uint16_to_float32(uint16_t a0);
lungo_obj lungo_lean_uint16_to_nat(uint16_t a0);
uint32_t lungo_lean_uint16_to_uint32(uint16_t a0);
uint64_t lungo_lean_uint16_to_uint64(uint16_t a0);
uint8_t lungo_lean_uint16_to_uint8(uint16_t a0);
size_t lungo_lean_uint16_to_usize(uint16_t a0);
uint16_t lungo_lean_uint16_xor(uint16_t a0, uint16_t a1);
uint32_t lungo_lean_uint32_add(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_uint32_complement(uint32_t a0);
uint8_t lungo_lean_uint32_dec_eq(uint32_t a0, uint32_t a1);
uint8_t lungo_lean_uint32_dec_le(uint32_t a0, uint32_t a1);
uint8_t lungo_lean_uint32_dec_lt(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_uint32_div(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_uint32_land(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_uint32_log2(uint32_t a0);
uint32_t lungo_lean_uint32_lor(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_uint32_mod(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_uint32_mul(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_uint32_neg(uint32_t a0);
uint32_t lungo_lean_uint32_of_nat(lungo_obj a0 /* borrowed */);
uint32_t lungo_lean_uint32_of_nat_mk(lungo_obj a0);
uint32_t lungo_lean_uint32_shift_left(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_uint32_shift_right(uint32_t a0, uint32_t a1);
uint32_t lungo_lean_uint32_sub(uint32_t a0, uint32_t a1);
double lungo_lean_uint32_to_float(uint32_t a0);
float lungo_lean_uint32_to_float32(uint32_t a0);
lungo_obj lungo_lean_uint32_to_nat(uint32_t a0);
uint16_t lungo_lean_uint32_to_uint16(uint32_t a0);
uint64_t lungo_lean_uint32_to_uint64(uint32_t a0);
uint8_t lungo_lean_uint32_to_uint8(uint32_t a0);
size_t lungo_lean_uint32_to_usize(uint32_t a0);
uint32_t lungo_lean_uint32_xor(uint32_t a0, uint32_t a1);
uint64_t lungo_lean_uint64_add(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_uint64_complement(uint64_t a0);
uint8_t lungo_lean_uint64_dec_eq(uint64_t a0, uint64_t a1);
uint8_t lungo_lean_uint64_dec_le(uint64_t a0, uint64_t a1);
uint8_t lungo_lean_uint64_dec_lt(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_uint64_div(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_uint64_land(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_uint64_log2(uint64_t a0);
uint64_t lungo_lean_uint64_lor(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_uint64_mix_hash(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_uint64_mod(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_uint64_mul(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_uint64_neg(uint64_t a0);
uint64_t lungo_lean_uint64_of_nat(lungo_obj a0 /* borrowed */);
uint64_t lungo_lean_uint64_of_nat_mk(lungo_obj a0);
uint64_t lungo_lean_uint64_shift_left(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_uint64_shift_right(uint64_t a0, uint64_t a1);
uint64_t lungo_lean_uint64_sub(uint64_t a0, uint64_t a1);
double lungo_lean_uint64_to_float(uint64_t a0);
float lungo_lean_uint64_to_float32(uint64_t a0);
lungo_obj lungo_lean_uint64_to_nat(uint64_t a0);
uint16_t lungo_lean_uint64_to_uint16(uint64_t a0);
uint32_t lungo_lean_uint64_to_uint32(uint64_t a0);
uint8_t lungo_lean_uint64_to_uint8(uint64_t a0);
size_t lungo_lean_uint64_to_usize(uint64_t a0);
uint64_t lungo_lean_uint64_xor(uint64_t a0, uint64_t a1);
uint8_t lungo_lean_uint8_add(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_uint8_complement(uint8_t a0);
uint8_t lungo_lean_uint8_dec_eq(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_uint8_dec_le(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_uint8_dec_lt(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_uint8_div(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_uint8_land(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_uint8_log2(uint8_t a0);
uint8_t lungo_lean_uint8_lor(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_uint8_mod(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_uint8_mul(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_uint8_neg(uint8_t a0);
uint8_t lungo_lean_uint8_of_nat(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_uint8_of_nat_mk(lungo_obj a0);
uint8_t lungo_lean_uint8_shift_left(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_uint8_shift_right(uint8_t a0, uint8_t a1);
uint8_t lungo_lean_uint8_sub(uint8_t a0, uint8_t a1);
double lungo_lean_uint8_to_float(uint8_t a0);
float lungo_lean_uint8_to_float32(uint8_t a0);
lungo_obj lungo_lean_uint8_to_nat(uint8_t a0);
uint16_t lungo_lean_uint8_to_uint16(uint8_t a0);
uint32_t lungo_lean_uint8_to_uint32(uint8_t a0);
uint64_t lungo_lean_uint8_to_uint64(uint8_t a0);
size_t lungo_lean_uint8_to_usize(uint8_t a0);
uint8_t lungo_lean_uint8_xor(uint8_t a0, uint8_t a1);
size_t lungo_lean_usize_add(size_t a0, size_t a1);
size_t lungo_lean_usize_complement(size_t a0);
uint8_t lungo_lean_usize_dec_eq(size_t a0, size_t a1);
uint8_t lungo_lean_usize_dec_le(size_t a0, size_t a1);
uint8_t lungo_lean_usize_dec_lt(size_t a0, size_t a1);
size_t lungo_lean_usize_div(size_t a0, size_t a1);
size_t lungo_lean_usize_land(size_t a0, size_t a1);
size_t lungo_lean_usize_log2(size_t a0);
size_t lungo_lean_usize_lor(size_t a0, size_t a1);
size_t lungo_lean_usize_mod(size_t a0, size_t a1);
size_t lungo_lean_usize_mul(size_t a0, size_t a1);
size_t lungo_lean_usize_neg(size_t a0);
size_t lungo_lean_usize_of_nat(lungo_obj a0 /* borrowed */);
size_t lungo_lean_usize_of_nat_mk(lungo_obj a0);
size_t lungo_lean_usize_shift_left(size_t a0, size_t a1);
size_t lungo_lean_usize_shift_right(size_t a0, size_t a1);
size_t lungo_lean_usize_sub(size_t a0, size_t a1);
double lungo_lean_usize_to_float(size_t a0);
float lungo_lean_usize_to_float32(size_t a0);
lungo_obj lungo_lean_usize_to_nat(size_t a0);
uint16_t lungo_lean_usize_to_uint16(size_t a0);
uint32_t lungo_lean_usize_to_uint32(size_t a0);
uint64_t lungo_lean_usize_to_uint64(size_t a0);
uint8_t lungo_lean_usize_to_uint8(size_t a0);
size_t lungo_lean_usize_xor(size_t a0, size_t a1);
lungo_obj lungo_lean_uv_chdir(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_cpu_info(void);
lungo_obj lungo_lean_uv_cwd(void);
lungo_obj lungo_lean_uv_dns_get_info(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */, uint8_t a2);
lungo_obj lungo_lean_uv_dns_get_name(lungo_obj a0 /* borrowed */);
uint8_t lungo_lean_uv_event_loop_alive(void);
lungo_obj lungo_lean_uv_event_loop_configure(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_exepath(void);
lungo_obj lungo_lean_uv_get_available_memory(void);
lungo_obj lungo_lean_uv_get_constrained_memory(void);
lungo_obj lungo_lean_uv_get_free_memory(void);
lungo_obj lungo_lean_uv_get_process_title(void);
lungo_obj lungo_lean_uv_get_total_memory(void);
lungo_obj lungo_lean_uv_getrusage(void);
lungo_obj lungo_lean_uv_hrtime(void);
lungo_obj lungo_lean_uv_interface_addresses(void);
lungo_obj lungo_lean_uv_ntop_v4(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_ntop_v6(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_os_environ(void);
lungo_obj lungo_lean_uv_os_get_group(uint64_t a0);
lungo_obj lungo_lean_uv_os_get_passwd(void);
lungo_obj lungo_lean_uv_os_getenv(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_os_gethostname(void);
lungo_obj lungo_lean_uv_os_getpid(void);
lungo_obj lungo_lean_uv_os_getppid(void);
lungo_obj lungo_lean_uv_os_getpriority(uint64_t a0);
lungo_obj lungo_lean_uv_os_homedir(void);
lungo_obj lungo_lean_uv_os_setenv(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_uv_os_setpriority(uint64_t a0, uint64_t a1);
lungo_obj lungo_lean_uv_os_tmpdir(void);
lungo_obj lungo_lean_uv_os_uname(void);
lungo_obj lungo_lean_uv_os_unsetenv(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_pton_v4(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_pton_v6(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_random(uint64_t a0);
lungo_obj lungo_lean_uv_set_process_title(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_signal_cancel(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_signal_mk(uint32_t a0, uint8_t a1);
lungo_obj lungo_lean_uv_signal_next(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_signal_stop(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_tcp_accept(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_tcp_bind(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_uv_tcp_cancel_accept(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_tcp_cancel_recv(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_tcp_connect(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_uv_tcp_getpeername(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_tcp_getsockname(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_tcp_keepalive(lungo_obj a0 /* borrowed */, uint8_t a1, uint32_t a2);
lungo_obj lungo_lean_uv_tcp_listen(lungo_obj a0 /* borrowed */, uint32_t a1);
lungo_obj lungo_lean_uv_tcp_new(void);
lungo_obj lungo_lean_uv_tcp_nodelay(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_tcp_recv(lungo_obj a0 /* borrowed */, uint64_t a1);
lungo_obj lungo_lean_uv_tcp_send(lungo_obj a0 /* borrowed */, lungo_obj a1);
lungo_obj lungo_lean_uv_tcp_shutdown(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_tcp_try_accept(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_tcp_wait_readable(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_timer_cancel(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_timer_mk(uint64_t a0, uint8_t a1);
lungo_obj lungo_lean_uv_timer_next(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_timer_reset(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_timer_stop(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_udp_bind(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_uv_udp_cancel_recv(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_udp_connect(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_uv_udp_getpeername(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_udp_getsockname(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_udp_new(void);
lungo_obj lungo_lean_uv_udp_recv(lungo_obj a0 /* borrowed */, uint64_t a1);
lungo_obj lungo_lean_uv_udp_send(lungo_obj a0 /* borrowed */, lungo_obj a1, lungo_obj a2 /* borrowed */);
lungo_obj lungo_lean_uv_udp_set_broadcast(lungo_obj a0 /* borrowed */, uint8_t a1);
lungo_obj lungo_lean_uv_udp_set_membership(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */, lungo_obj a2 /* borrowed */, uint8_t a3);
lungo_obj lungo_lean_uv_udp_set_multicast_interface(lungo_obj a0 /* borrowed */, lungo_obj a1 /* borrowed */);
lungo_obj lungo_lean_uv_udp_set_multicast_loop(lungo_obj a0 /* borrowed */, uint8_t a1);
lungo_obj lungo_lean_uv_udp_set_multicast_ttl(lungo_obj a0 /* borrowed */, uint32_t a1);
lungo_obj lungo_lean_uv_udp_set_ttl(lungo_obj a0 /* borrowed */, uint32_t a1);
lungo_obj lungo_lean_uv_udp_wait_readable(lungo_obj a0 /* borrowed */);
lungo_obj lungo_lean_uv_uptime(void);
uint8_t lungo_lean_version_get_is_release(lungo_obj a0);
lungo_obj lungo_lean_version_get_major(lungo_obj a0);
lungo_obj lungo_lean_version_get_minor(lungo_obj a0);
lungo_obj lungo_lean_version_get_patch(lungo_obj a0);
lungo_obj lungo_lean_version_get_special_desc(lungo_obj a0);
lungo_obj lungo_lean_void_mk(lungo_obj a0);
lungo_obj lungo_lean_windows_get_next_transition(lungo_obj a0 /* borrowed */, uint64_t a1, uint8_t a2);
double lungo_log(double a0);
double lungo_log10(double a0);
float lungo_log10f(float a0);
double lungo_log2(double a0);
float lungo_log2f(float a0);
float lungo_logf(float a0);
double lungo_pow(double a0, double a1);
float lungo_powf(float a0, float a1);
double lungo_round(double a0);
float lungo_roundf(float a0);
double lungo_sin(double a0);
float lungo_sinf(float a0);
double lungo_sinh(double a0);
float lungo_sinhf(float a0);
double lungo_sqrt(double a0);
float lungo_sqrtf(float a0);
double lungo_tan(double a0);
float lungo_tanf(float a0);
double lungo_tanh(double a0);
float lungo_tanhf(float a0);
/* END GENERATED: runtime primitives */

#ifdef __cplusplus
}
#endif

#endif /* LUNGO_H */
