/* Generated by lungo 1.68.2857 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
#include "tagged_urn_formal_program.h"

/* The runtime calls IO.Error.toString as `lean_io_error_to_string`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dtoString(lungo_obj a_0) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dtoString(a_0);
    return r;
}

/* The runtime calls IO.FS.Stream.ofHandle as `lean_stream_of_handle`. */
static lungo_obj tagged_urn_formal__e_l_IO_dFS_dStream_dofHandle(lungo_obj a_0) {
    lungo_obj r = tagged_urn_formal__l_IO_dFS_dStream_dofHandle(a_0);
    return r;
}

/* The runtime calls _private.Init.System.IO.0.IO.eprintlnAux as `lean_io_eprintln`. */
static lungo_obj tagged_urn_formal__e_l___private_dInit_dSystem_dIO_d0_dIO_deprintlnAux(lungo_obj a_0) {
    lungo_obj r = tagged_urn_formal__l___private_dInit_dSystem_dIO_d0_dIO_deprintlnAux(a_0);
    return r;
}

/* The runtime calls IO.userError as `lean_mk_io_user_error`. */
static lungo_obj tagged_urn_formal__e_l_IO_duserError(lungo_obj a_0) {
    lungo_obj r = tagged_urn_formal__l_IO_duserError(a_0);
    return r;
}

/* The runtime calls IO.Error.mkEofError as `lean_mk_io_error_eof`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkEofError(lungo_obj a_0) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkEofError(a_0);
    return r;
}

/* The runtime calls IO.Error.mkAlreadyExists as `lean_mk_io_error_already_exists`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkAlreadyExists(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkAlreadyExists(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkAlreadyExistsFile as `lean_mk_io_error_already_exists_file`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkAlreadyExistsFile(lungo_obj a_0, uint32_t a_1, lungo_obj a_2) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkAlreadyExistsFile(a_0, a_1, a_2);
    return r;
}

/* The runtime calls IO.Error.mkHardwareFault as `lean_mk_io_error_hardware_fault`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkHardwareFault(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkHardwareFault(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkIllegalOperation as `lean_mk_io_error_illegal_operation`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkIllegalOperation(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkIllegalOperation(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkInappropriateType as `lean_mk_io_error_inappropriate_type`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkInappropriateType(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkInappropriateType(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkInappropriateTypeFile as `lean_mk_io_error_inappropriate_type_file`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkInappropriateTypeFile(lungo_obj a_0, uint32_t a_1, lungo_obj a_2) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkInappropriateTypeFile(a_0, a_1, a_2);
    return r;
}

/* The runtime calls IO.Error.mkInterrupted as `lean_mk_io_error_interrupted`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkInterrupted(lungo_obj a_0, uint32_t a_1, lungo_obj a_2) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkInterrupted(a_0, a_1, a_2);
    return r;
}

/* The runtime calls IO.Error.mkInvalidArgument as `lean_mk_io_error_invalid_argument`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkInvalidArgument(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkInvalidArgument(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkInvalidArgumentFile as `lean_mk_io_error_invalid_argument_file`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkInvalidArgumentFile(lungo_obj a_0, uint32_t a_1, lungo_obj a_2) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkInvalidArgumentFile(a_0, a_1, a_2);
    return r;
}

/* The runtime calls IO.Error.mkNoFileOrDirectory as `lean_mk_io_error_no_file_or_directory`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkNoFileOrDirectory(lungo_obj a_0, uint32_t a_1, lungo_obj a_2) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkNoFileOrDirectory(a_0, a_1, a_2);
    return r;
}

/* The runtime calls IO.Error.mkNoSuchThing as `lean_mk_io_error_no_such_thing`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkNoSuchThing(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkNoSuchThing(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkNoSuchThingFile as `lean_mk_io_error_no_such_thing_file`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkNoSuchThingFile(lungo_obj a_0, uint32_t a_1, lungo_obj a_2) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkNoSuchThingFile(a_0, a_1, a_2);
    return r;
}

/* The runtime calls IO.Error.mkOtherError as `lean_mk_io_error_other_error`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkOtherError(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkOtherError(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkPermissionDenied as `lean_mk_io_error_permission_denied`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkPermissionDenied(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkPermissionDenied(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkPermissionDeniedFile as `lean_mk_io_error_permission_denied_file`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkPermissionDeniedFile(lungo_obj a_0, uint32_t a_1, lungo_obj a_2) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkPermissionDeniedFile(a_0, a_1, a_2);
    return r;
}

/* The runtime calls IO.Error.mkProtocolError as `lean_mk_io_error_protocol_error`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkProtocolError(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkProtocolError(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkResourceBusy as `lean_mk_io_error_resource_busy`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkResourceBusy(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkResourceBusy(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkResourceExhausted as `lean_mk_io_error_resource_exhausted`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkResourceExhausted(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkResourceExhausted(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkResourceExhaustedFile as `lean_mk_io_error_resource_exhausted_file`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkResourceExhaustedFile(lungo_obj a_0, uint32_t a_1, lungo_obj a_2) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkResourceExhaustedFile(a_0, a_1, a_2);
    return r;
}

/* The runtime calls IO.Error.mkResourceVanished as `lean_mk_io_error_resource_vanished`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkResourceVanished(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkResourceVanished(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkTimeExpired as `lean_mk_io_error_time_expired`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkTimeExpired(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkTimeExpired(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkUnsatisfiedConstraints as `lean_mk_io_error_unsatisfied_constraints`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkUnsatisfiedConstraints(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkUnsatisfiedConstraints(a_0, a_1);
    return r;
}

/* The runtime calls IO.Error.mkUnsupportedOperation as `lean_mk_io_error_unsupported_operation`. */
static lungo_obj tagged_urn_formal__e_l_IO_dError_dmkUnsupportedOperation(uint32_t a_0, lungo_obj a_1) {
    lungo_obj r = tagged_urn_formal__l_IO_dError_dmkUnsupportedOperation(a_0, a_1);
    return r;
}

static uint64_t tagged_urn_formal__initialize_once(void) {
    /* A runtime of another C ABI version does not define lungo_abi_v1: linking fails. */
    if (lungo_abi_v1() != LUNGO_ABI_VERSION) lungo_panic_unreachable();
    /* Initializers may call host externs: every one must be registered. */
    tagged_urn_formal__check_host_externs();
    lungo_register_export("lean_io_error_to_string", (void *)tagged_urn_formal__e_l_IO_dError_dtoString);
    lungo_register_export("lean_stream_of_handle", (void *)tagged_urn_formal__e_l_IO_dFS_dStream_dofHandle);
    lungo_register_export("lean_io_eprintln", (void *)tagged_urn_formal__e_l___private_dInit_dSystem_dIO_d0_dIO_deprintlnAux);
    lungo_register_export("lean_mk_io_user_error", (void *)tagged_urn_formal__e_l_IO_duserError);
    lungo_register_export("lean_mk_io_error_eof", (void *)tagged_urn_formal__e_l_IO_dError_dmkEofError);
    lungo_register_export("lean_mk_io_error_already_exists", (void *)tagged_urn_formal__e_l_IO_dError_dmkAlreadyExists);
    lungo_register_export("lean_mk_io_error_already_exists_file", (void *)tagged_urn_formal__e_l_IO_dError_dmkAlreadyExistsFile);
    lungo_register_export("lean_mk_io_error_hardware_fault", (void *)tagged_urn_formal__e_l_IO_dError_dmkHardwareFault);
    lungo_register_export("lean_mk_io_error_illegal_operation", (void *)tagged_urn_formal__e_l_IO_dError_dmkIllegalOperation);
    lungo_register_export("lean_mk_io_error_inappropriate_type", (void *)tagged_urn_formal__e_l_IO_dError_dmkInappropriateType);
    lungo_register_export("lean_mk_io_error_inappropriate_type_file", (void *)tagged_urn_formal__e_l_IO_dError_dmkInappropriateTypeFile);
    lungo_register_export("lean_mk_io_error_interrupted", (void *)tagged_urn_formal__e_l_IO_dError_dmkInterrupted);
    lungo_register_export("lean_mk_io_error_invalid_argument", (void *)tagged_urn_formal__e_l_IO_dError_dmkInvalidArgument);
    lungo_register_export("lean_mk_io_error_invalid_argument_file", (void *)tagged_urn_formal__e_l_IO_dError_dmkInvalidArgumentFile);
    lungo_register_export("lean_mk_io_error_no_file_or_directory", (void *)tagged_urn_formal__e_l_IO_dError_dmkNoFileOrDirectory);
    lungo_register_export("lean_mk_io_error_no_such_thing", (void *)tagged_urn_formal__e_l_IO_dError_dmkNoSuchThing);
    lungo_register_export("lean_mk_io_error_no_such_thing_file", (void *)tagged_urn_formal__e_l_IO_dError_dmkNoSuchThingFile);
    lungo_register_export("lean_mk_io_error_other_error", (void *)tagged_urn_formal__e_l_IO_dError_dmkOtherError);
    lungo_register_export("lean_mk_io_error_permission_denied", (void *)tagged_urn_formal__e_l_IO_dError_dmkPermissionDenied);
    lungo_register_export("lean_mk_io_error_permission_denied_file", (void *)tagged_urn_formal__e_l_IO_dError_dmkPermissionDeniedFile);
    lungo_register_export("lean_mk_io_error_protocol_error", (void *)tagged_urn_formal__e_l_IO_dError_dmkProtocolError);
    lungo_register_export("lean_mk_io_error_resource_busy", (void *)tagged_urn_formal__e_l_IO_dError_dmkResourceBusy);
    lungo_register_export("lean_mk_io_error_resource_exhausted", (void *)tagged_urn_formal__e_l_IO_dError_dmkResourceExhausted);
    lungo_register_export("lean_mk_io_error_resource_exhausted_file", (void *)tagged_urn_formal__e_l_IO_dError_dmkResourceExhaustedFile);
    lungo_register_export("lean_mk_io_error_resource_vanished", (void *)tagged_urn_formal__e_l_IO_dError_dmkResourceVanished);
    lungo_register_export("lean_mk_io_error_time_expired", (void *)tagged_urn_formal__e_l_IO_dError_dmkTimeExpired);
    lungo_register_export("lean_mk_io_error_unsatisfied_constraints", (void *)tagged_urn_formal__e_l_IO_dError_dmkUnsatisfiedConstraints);
    lungo_register_export("lean_mk_io_error_unsupported_operation", (void *)tagged_urn_formal__e_l_IO_dError_dmkUnsupportedOperation);
    /* Init.Data.Random */
    {
        lungo_obj v = lungo_check_initializer("IO.stdGenRef", tagged_urn_formal__l___private_dInit_dData_dRandom_d0_dinitFn_d___x40__dInit_dData_dRandom_d2456098205_d__hygCtx_d__hyg_d2());
        lungo_init_obj_set(&tagged_urn_formal__I_l_IO_dstdGenRef, v);
    }
    lungo_end_initialization();
    return 1;
}
static lungo_lazy_bits tagged_urn_formal__initialized;
/* Initializes the program; concurrent and repeated calls initialize it once. */
void tagged_urn_formal__initialize(void) {
    (void)lungo_lazy_bits_get(&tagged_urn_formal__initialized, tagged_urn_formal__initialize_once);
}

