/* Generated by lungo 1.83.0 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
#include "tagged_urn_formal_program.h"

static const uint8_t tagged_urn_formal__type_table[] = {
    0x4c, 0x4e, 0x47, 0x54, 0x02, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x11, 0x00, 0x00, 0x00,
    0x54, 0x61, 0x67, 0x67, 0x65, 0x64, 0x55, 0x72, 0x6e, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x2e, 0x57,
    0x66, 0x01, 0x00, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x00, 0x00, 0x00,
    0x54, 0x61, 0x67, 0x67, 0x65, 0x64, 0x55, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72,
    0x61, 0x69, 0x6e, 0x74, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07, 0x00, 0x07, 0x00, 0x00, 0x00, 0x1c,
    0x00, 0x00, 0x00, 0x54, 0x61, 0x67, 0x67, 0x65, 0x64, 0x55, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x6e,
    0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x2e, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x22, 0x00, 0x00, 0x00, 0x54, 0x61, 0x67, 0x67, 0x65, 0x64, 0x55, 0x72, 0x6e,
    0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x2e, 0x75, 0x6e, 0x63, 0x6f,
    0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00,
    0x00, 0x54, 0x61, 0x67, 0x67, 0x65, 0x64, 0x55, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74,
    0x72, 0x61, 0x69, 0x6e, 0x74, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x4e, 0x6f,
    0x74, 0x02, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x01, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x10, 0x1c, 0x00, 0x00, 0x00, 0x54, 0x61, 0x67, 0x67, 0x65, 0x64, 0x55, 0x72,
    0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x65,
    0x73, 0x65, 0x6e, 0x74, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1f, 0x00, 0x00, 0x00, 0x54, 0x61, 0x67, 0x67,
    0x65, 0x64, 0x55, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74,
    0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x04, 0x00, 0x00, 0x00, 0x01,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x05,
    0x00, 0x00, 0x00, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x1a, 0x00,
    0x00, 0x00, 0x54, 0x61, 0x67, 0x67, 0x65, 0x64, 0x55, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x73,
    0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x2e, 0x65, 0x78, 0x61, 0x63, 0x74, 0x05, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
    0x05, 0x00, 0x00, 0x00, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x1b,
    0x00, 0x00, 0x00, 0x54, 0x61, 0x67, 0x67, 0x65, 0x64, 0x55, 0x72, 0x6e, 0x2e, 0x43, 0x6f, 0x6e,
    0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x2e, 0x61, 0x62, 0x73, 0x65, 0x6e, 0x74, 0x06, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00,
};
static lungo_lazy_bits tagged_urn_formal__types_cell;
static uint64_t tagged_urn_formal__types_load(void) {
    return (uint64_t)(uintptr_t)lungo_types_load(tagged_urn_formal__type_table, 498);
}
const lungo_types *tagged_urn_formal__types(void) {
    return (const lungo_types *)(uintptr_t)lungo_lazy_bits_get(&tagged_urn_formal__types_cell, tagged_urn_formal__types_load);
}

static uint64_t tagged_urn_formal__host_callbacks[1];
/* Registers the host's implementation of host extern `index`, before the program is initialized. */
void tagged_urn_formal__set_host_extern(size_t index, uint64_t callback) {
    if (index >= 0 || callback == 0) lungo_panic_unreachable();
    tagged_urn_formal__host_callbacks[index] = callback;
}
void tagged_urn_formal__check_host_externs(void) {
}

static const uint8_t tagged_urn_formal__t_0[] = {
    0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_1[] = {
    0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_2[] = {
    0x02,
};
static const uint8_t tagged_urn_formal__t_3[] = {
    0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_4[] = {
    0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_5[] = {
    0x02,
};
static const uint8_t tagged_urn_formal__t_6[] = {
    0x10,
};
static const uint8_t tagged_urn_formal__t_7[] = {
    0x15, 0x17, 0x10, 0x1b, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_8[] = {
    0x14, 0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_9[] = {
    0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_10[] = {
    0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_11[] = {
    0x02,
};
static const uint8_t tagged_urn_formal__t_12[] = {
    0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_13[] = {
    0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_14[] = {
    0x02,
};
static const uint8_t tagged_urn_formal__t_15[] = {
    0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_16[] = {
    0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_17[] = {
    0x02,
};
static const uint8_t tagged_urn_formal__t_18[] = {
    0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_19[] = {
    0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_20[] = {
    0x02,
};
static const uint8_t tagged_urn_formal__t_21[] = {
    0x1b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_22[] = {
    0x00,
};
static const uint8_t tagged_urn_formal__t_23[] = {
    0x1b, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_24[] = {
    0x1b, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_25[] = {
    0x02,
};
static const uint8_t tagged_urn_formal__t_26[] = {
    0x1b, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_27[] = {
    0x1b, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_28[] = {
    0x02,
};
static const uint8_t tagged_urn_formal__t_29[] = {
    0x1b, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_30[] = {
    0x1b, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
static const uint8_t tagged_urn_formal__t_31[] = {
    0x02,
};

/* TaggedUrn.Exec.comparable : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dcomparable(const uint8_t *input, size_t len, lungo_buffer *out) {
    tagged_urn_formal__initialize();
    lungo_call *call = lungo_call_begin(tagged_urn_formal__types(), input, len);
    lungo_obj a_0 = lungo_call_read(call, tagged_urn_formal__t_0, 9);
    lungo_obj a_1 = lungo_call_read(call, tagged_urn_formal__t_1, 9);
    if (!lungo_call_complete(call)) {
        lungo_dec(a_0);
        lungo_dec(a_1);
        return lungo_call_end(call, out);
    }
    uint8_t r = tagged_urn_formal__l_TaggedUrn_dExec_dcomparable(a_0, a_1);
    lungo_dec(a_0);
    lungo_dec(a_1);
    lungo_call_write(call, lungo_box((size_t)r), tagged_urn_formal__t_2, 1);
    return lungo_call_end(call, out);
}

/* TaggedUrn.Exec.equivalent : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dequivalent(const uint8_t *input, size_t len, lungo_buffer *out) {
    tagged_urn_formal__initialize();
    lungo_call *call = lungo_call_begin(tagged_urn_formal__types(), input, len);
    lungo_obj a_0 = lungo_call_read(call, tagged_urn_formal__t_3, 9);
    lungo_obj a_1 = lungo_call_read(call, tagged_urn_formal__t_4, 9);
    if (!lungo_call_complete(call)) {
        lungo_dec(a_0);
        lungo_dec(a_1);
        return lungo_call_end(call, out);
    }
    uint8_t r = tagged_urn_formal__l_TaggedUrn_dExec_dequivalent(a_0, a_1);
    lungo_dec(a_0);
    lungo_dec(a_1);
    lungo_call_write(call, lungo_box((size_t)r), tagged_urn_formal__t_5, 1);
    return lungo_call_end(call, out);
}

/* TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf */
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dmake(const uint8_t *input, size_t len, lungo_buffer *out) {
    tagged_urn_formal__initialize();
    lungo_call *call = lungo_call_begin(tagged_urn_formal__types(), input, len);
    lungo_obj a_0 = lungo_call_read(call, tagged_urn_formal__t_6, 1);
    lungo_obj a_1 = lungo_call_read(call, tagged_urn_formal__t_7, 12);
    if (!lungo_call_complete(call)) {
        lungo_dec(a_0);
        lungo_dec(a_1);
        return lungo_call_end(call, out);
    }
    lungo_obj r = tagged_urn_formal__l_TaggedUrn_dExec_dmake(a_0, a_1);
    lungo_call_write(call, r, tagged_urn_formal__t_8, 10);
    return lungo_call_end(call, out);
}

/* TaggedUrn.Exec.meets : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dmeets(const uint8_t *input, size_t len, lungo_buffer *out) {
    tagged_urn_formal__initialize();
    lungo_call *call = lungo_call_begin(tagged_urn_formal__types(), input, len);
    lungo_obj a_0 = lungo_call_read(call, tagged_urn_formal__t_9, 9);
    lungo_obj a_1 = lungo_call_read(call, tagged_urn_formal__t_10, 9);
    if (!lungo_call_complete(call)) {
        lungo_dec(a_0);
        lungo_dec(a_1);
        return lungo_call_end(call, out);
    }
    uint8_t r = tagged_urn_formal__l_TaggedUrn_dExec_dmeets(a_0, a_1);
    lungo_call_write(call, lungo_box((size_t)r), tagged_urn_formal__t_11, 1);
    return lungo_call_end(call, out);
}

/* TaggedUrn.Exec.meetsClosed : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dmeetsClosed(const uint8_t *input, size_t len, lungo_buffer *out) {
    tagged_urn_formal__initialize();
    lungo_call *call = lungo_call_begin(tagged_urn_formal__types(), input, len);
    lungo_obj a_0 = lungo_call_read(call, tagged_urn_formal__t_12, 9);
    lungo_obj a_1 = lungo_call_read(call, tagged_urn_formal__t_13, 9);
    if (!lungo_call_complete(call)) {
        lungo_dec(a_0);
        lungo_dec(a_1);
        return lungo_call_end(call, out);
    }
    uint8_t r = tagged_urn_formal__l_TaggedUrn_dExec_dmeetsClosed(a_0, a_1);
    lungo_call_write(call, lungo_box((size_t)r), tagged_urn_formal__t_14, 1);
    return lungo_call_end(call, out);
}

/* TaggedUrn.Exec.refines : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_drefines(const uint8_t *input, size_t len, lungo_buffer *out) {
    tagged_urn_formal__initialize();
    lungo_call *call = lungo_call_begin(tagged_urn_formal__types(), input, len);
    lungo_obj a_0 = lungo_call_read(call, tagged_urn_formal__t_15, 9);
    lungo_obj a_1 = lungo_call_read(call, tagged_urn_formal__t_16, 9);
    if (!lungo_call_complete(call)) {
        lungo_dec(a_0);
        lungo_dec(a_1);
        return lungo_call_end(call, out);
    }
    uint8_t r = tagged_urn_formal__l_TaggedUrn_dExec_drefines(a_0, a_1);
    lungo_dec(a_0);
    lungo_dec(a_1);
    lungo_call_write(call, lungo_box((size_t)r), tagged_urn_formal__t_17, 1);
    return lungo_call_end(call, out);
}

/* TaggedUrn.Exec.refinesClosed : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool */
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_drefinesClosed(const uint8_t *input, size_t len, lungo_buffer *out) {
    tagged_urn_formal__initialize();
    lungo_call *call = lungo_call_begin(tagged_urn_formal__types(), input, len);
    lungo_obj a_0 = lungo_call_read(call, tagged_urn_formal__t_18, 9);
    lungo_obj a_1 = lungo_call_read(call, tagged_urn_formal__t_19, 9);
    if (!lungo_call_complete(call)) {
        lungo_dec(a_0);
        lungo_dec(a_1);
        return lungo_call_end(call, out);
    }
    uint8_t r = tagged_urn_formal__l_TaggedUrn_dExec_drefinesClosed(a_0, a_1);
    lungo_call_write(call, lungo_box((size_t)r), tagged_urn_formal__t_20, 1);
    return lungo_call_end(call, out);
}

/* TaggedUrn.Exec.specificity : TaggedUrn.Exec.Wf → Nat */
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dspecificity(const uint8_t *input, size_t len, lungo_buffer *out) {
    tagged_urn_formal__initialize();
    lungo_call *call = lungo_call_begin(tagged_urn_formal__types(), input, len);
    lungo_obj a_0 = lungo_call_read(call, tagged_urn_formal__t_21, 9);
    if (!lungo_call_complete(call)) {
        lungo_dec(a_0);
        return lungo_call_end(call, out);
    }
    lungo_obj r = tagged_urn_formal__l_TaggedUrn_dExec_dspecificity(a_0);
    lungo_call_write(call, r, tagged_urn_formal__t_22, 1);
    return lungo_call_end(call, out);
}

/* TaggedUrn.Exec.valuesMatch : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool */
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMatch(const uint8_t *input, size_t len, lungo_buffer *out) {
    tagged_urn_formal__initialize();
    lungo_call *call = lungo_call_begin(tagged_urn_formal__types(), input, len);
    lungo_obj a_0 = lungo_call_read(call, tagged_urn_formal__t_23, 9);
    lungo_obj a_1 = lungo_call_read(call, tagged_urn_formal__t_24, 9);
    if (!lungo_call_complete(call)) {
        lungo_dec(a_0);
        lungo_dec(a_1);
        return lungo_call_end(call, out);
    }
    uint8_t r = tagged_urn_formal__l_TaggedUrn_dExec_dvaluesMatch(a_0, a_1);
    lungo_dec(a_0);
    lungo_dec(a_1);
    lungo_call_write(call, lungo_box((size_t)r), tagged_urn_formal__t_25, 1);
    return lungo_call_end(call, out);
}

/* TaggedUrn.Exec.valuesMatchClosed : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool */
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMatchClosed(const uint8_t *input, size_t len, lungo_buffer *out) {
    tagged_urn_formal__initialize();
    lungo_call *call = lungo_call_begin(tagged_urn_formal__types(), input, len);
    lungo_obj a_0 = lungo_call_read(call, tagged_urn_formal__t_26, 9);
    lungo_obj a_1 = lungo_call_read(call, tagged_urn_formal__t_27, 9);
    if (!lungo_call_complete(call)) {
        lungo_dec(a_0);
        lungo_dec(a_1);
        return lungo_call_end(call, out);
    }
    uint8_t r = tagged_urn_formal__l_TaggedUrn_dExec_dvaluesMatchClosed(a_0, a_1);
    lungo_dec(a_0);
    lungo_dec(a_1);
    lungo_call_write(call, lungo_box((size_t)r), tagged_urn_formal__t_28, 1);
    return lungo_call_end(call, out);
}

/* TaggedUrn.Exec.valuesMeet : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool */
int32_t tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMeet(const uint8_t *input, size_t len, lungo_buffer *out) {
    tagged_urn_formal__initialize();
    lungo_call *call = lungo_call_begin(tagged_urn_formal__types(), input, len);
    lungo_obj a_0 = lungo_call_read(call, tagged_urn_formal__t_29, 9);
    lungo_obj a_1 = lungo_call_read(call, tagged_urn_formal__t_30, 9);
    if (!lungo_call_complete(call)) {
        lungo_dec(a_0);
        lungo_dec(a_1);
        return lungo_call_end(call, out);
    }
    uint8_t r = tagged_urn_formal__l_TaggedUrn_dExec_dvaluesMeet(a_0, a_1);
    lungo_dec(a_0);
    lungo_dec(a_1);
    lungo_call_write(call, lungo_box((size_t)r), tagged_urn_formal__t_31, 1);
    return lungo_call_end(call, out);
}

