"""The Lean program tagged_urn_formal (generated by lungo 1.83.0 from Lean 4.34.1). Do not edit."""

from __future__ import annotations

import os as _os
import sys as _sys
import typing as _t
from dataclasses import dataclass as _dataclass

import lungo_py

if lungo_py.__version__ != "1.83.0":
    raise ImportError(f"this package needs lungo_py 1.83.0, not {lungo_py.__version__}")


def _library() -> str:
    name = {"win32": "tagged_urn_formal_lean.dll", "darwin": "libtagged_urn_formal_lean.dylib"}.get(_sys.platform, "libtagged_urn_formal_lean.so")
    for directory in __path__:
        path = _os.path.join(directory, name)
        if _os.path.isfile(path):
            return path
    raise ImportError(f"the compiled program {name} is in none of {list(__path__)}: install the package with pip")


_program = lungo_py.Program(_library(), "tagged_urn_formal__types")


class Wf(lungo_py.Opaque):
    """Lean's TaggedUrn.Exec.Wf, held by handle: only the program's functions make and read its values."""

    __slots__ = ()


class _WfType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(0)

    def encode(self, w, v):
        if not isinstance(v, Wf):
            raise lungo_py.MalformedError(f"{v!r} is not a TaggedUrn.Exec.Wf")
        lungo_py.OPAQUE.encode(w, v)

    def decode(self, r):
        return Wf(r.u64())


def wf_type() -> lungo_py.Type[Wf]:
    """Describes TaggedUrn.Exec.Wf for polymorphic functions."""
    return _WfType()


Wf.__lungo_fingerprint__ = "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785"
Wf.__lungo_descriptor__ = staticmethod(wf_type)


class Constraint:
    """Lean's TaggedUrn.Constraint: one of ConstraintMissing, ConstraintUnconstrained, ConstraintOptionalNot, ConstraintPresent, ConstraintPresentNot, ConstraintExact, ConstraintAbsent."""

    __slots__ = ()


@_dataclass(frozen=True)
class ConstraintMissing(Constraint):
    """Lean's TaggedUrn.Constraint.missing."""


@_dataclass(frozen=True)
class ConstraintUnconstrained(Constraint):
    """Lean's TaggedUrn.Constraint.unconstrained."""


@_dataclass(frozen=True)
class ConstraintOptionalNot(Constraint):
    """Lean's TaggedUrn.Constraint.optionalNot."""
    value: str


@_dataclass(frozen=True)
class ConstraintPresent(Constraint):
    """Lean's TaggedUrn.Constraint.present."""


@_dataclass(frozen=True)
class ConstraintPresentNot(Constraint):
    """Lean's TaggedUrn.Constraint.presentNot."""
    value: str


@_dataclass(frozen=True)
class ConstraintExact(Constraint):
    """Lean's TaggedUrn.Constraint.exact."""
    value: str


@_dataclass(frozen=True)
class ConstraintAbsent(Constraint):
    """Lean's TaggedUrn.Constraint.absent."""


class _ConstraintType(lungo_py.Type):
    def expr(self):
        return lungo_py.inductive_expr(1)

    def encode(self, w, v):
        if isinstance(v, ConstraintMissing):
            w.u32(0)
        elif isinstance(v, ConstraintUnconstrained):
            w.u32(1)
        elif isinstance(v, ConstraintOptionalNot):
            w.u32(2)
            lungo_py.STRING.encode(w, v.value)
        elif isinstance(v, ConstraintPresent):
            w.u32(3)
        elif isinstance(v, ConstraintPresentNot):
            w.u32(4)
            lungo_py.STRING.encode(w, v.value)
        elif isinstance(v, ConstraintExact):
            w.u32(5)
            lungo_py.STRING.encode(w, v.value)
        elif isinstance(v, ConstraintAbsent):
            w.u32(6)
        else:
            raise lungo_py.MalformedError(f"{v!r} is not a TaggedUrn.Constraint")

    def decode(self, r):
        c = r.u32()
        if c == 0:
            return ConstraintMissing()
        if c == 1:
            return ConstraintUnconstrained()
        if c == 2:
            return ConstraintOptionalNot(lungo_py.STRING.decode(r))
        if c == 3:
            return ConstraintPresent()
        if c == 4:
            return ConstraintPresentNot(lungo_py.STRING.decode(r))
        if c == 5:
            return ConstraintExact(lungo_py.STRING.decode(r))
        if c == 6:
            return ConstraintAbsent()
        raise lungo_py.MalformedError(f"constructor index {c} of TaggedUrn.Constraint")


def constraint_type() -> lungo_py.Type[Constraint]:
    """Describes TaggedUrn.Constraint for polymorphic functions."""
    return _ConstraintType()


Constraint.__lungo_fingerprint__ = "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7"
Constraint.__lungo_descriptor__ = staticmethod(constraint_type)


def comparable(a: Wf, b: Wf) -> bool:
    """Lean's TaggedUrn.Exec.comparable : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool"""
    return _program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dcomparable", (), ((wf_type(), a), (wf_type(), b),), lungo_py.value(lungo_py.BOOL))


def equivalent(a: Wf, b: Wf) -> bool:
    """Lean's TaggedUrn.Exec.equivalent : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool"""
    return _program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dequivalent", (), ((wf_type(), a), (wf_type(), b),), lungo_py.value(lungo_py.BOOL))


def make(scheme: str, tags: _t.List[_t.Tuple[str, Constraint]]) -> _t.Optional[Wf]:
    """Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf"""
    return _program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dmake", (), ((lungo_py.STRING, scheme), (lungo_py.list_of(lungo_py.pair(lungo_py.STRING, constraint_type())), tags),), lungo_py.value(lungo_py.option(wf_type())))


def meets(a: Wf, b: Wf) -> bool:
    """Lean's TaggedUrn.Exec.meets : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool"""
    return _program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dmeets", (), ((wf_type(), a), (wf_type(), b),), lungo_py.value(lungo_py.BOOL))


def meets_closed(a: Wf, b: Wf) -> bool:
    """Lean's TaggedUrn.Exec.meetsClosed : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool"""
    return _program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dmeetsClosed", (), ((wf_type(), a), (wf_type(), b),), lungo_py.value(lungo_py.BOOL))


def refines(a: Wf, b: Wf) -> bool:
    """Lean's TaggedUrn.Exec.refines : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool"""
    return _program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_drefines", (), ((wf_type(), a), (wf_type(), b),), lungo_py.value(lungo_py.BOOL))


def refines_closed(a: Wf, b: Wf) -> bool:
    """Lean's TaggedUrn.Exec.refinesClosed : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool"""
    return _program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_drefinesClosed", (), ((wf_type(), a), (wf_type(), b),), lungo_py.value(lungo_py.BOOL))


def specificity(a: Wf) -> int:
    """Lean's TaggedUrn.Exec.specificity : TaggedUrn.Exec.Wf → Nat"""
    return _program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dspecificity", (), ((wf_type(), a),), lungo_py.value(lungo_py.NAT))


def values_match(inst: Constraint, patt: Constraint) -> bool:
    """Lean's TaggedUrn.Exec.valuesMatch : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool"""
    return _program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMatch", (), ((constraint_type(), inst), (constraint_type(), patt),), lungo_py.value(lungo_py.BOOL))


def values_match_closed(inst: Constraint, patt: Constraint) -> bool:
    """Lean's TaggedUrn.Exec.valuesMatchClosed : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool"""
    return _program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMatchClosed", (), ((constraint_type(), inst), (constraint_type(), patt),), lungo_py.value(lungo_py.BOOL))


def values_meet(a: Constraint, b: Constraint) -> bool:
    """Lean's TaggedUrn.Exec.valuesMeet : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool"""
    return _program.invoke("tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMeet", (), ((constraint_type(), a), (constraint_type(), b),), lungo_py.value(lungo_py.BOOL))
