/* Generated by lungo 1.67.2841 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.Nat.Bitwise.Basic. */
#include "tagged_urn_formal_program.h"

/* Lean: Nat.shiftRight */
/* Source: <lean>/Init/Data/Nat/Bitwise/Basic.lean:83:1 */
lungo_obj tagged_urn_formal__l_Nat_dshiftRight(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj r = lungo_lean_nat_shiftr(x_1, x_2);
    return r;
}

