/* Generated by lungo 1.86.160 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.Format.Syntax. */
#include "tagged_urn_formal_program.h"

/* Lean: List.foldl._at_.Std.Format.joinSep._at_.Lean.Syntax.formatStxAux.spec_2.spec_2 */
/* Compiled from: List.foldl */
/* Source: <lean>/Init/Prelude.lean:3102:1 */
lungo_obj tagged_urn_formal__l_List_dfoldl_d__at___dStd_dFormat_djoinSep_d__at___dLean_dSyntax_dformatStxAux_dspec__2_dspec__2(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_13;
    uint8_t x_14;
    _start:
    switch (lungo_obj_tag(x_3)) {
        case 0: {
            lungo_dec(x_1);
            return x_2;
        }
        default: {
            x_4 = lungo_ctor_get(x_3, 0);
            x_5 = lungo_ctor_get(x_3, 1);
            x_14 = !lungo_is_exclusive(x_3);
            switch (x_14) {
                case 0: {
                    x_7 = x_3;
                    x_8 = x_14;
                    goto block_6;
                }
                default: {
                    lungo_inc(x_5);
                    lungo_inc(x_4);
                    lungo_dec(x_3);
                    x_7 = lungo_box(0);
                    x_8 = x_14;
                    goto block_6;
                }
            }
            block_6:;
            lungo_inc(x_1);
            switch (x_8) {
                case 0: {
                    lungo_ctor_set_tag(x_7, 5);
                    lungo_ctor_set(x_7, 1, x_1);
                    lungo_ctor_set(x_7, 0, x_2);
                    x_10 = x_7;
                    goto block_9;
                }
                default: {
                    x_13 = lungo_alloc_ctor(5, 2, 0);
                    lungo_ctor_set(x_13, 0, x_2);
                    lungo_ctor_set(x_13, 1, x_1);
                    x_10 = x_13;
                    goto block_9;
                }
            }
            block_9:;
            x_11 = lungo_alloc_ctor(5, 2, 0);
            lungo_ctor_set(x_11, 0, x_10);
            lungo_ctor_set(x_11, 1, x_4);
            {
                lungo_obj t_0 = x_1;
                lungo_obj t_1 = x_11;
                lungo_obj t_2 = x_5;
                x_1 = t_0;
                x_2 = t_1;
                x_3 = t_2;
                goto _start;
            }
        }
    }
}

/* Lean: Std.Format.joinSep._at_.Lean.Syntax.formatStxAux.spec_2 */
/* Compiled from: Std.Format.joinSep */
/* Source: <lean>/Init/Data/Format/Basic.lean:443:1 */
lungo_obj tagged_urn_formal__l_Std_dFormat_djoinSep_d__at___dLean_dSyntax_dformatStxAux_dspec__2(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec(x_2);
            x_3 = lungo_box(0);
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_1, 1);
            switch (lungo_obj_tag(x_4)) {
                case 0: {
                    lungo_dec(x_2);
                    x_5 = lungo_ctor_get(x_1, 0);
                    lungo_inc(x_5);
                    lungo_dec_ref(x_1);
                    return x_5;
                }
                default: {
                    lungo_inc(x_4);
                    x_6 = lungo_ctor_get(x_1, 0);
                    lungo_inc(x_6);
                    lungo_dec_ref(x_1);
                    x_7 = tagged_urn_formal__l_List_dfoldl_d__at___dStd_dFormat_djoinSep_d__at___dLean_dSyntax_dformatStxAux_dspec__2_dspec__2(x_2, x_6, x_4);
                    return x_7;
                }
            }
        }
    }
}

