/* Generated by lungo 1.156.5900 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.System.IO. */
#include "tagged_urn_formal_program.h"

/* Lean: IO.FS.Handle.flush */
/* Source: <lean>/Init/System/IO.lean:822:1 */
lungo_obj tagged_urn_formal__l_IO_dFS_dHandle_dflush(lungo_obj x_1) {
    lungo_obj r = lungo_lean_io_prim_handle_flush(x_1);
    return r;
}

/* Lean: IO.FS.Handle.flush._boxed */
/* Compiled from: IO.FS.Handle.flush */
/* Source: <lean>/Init/System/IO.lean:822:1 */
lungo_obj tagged_urn_formal__l_IO_dFS_dHandle_dflush_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    (void)x_2;
    lungo_obj x_3;
    x_3 = tagged_urn_formal__l_IO_dFS_dHandle_dflush(x_1);
    lungo_dec(x_1);
    return x_3;
}

/* Lean: IO.FS.Handle.getLine */
/* Source: <lean>/Init/System/IO.lean:856:1 */
lungo_obj tagged_urn_formal__l_IO_dFS_dHandle_dgetLine(lungo_obj x_1) {
    lungo_obj r = lungo_lean_io_prim_handle_get_line(x_1);
    return r;
}

/* Lean: IO.FS.Handle.getLine._boxed */
/* Compiled from: IO.FS.Handle.getLine */
/* Source: <lean>/Init/System/IO.lean:856:1 */
lungo_obj tagged_urn_formal__l_IO_dFS_dHandle_dgetLine_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    (void)x_2;
    lungo_obj x_3;
    x_3 = tagged_urn_formal__l_IO_dFS_dHandle_dgetLine(x_1);
    lungo_dec(x_1);
    return x_3;
}

/* Lean: IO.FS.Handle.isTty */
/* Source: <lean>/Init/System/IO.lean:817:1 */
uint8_t tagged_urn_formal__l_IO_dFS_dHandle_disTty(lungo_obj x_1) {
    uint8_t r = lungo_lean_io_prim_handle_is_tty(x_1);
    return r;
}

/* Lean: IO.FS.Handle.isTty._boxed */
/* Compiled from: IO.FS.Handle.isTty */
/* Source: <lean>/Init/System/IO.lean:817:1 */
lungo_obj tagged_urn_formal__l_IO_dFS_dHandle_disTty_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    (void)x_2;
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_IO_dFS_dHandle_disTty(x_1);
    lungo_dec(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: IO.FS.Handle.putStr */
/* Source: <lean>/Init/System/IO.lean:863:1 */
lungo_obj tagged_urn_formal__l_IO_dFS_dHandle_dputStr(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj r = lungo_lean_io_prim_handle_put_str(x_1, x_2);
    return r;
}

/* Lean: IO.FS.Handle.putStr._boxed */
/* Compiled from: IO.FS.Handle.putStr */
/* Source: <lean>/Init/System/IO.lean:863:1 */
lungo_obj tagged_urn_formal__l_IO_dFS_dHandle_dputStr_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    (void)x_3;
    lungo_obj x_4;
    x_4 = tagged_urn_formal__l_IO_dFS_dHandle_dputStr(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec(x_1);
    return x_4;
}

/* Lean: IO.FS.Handle.read */
/* Source: <lean>/Init/System/IO.lean:841:1 */
lungo_obj tagged_urn_formal__l_IO_dFS_dHandle_dread(lungo_obj x_1, size_t x_2) {
    lungo_obj r = lungo_lean_io_prim_handle_read(x_1, x_2);
    return r;
}

/* Lean: IO.FS.Handle.read._boxed */
/* Compiled from: IO.FS.Handle.read */
/* Source: <lean>/Init/System/IO.lean:841:1 */
lungo_obj tagged_urn_formal__l_IO_dFS_dHandle_dread_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    (void)x_3;
    size_t x_4;
    lungo_obj x_5;
    x_4 = lungo_unbox_usize(x_2);
    lungo_dec(x_2);
    x_5 = tagged_urn_formal__l_IO_dFS_dHandle_dread(x_1, x_4);
    lungo_dec(x_1);
    return x_5;
}

/* Lean: IO.FS.Handle.write */
/* Source: <lean>/Init/System/IO.lean:848:1 */
lungo_obj tagged_urn_formal__l_IO_dFS_dHandle_dwrite(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj r = lungo_lean_io_prim_handle_write(x_1, x_2);
    return r;
}

/* Lean: IO.FS.Handle.write._boxed */
/* Compiled from: IO.FS.Handle.write */
/* Source: <lean>/Init/System/IO.lean:848:1 */
lungo_obj tagged_urn_formal__l_IO_dFS_dHandle_dwrite_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    (void)x_3;
    lungo_obj x_4;
    x_4 = tagged_urn_formal__l_IO_dFS_dHandle_dwrite(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec(x_1);
    return x_4;
}

/* Lean: IO.FS.Stream.ofHandle */
/* Source: <lean>/Init/System/IO.lean:1678:1 */
lungo_obj tagged_urn_formal__l_IO_dFS_dStream_dofHandle(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_inc_n(x_1, 5);
    x_2 = lungo_alloc_closure((void *)tagged_urn_formal__l_IO_dFS_dHandle_dflush_d__boxed, 2, 1);
    lungo_closure_set(x_2, 0, x_1);
    x_3 = lungo_alloc_closure((void *)tagged_urn_formal__l_IO_dFS_dHandle_dread_d__boxed, 3, 1);
    lungo_closure_set(x_3, 0, x_1);
    x_4 = lungo_alloc_closure((void *)tagged_urn_formal__l_IO_dFS_dHandle_dwrite_d__boxed, 3, 1);
    lungo_closure_set(x_4, 0, x_1);
    x_5 = lungo_alloc_closure((void *)tagged_urn_formal__l_IO_dFS_dHandle_dgetLine_d__boxed, 2, 1);
    lungo_closure_set(x_5, 0, x_1);
    x_6 = lungo_alloc_closure((void *)tagged_urn_formal__l_IO_dFS_dHandle_dputStr_d__boxed, 3, 1);
    lungo_closure_set(x_6, 0, x_1);
    x_7 = lungo_alloc_closure((void *)tagged_urn_formal__l_IO_dFS_dHandle_disTty_d__boxed, 2, 1);
    lungo_closure_set(x_7, 0, x_1);
    x_8 = lungo_alloc_ctor(0, 6, 0);
    lungo_ctor_set(x_8, 0, x_2);
    lungo_ctor_set(x_8, 1, x_3);
    lungo_ctor_set(x_8, 2, x_4);
    lungo_ctor_set(x_8, 3, x_5);
    lungo_ctor_set(x_8, 4, x_6);
    lungo_ctor_set(x_8, 5, x_7);
    return x_8;
}

/* Lean: IO.eprint._at_._private.Init.System.IO.0.IO.eprintAux.spec_0 */
/* Compiled from: IO.eprint */
/* Source: <lean>/Init/System/IO.lean:1279:1 */
lungo_obj tagged_urn_formal__l_IO_deprint_d__at___d__private_dInit_dSystem_dIO_d0_dIO_deprintAux_dspec__0(lungo_obj x_1) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    x_3 = tagged_urn_formal__l_IO_dgetStderr();
    x_4 = lungo_ctor_get(x_3, 4);
    lungo_inc_ref(x_4);
    lungo_dec_ref(x_3);
    x_5 = lungo_apply_2(x_4, x_1, lungo_box(0));
    return x_5;
}

/* Lean: IO.eprintln._at_._private.Init.System.IO.0.IO.eprintlnAux.spec_0 */
/* Compiled from: IO.eprintln */
/* Source: <lean>/Init/System/IO.lean:1287:1 */
lungo_obj tagged_urn_formal__l_IO_deprintln_d__at___d__private_dInit_dSystem_dIO_d0_dIO_deprintlnAux_dspec__0(lungo_obj x_1) {
    uint32_t x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    x_3 = (uint32_t)10u;
    x_4 = tagged_urn_formal__l_String_dpush(x_1, x_3);
    x_5 = tagged_urn_formal__l_IO_deprint_d__at___d__private_dInit_dSystem_dIO_d0_dIO_deprintAux_dspec__0(x_4);
    return x_5;
}

/* Lean: IO.getRandomBytes */
/* Source: <lean>/Init/System/IO.lean:423:1 */
lungo_obj tagged_urn_formal__l_IO_dgetRandomBytes(size_t x_1) {
    lungo_obj r = lungo_lean_io_get_random_bytes(x_1);
    return r;
}

/* Lean: IO.getStderr */
/* Source: <lean>/Init/System/IO.lean:749:1 */
lungo_obj tagged_urn_formal__l_IO_dgetStderr(void) {
    lungo_obj r = lungo_lean_get_stderr();
    return r;
}

/* Lean: _private.Init.System.IO.0.IO.eprintlnAux */
/* Source: <lean>/Init/System/IO.lean:1298:1 */
lungo_obj tagged_urn_formal__l___private_dInit_dSystem_dIO_d0_dIO_deprintlnAux(lungo_obj x_1) {
    lungo_obj x_3;
    x_3 = tagged_urn_formal__l_IO_deprintln_d__at___d__private_dInit_dSystem_dIO_d0_dIO_deprintlnAux_dspec__0(x_1);
    return x_3;
}

