/* Generated by lungo 1.83.79 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.List.Basic. */
#include "tagged_urn_formal_program.h"

/* Lean: List.appendTR._redArg */
/* Compiled from: List.appendTR */
/* Source: <lean>/Init/Data/List/Basic.lean:588:1 */
lungo_obj tagged_urn_formal__l_List_dappendTR_d__redArg(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_List_dreverse_d__redArg(x_1);
    x_4 = tagged_urn_formal__l_List_dreverseAux_d__redArg(x_3, x_2);
    return x_4;
}

/* Lean: List.decidableBAll._redArg */
/* Compiled from: List.decidableBAll */
/* Source: <lean>/Init/Data/List/Basic.lean:886:1 */
uint8_t tagged_urn_formal__l_List_ddecidableBAll_d__redArg(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    uint8_t x_8;
    _start:
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec_ref(x_1);
            x_3 = (uint8_t)1u;
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_2, 0);
            lungo_inc(x_4);
            x_5 = lungo_ctor_get(x_2, 1);
            lungo_inc(x_5);
            lungo_dec_ref(x_2);
            lungo_inc_ref(x_1);
            x_6 = lungo_apply_1(x_1, x_4);
            x_7 = (uint8_t)lungo_unbox(x_6);
            switch (x_7) {
                case 0: {
                    lungo_dec(x_5);
                    lungo_dec_ref(x_1);
                    x_8 = (uint8_t)lungo_unbox(x_6);
                    return x_8;
                }
                default: {
                    {
                        lungo_obj t_0 = x_1;
                        lungo_obj t_1 = x_5;
                        x_1 = t_0;
                        x_2 = t_1;
                        goto _start;
                    }
                }
            }
        }
    }
}

/* Lean: List.instDecidablePairwise._redArg */
/* Compiled from: List.instDecidablePairwise */
/* Source: <lean>/Init/Data/List/Basic.lean:1389:1 */
uint8_t tagged_urn_formal__l_List_dinstDecidablePairwise_d__redArg(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    uint8_t x_8;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec_ref(x_1);
            x_3 = (uint8_t)1u;
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_2, 0);
            lungo_inc(x_4);
            x_5 = lungo_ctor_get(x_2, 1);
            lungo_inc_n(x_5, 2);
            lungo_dec_ref(x_2);
            lungo_inc_ref(x_1);
            x_6 = tagged_urn_formal__l_List_dinstDecidablePairwise_d__redArg(x_1, x_5);
            switch (x_6) {
                case 0: {
                    lungo_dec(x_5);
                    lungo_dec(x_4);
                    lungo_dec_ref(x_1);
                    return x_6;
                }
                default: {
                    x_7 = lungo_apply_1(x_1, x_4);
                    x_8 = tagged_urn_formal__l_List_ddecidableBAll_d__redArg(x_7, x_5);
                    return x_8;
                }
            }
        }
    }
}

/* Lean: List.range */
/* Source: <lean>/Init/Data/List/Basic.lean:2092:1 */
lungo_obj tagged_urn_formal__l_List_drange(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    x_2 = lungo_box(0);
    x_3 = tagged_urn_formal__l_List_drange_dloop(x_1, x_2);
    return x_3;
}

/* Lean: List.range.loop */
/* Source: <lean>/Init/Data/List/Basic.lean:2105:3 */
lungo_obj tagged_urn_formal__l_List_drange_dloop(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    uint8_t x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    _start:
    x_3 = lungo_usize_to_nat(0u);
    x_4 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_3);
    switch (x_4) {
        case 1: {
            lungo_dec(x_1);
            return x_2;
        }
        default: {
            x_5 = lungo_usize_to_nat(1u);
            x_6 = tagged_urn_formal__l_Nat_dsub(x_1, x_5);
            lungo_dec(x_1);
            lungo_inc(x_6);
            x_7 = lungo_alloc_ctor(1, 2, 0);
            lungo_ctor_set(x_7, 0, x_6);
            lungo_ctor_set(x_7, 1, x_2);
            {
                lungo_obj t_0 = x_6;
                lungo_obj t_1 = x_7;
                x_1 = t_0;
                x_2 = t_1;
                goto _start;
            }
        }
    }
}

/* Lean: List.reverse._redArg */
/* Compiled from: List.reverse */
/* Source: <lean>/Init/Data/List/Basic.lean:562:1 */
lungo_obj tagged_urn_formal__l_List_dreverse_d__redArg(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    x_2 = lungo_box(0);
    x_3 = tagged_urn_formal__l_List_dreverseAux_d__redArg(x_1, x_2);
    return x_3;
}

/* Lean: List.reverseAux._redArg */
/* Compiled from: List.reverseAux */
/* Source: <lean>/Init/Data/List/Basic.lean:554:1 */
lungo_obj tagged_urn_formal__l_List_dreverseAux_d__redArg(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_9;
    lungo_obj x_11;
    uint8_t x_12;
    _start:
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            return x_2;
        }
        default: {
            x_3 = lungo_ctor_get(x_1, 0);
            x_4 = lungo_ctor_get(x_1, 1);
            x_12 = !lungo_is_exclusive(x_1);
            switch (x_12) {
                case 0: {
                    x_6 = x_1;
                    x_7 = x_12;
                    goto block_5;
                }
                default: {
                    lungo_inc(x_4);
                    lungo_inc(x_3);
                    lungo_dec(x_1);
                    x_6 = lungo_box(0);
                    x_7 = x_12;
                    goto block_5;
                }
            }
            block_5:;
            switch (x_7) {
                case 0: {
                    lungo_ctor_set(x_6, 1, x_2);
                    x_9 = x_6;
                    goto block_8;
                }
                default: {
                    x_11 = lungo_alloc_ctor(1, 2, 0);
                    lungo_ctor_set(x_11, 0, x_3);
                    lungo_ctor_set(x_11, 1, x_2);
                    x_9 = x_11;
                    goto block_8;
                }
            }
            block_8:;
            {
                lungo_obj t_0 = x_4;
                lungo_obj t_1 = x_9;
                x_1 = t_0;
                x_2 = t_1;
                goto _start;
            }
        }
    }
}

