/* Generated by lungo 1.78.3254 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.String.Modify. */
#include "tagged_urn_formal_program.h"

/* Lean: String.Pos.Raw.set */
/* Source: <lean>/Init/Data/String/Modify.lean:143:1 */
lungo_obj tagged_urn_formal__l_String_dPos_dRaw_dset(lungo_obj x_1, lungo_obj x_2, uint32_t x_3) {
    lungo_obj r = lungo_lean_string_utf8_set(x_1, x_2, x_3);
    return r;
}

