/* Generated by lungo 1.84.11 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.UInt.BasicAux. */
#include "tagged_urn_formal_program.h"

/* Lean: UInt32.add */
/* Source: <lean>/Init/Data/UInt/BasicAux.lean:225:1 */
uint32_t tagged_urn_formal__l_UInt32_dadd(uint32_t x_1, uint32_t x_2) {
    uint32_t r = lungo_lean_uint32_add(x_1, x_2);
    return r;
}

/* Lean: UInt64.toNat */
/* Source: <lean>/Init/Data/UInt/BasicAux.lean:289:1 */
lungo_obj tagged_urn_formal__l_UInt64_dtoNat(uint64_t x_1) {
    lungo_obj r = lungo_lean_uint64_to_nat(x_1);
    return r;
}

/* Lean: UInt8.toUInt64 */
/* Source: <lean>/Init/Data/UInt/BasicAux.lean:317:1 */
uint64_t tagged_urn_formal__l_UInt8_dtoUInt64(uint8_t x_1) {
    uint64_t r = lungo_lean_uint8_to_uint64(x_1);
    return r;
}

/* Lean: USize.ofNat */
/* Source: <lean>/Init/Data/UInt/BasicAux.lean:344:1 */
size_t tagged_urn_formal__l_USize_dofNat(lungo_obj x_1) {
    size_t r = lungo_lean_usize_of_nat(x_1);
    return r;
}

