/* Generated by lungo 1.67.2841 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.ByteArray.Extra. */
#include "tagged_urn_formal_program.h"

/* Lean: ByteArray.toUInt64LE! */
/* Source: <lean>/Init/Data/ByteArray/Extra.lean:15:1 */
uint64_t tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21_(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    uint8_t x_4;
    lungo_obj x_5;
    uint64_t x_6;
    lungo_obj x_7;
    uint8_t x_8;
    uint64_t x_9;
    uint64_t x_10;
    uint64_t x_11;
    lungo_obj x_12;
    uint8_t x_13;
    uint64_t x_14;
    uint64_t x_15;
    uint64_t x_16;
    uint64_t x_17;
    lungo_obj x_18;
    uint8_t x_19;
    uint64_t x_20;
    uint64_t x_21;
    uint64_t x_22;
    uint64_t x_23;
    lungo_obj x_24;
    uint8_t x_25;
    uint64_t x_26;
    uint64_t x_27;
    uint64_t x_28;
    uint64_t x_29;
    lungo_obj x_30;
    uint8_t x_31;
    uint64_t x_32;
    uint64_t x_33;
    uint64_t x_34;
    uint64_t x_35;
    lungo_obj x_36;
    uint8_t x_37;
    uint64_t x_38;
    uint64_t x_39;
    uint64_t x_40;
    uint64_t x_41;
    lungo_obj x_42;
    uint8_t x_43;
    uint64_t x_44;
    uint64_t x_45;
    uint64_t x_46;
    uint64_t x_47;
    lungo_obj x_48;
    uint8_t x_49;
    uint64_t x_50;
    uint64_t x_51;
    x_2 = tagged_urn_formal__l_ByteArray_dsize(x_1);
    x_3 = lungo_usize_to_nat(8u);
    x_4 = tagged_urn_formal__l_Nat_ddecEq(x_2, x_3);
    switch (x_4) {
        case 0: {
            x_5 = tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__3();
            x_6 = tagged_urn_formal__l_panic_d__at___dByteArray_dtoUInt64LE_x21__dspec__0(x_5);
            return x_6;
        }
        default: {
            x_7 = lungo_usize_to_nat(7u);
            x_8 = tagged_urn_formal__l_ByteArray_dget_x21_(x_1, x_7);
            x_9 = tagged_urn_formal__l_UInt8_dtoUInt64(x_8);
            x_10 = (uint64_t)UINT64_C(56);
            x_11 = tagged_urn_formal__l_UInt64_dshiftLeft(x_9, x_10);
            x_12 = lungo_usize_to_nat(6u);
            x_13 = tagged_urn_formal__l_ByteArray_dget_x21_(x_1, x_12);
            x_14 = tagged_urn_formal__l_UInt8_dtoUInt64(x_13);
            x_15 = (uint64_t)UINT64_C(48);
            x_16 = tagged_urn_formal__l_UInt64_dshiftLeft(x_14, x_15);
            x_17 = tagged_urn_formal__l_UInt64_dlor(x_11, x_16);
            x_18 = lungo_usize_to_nat(5u);
            x_19 = tagged_urn_formal__l_ByteArray_dget_x21_(x_1, x_18);
            x_20 = tagged_urn_formal__l_UInt8_dtoUInt64(x_19);
            x_21 = (uint64_t)UINT64_C(40);
            x_22 = tagged_urn_formal__l_UInt64_dshiftLeft(x_20, x_21);
            x_23 = tagged_urn_formal__l_UInt64_dlor(x_17, x_22);
            x_24 = lungo_usize_to_nat(4u);
            x_25 = tagged_urn_formal__l_ByteArray_dget_x21_(x_1, x_24);
            x_26 = tagged_urn_formal__l_UInt8_dtoUInt64(x_25);
            x_27 = (uint64_t)UINT64_C(32);
            x_28 = tagged_urn_formal__l_UInt64_dshiftLeft(x_26, x_27);
            x_29 = tagged_urn_formal__l_UInt64_dlor(x_23, x_28);
            x_30 = lungo_usize_to_nat(3u);
            x_31 = tagged_urn_formal__l_ByteArray_dget_x21_(x_1, x_30);
            x_32 = tagged_urn_formal__l_UInt8_dtoUInt64(x_31);
            x_33 = (uint64_t)UINT64_C(24);
            x_34 = tagged_urn_formal__l_UInt64_dshiftLeft(x_32, x_33);
            x_35 = tagged_urn_formal__l_UInt64_dlor(x_29, x_34);
            x_36 = lungo_usize_to_nat(2u);
            x_37 = tagged_urn_formal__l_ByteArray_dget_x21_(x_1, x_36);
            x_38 = tagged_urn_formal__l_UInt8_dtoUInt64(x_37);
            x_39 = (uint64_t)UINT64_C(16);
            x_40 = tagged_urn_formal__l_UInt64_dshiftLeft(x_38, x_39);
            x_41 = tagged_urn_formal__l_UInt64_dlor(x_35, x_40);
            x_42 = lungo_usize_to_nat(1u);
            x_43 = tagged_urn_formal__l_ByteArray_dget_x21_(x_1, x_42);
            x_44 = tagged_urn_formal__l_UInt8_dtoUInt64(x_43);
            x_45 = (uint64_t)UINT64_C(8);
            x_46 = tagged_urn_formal__l_UInt64_dshiftLeft(x_44, x_45);
            x_47 = tagged_urn_formal__l_UInt64_dlor(x_41, x_46);
            x_48 = lungo_usize_to_nat(0u);
            x_49 = tagged_urn_formal__l_ByteArray_dget_x21_(x_1, x_48);
            x_50 = tagged_urn_formal__l_UInt8_dtoUInt64(x_49);
            x_51 = tagged_urn_formal__l_UInt64_dlor(x_47, x_50);
            return x_51;
        }
    }
}

/* Lean: ByteArray.toUInt64LE!._closed_0 */
/* Compiled from: ByteArray.toUInt64LE! */
/* Source: <lean>/Init/Data/ByteArray/Extra.lean:15:1 */
static lungo_obj tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"Init.Data.ByteArray.Extra", 25, 25);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__0__cell;
lungo_obj tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__0__cell, tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__0__init);
}

/* Lean: ByteArray.toUInt64LE!._closed_1 */
/* Compiled from: ByteArray.toUInt64LE! */
/* Source: <lean>/Init/Data/ByteArray/Extra.lean:15:1 */
static lungo_obj tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__1__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"ByteArray.toUInt64LE!", 21, 21);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__1__cell;
lungo_obj tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__1__cell, tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__1__init);
}

/* Lean: ByteArray.toUInt64LE!._closed_2 */
/* Compiled from: ByteArray.toUInt64LE! */
/* Source: <lean>/Init/Data/ByteArray/Extra.lean:15:1 */
static lungo_obj tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__2__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"assertion violation: bs.size == 8\012  ", 36, 36);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__2__cell;
lungo_obj tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__2(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__2__cell, tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__2__init);
}

/* Lean: ByteArray.toUInt64LE!._closed_3 */
/* Compiled from: ByteArray.toUInt64LE! */
/* Source: <lean>/Init/Data/ByteArray/Extra.lean:15:1 */
static lungo_obj tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__3__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    x_1 = tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__2();
    x_2 = lungo_usize_to_nat(2u);
    x_3 = lungo_usize_to_nat(21u);
    x_4 = tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__1();
    x_5 = tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__0();
    x_6 = tagged_urn_formal__l_mkPanicMessageWithDecl(x_5, x_4, x_3, x_2, x_1);
    return x_6;
}
static lungo_lazy_obj tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__3__cell;
lungo_obj tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__3(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__3__cell, tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21__d__closed__3__init);
}

/* Lean: panic._at_.ByteArray.toUInt64LE!.spec_0 */
/* Compiled from: panic */
/* Source: <lean>/Init/Prelude.lean:3710:1 */
uint64_t tagged_urn_formal__l_panic_d__at___dByteArray_dtoUInt64LE_x21__dspec__0(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    uint64_t x_4;
    x_2 = tagged_urn_formal__l_panic_d__at___dByteArray_dtoUInt64LE_x21__dspec__0_d__boxed__const__1();
    x_3 = tagged_urn_formal__l_panicCore(lungo_box(0), x_2, x_1);
    x_4 = lungo_unbox_uint64(x_3);
    lungo_dec(x_3);
    return x_4;
}

/* Lean: panic._at_.ByteArray.toUInt64LE!.spec_0._boxed_const_1 */
/* Compiled from: panic */
/* Source: <lean>/Init/Prelude.lean:3710:1 */
static lungo_obj tagged_urn_formal__l_panic_d__at___dByteArray_dtoUInt64LE_x21__dspec__0_d__boxed__const__1__init(void) {
    uint64_t x_1;
    lungo_obj x_2;
    x_1 = (uint64_t)UINT64_C(0);
    x_2 = lungo_box_uint64(x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_panic_d__at___dByteArray_dtoUInt64LE_x21__dspec__0_d__boxed__const__1__cell;
lungo_obj tagged_urn_formal__l_panic_d__at___dByteArray_dtoUInt64LE_x21__dspec__0_d__boxed__const__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_panic_d__at___dByteArray_dtoUInt64LE_x21__dspec__0_d__boxed__const__1__cell, tagged_urn_formal__l_panic_d__at___dByteArray_dtoUInt64LE_x21__dspec__0_d__boxed__const__1__init);
}

