/* Generated by lungo 1.82.64 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.String.Iterate. */
#include "tagged_urn_formal_program.h"

/* Lean: String.Internal.foldlImpl */
/* Source: <lean>/Init/Data/String/Iterate.lean:474:1 */
lungo_obj tagged_urn_formal__l_String_dInternal_dfoldlImpl(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    x_4 = lungo_usize_to_nat(0u);
    x_5 = tagged_urn_formal__l_String_dutf8ByteSize(x_3);
    lungo_inc_ref(x_3);
    x_6 = lungo_alloc_ctor(0, 3, 0);
    lungo_ctor_set(x_6, 0, x_3);
    lungo_ctor_set(x_6, 1, x_4);
    lungo_ctor_set(x_6, 2, x_5);
    x_7 = tagged_urn_formal__l_WellFounded_dopaqueFix_x2083__d__at___dString_dInternal_dfoldlImpl_dspec__0_d__redArg(x_1, x_6, x_3, x_4, x_2);
    lungo_dec_ref(x_3);
    lungo_dec_ref(x_6);
    return x_7;
}

/* Lean: WellFounded.opaqueFix₃._at_.String.Internal.foldlImpl.spec_0._redArg */
/* Compiled from: WellFounded.opaqueFix₃ */
/* Source: <lean>/Init/WFExtrinsicFix.lean:190:1 */
lungo_obj tagged_urn_formal__l_WellFounded_dopaqueFix_x2083__d__at___dString_dInternal_dfoldlImpl_dspec__0_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5) {
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    uint8_t x_9;
    uint32_t x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    _start:
    x_6 = lungo_ctor_get(x_2, 1);
    x_7 = lungo_ctor_get(x_2, 2);
    x_8 = tagged_urn_formal__l_Nat_dsub(x_7, x_6);
    x_9 = tagged_urn_formal__l_Nat_ddecEq(x_4, x_8);
    lungo_dec(x_8);
    switch (x_9) {
        case 0: {
            x_10 = tagged_urn_formal__l_String_ddecodeChar(x_3, x_4, lungo_box(0));
            x_11 = tagged_urn_formal__l_String_dPos_dnext(x_3, x_4, lungo_box(0));
            lungo_dec(x_4);
            x_12 = lungo_box_uint32(x_10);
            lungo_inc_ref(x_1);
            x_13 = lungo_apply_2(x_1, x_5, x_12);
            {
                lungo_obj t_0 = x_1;
                lungo_obj t_1 = x_2;
                lungo_obj t_2 = x_3;
                lungo_obj t_3 = x_11;
                lungo_obj t_4 = x_13;
                x_1 = t_0;
                x_2 = t_1;
                x_3 = t_2;
                x_4 = t_3;
                x_5 = t_4;
                goto _start;
            }
        }
        default: {
            lungo_dec(x_4);
            lungo_dec_ref(x_1);
            return x_5;
        }
    }
}

