/* Generated by lungo 1.72.2908 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Core. */
#include "tagged_urn_formal_program.h"

/* Lean: instDecidableEqProd._redArg */
/* Compiled from: instDecidableEqProd */
/* Source: <lean>/Init/Core.lean:1456:1 */
uint8_t tagged_urn_formal__l_instDecidableEqProd_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    uint8_t x_10;
    uint8_t x_11;
    lungo_obj x_12;
    uint8_t x_13;
    x_5 = lungo_ctor_get(x_3, 0);
    lungo_inc(x_5);
    x_6 = lungo_ctor_get(x_3, 1);
    lungo_inc(x_6);
    lungo_dec_ref(x_3);
    x_7 = lungo_ctor_get(x_4, 0);
    lungo_inc(x_7);
    x_8 = lungo_ctor_get(x_4, 1);
    lungo_inc(x_8);
    lungo_dec_ref(x_4);
    x_9 = lungo_apply_2(x_1, x_5, x_7);
    x_10 = (uint8_t)lungo_unbox(x_9);
    switch (x_10) {
        case 0: {
            lungo_dec(x_8);
            lungo_dec(x_6);
            lungo_dec_ref(x_2);
            x_11 = (uint8_t)lungo_unbox(x_9);
            return x_11;
        }
        default: {
            x_12 = lungo_apply_2(x_2, x_6, x_8);
            x_13 = (uint8_t)lungo_unbox(x_12);
            return x_13;
        }
    }
}

