/* Generated by lungo 1.84.11 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.Int.Repr. */
#include "tagged_urn_formal_program.h"

/* Lean: Int.repr */
/* Source: <lean>/Init/Data/Int/Repr.lean:14:1 */
lungo_obj tagged_urn_formal__l_Int_drepr(lungo_obj x_1) {
    lungo_obj x_2;
    uint8_t x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    x_2 = tagged_urn_formal__l_Int_drepr_d__closed__0();
    x_3 = tagged_urn_formal__l_Int_ddecLt(x_1, x_2);
    switch (x_3) {
        case 0: {
            x_4 = tagged_urn_formal__l_Int_dnatAbs(x_1);
            x_5 = tagged_urn_formal__l_Nat_dreprFast(x_4);
            return x_5;
        }
        default: {
            x_6 = tagged_urn_formal__l_Int_dnatAbs(x_1);
            x_7 = lungo_usize_to_nat(1u);
            x_8 = tagged_urn_formal__l_Nat_dsub(x_6, x_7);
            lungo_dec(x_6);
            x_9 = tagged_urn_formal__l_Int_drepr_d__closed__1();
            x_10 = tagged_urn_formal__l_Nat_dadd(x_8, x_7);
            lungo_dec(x_8);
            x_11 = tagged_urn_formal__l_Nat_dreprFast(x_10);
            x_12 = tagged_urn_formal__l_String_dappend(x_9, x_11);
            lungo_dec_ref(x_11);
            return x_12;
        }
    }
}

/* Lean: Int.repr._closed_0 */
/* Compiled from: Int.repr */
/* Source: <lean>/Init/Data/Int/Repr.lean:14:1 */
static lungo_obj tagged_urn_formal__l_Int_drepr_d__closed__0__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = lungo_usize_to_nat(0u);
    x_2 = tagged_urn_formal__l_Int_dofNat(x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_Int_drepr_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_Int_drepr_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Int_drepr_d__closed__0__cell, tagged_urn_formal__l_Int_drepr_d__closed__0__init);
}

/* Lean: Int.repr._closed_1 */
/* Compiled from: Int.repr */
/* Source: <lean>/Init/Data/Int/Repr.lean:14:1 */
static lungo_obj tagged_urn_formal__l_Int_drepr_d__closed__1__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"-", 1, 1);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_Int_drepr_d__closed__1__cell;
lungo_obj tagged_urn_formal__l_Int_drepr_d__closed__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Int_drepr_d__closed__1__cell, tagged_urn_formal__l_Int_drepr_d__closed__1__init);
}

