/* Generated by lungo 1.78.3254 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.Int.Basic. */
#include "tagged_urn_formal_program.h"

/* Lean: Int.decLt */
/* Source: <lean>/Init/Data/Int/Basic.lean:303:1 */
uint8_t tagged_urn_formal__l_Int_ddecLt(lungo_obj x_1, lungo_obj x_2) {
    uint8_t r = lungo_lean_int_dec_lt(x_1, x_2);
    return r;
}

/* Lean: Int.natAbs */
/* Source: <lean>/Init/Data/Int/Basic.lean:317:1 */
lungo_obj tagged_urn_formal__l_Int_dnatAbs(lungo_obj x_1) {
    lungo_obj r = lungo_lean_nat_abs(x_1);
    return r;
}

/* Lean: Int.ofNat */
/* Source: <lean>/Init/Data/Int/Basic.lean:47:3 */
lungo_obj tagged_urn_formal__l_Int_dofNat(lungo_obj x_1) {
    lungo_obj r = lungo_lean_nat_to_int(x_1);
    return r;
}

