/* Generated by lungo 1.76.3233 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.Random. */
#include "tagged_urn_formal_program.h"

/* Lean: IO.stdGenRef */
/* Source: <lean>/Init/Data/Random.lean:124:1 */
lungo_obj tagged_urn_formal__l_IO_dstdGenRef(void) {
    return lungo_init_obj_get(&tagged_urn_formal__I_l_IO_dstdGenRef);
}
lungo_init_obj tagged_urn_formal__I_l_IO_dstdGenRef = {0, 0, "IO.stdGenRef"};

/* Lean: _private.Init.Data.Random.0.initFn._@.Init.Data.Random.2456098205._hygCtx._hyg.2 */
/* Source: <lean>/Init/Data/Random.lean:124:1 */
lungo_obj tagged_urn_formal__l___private_dInit_dData_dRandom_d0_dinitFn_d___x40__dInit_dData_dRandom_d2456098205_d__hygCtx_d__hyg_d2(void) {
    size_t x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_6;
    uint8_t x_7;
    uint64_t x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_13;
    lungo_obj x_14;
    uint8_t x_15;
    lungo_obj x_16;
    lungo_obj x_18;
    uint8_t x_19;
    lungo_obj x_21;
    lungo_obj x_22;
    uint8_t x_23;
    x_2 = (size_t)UINT64_C(8);
    x_3 = tagged_urn_formal__l_IO_dgetRandomBytes(x_2);
    switch (lungo_obj_tag(x_3)) {
        case 0: {
            x_4 = lungo_ctor_get(x_3, 0);
            x_15 = !lungo_is_exclusive(x_3);
            switch (x_15) {
                case 0: {
                    x_6 = x_3;
                    x_7 = x_15;
                    goto block_5;
                }
                default: {
                    lungo_inc(x_4);
                    lungo_dec(x_3);
                    x_6 = lungo_box(0);
                    x_7 = x_15;
                    goto block_5;
                }
            }
            block_5:;
            x_8 = tagged_urn_formal__l_ByteArray_dtoUInt64LE_x21_(x_4);
            lungo_dec(x_4);
            x_9 = tagged_urn_formal__l_UInt64_dtoNat(x_8);
            x_10 = tagged_urn_formal__l_mkStdGen(x_9);
            lungo_dec(x_9);
            x_11 = tagged_urn_formal__l_ST_dPrim_dmkRef(lungo_box(0), lungo_box(0), x_10);
            switch (x_7) {
                case 0: {
                    lungo_ctor_set(x_6, 0, x_11);
                    x_13 = x_6;
                    goto block_12;
                }
                default: {
                    x_14 = lungo_alloc_ctor(0, 1, 0);
                    lungo_ctor_set(x_14, 0, x_11);
                    x_13 = x_14;
                    goto block_12;
                }
            }
            block_12:;
            return x_13;
        }
        default: {
            x_16 = lungo_ctor_get(x_3, 0);
            x_23 = !lungo_is_exclusive(x_3);
            switch (x_23) {
                case 0: {
                    x_18 = x_3;
                    x_19 = x_23;
                    goto block_17;
                }
                default: {
                    lungo_inc(x_16);
                    lungo_dec(x_3);
                    x_18 = lungo_box(0);
                    x_19 = x_23;
                    goto block_17;
                }
            }
            block_17:;
            switch (x_19) {
                case 0: {
                    x_21 = x_18;
                    goto block_20;
                }
                default: {
                    x_22 = lungo_alloc_ctor(1, 1, 0);
                    lungo_ctor_set(x_22, 0, x_16);
                    x_21 = x_22;
                    goto block_20;
                }
            }
            block_20:;
            return x_21;
        }
    }
}

/* Lean: mkStdGen */
/* Source: <lean>/Init/Data/Random.lean:40:1 */
lungo_obj tagged_urn_formal__l_mkStdGen(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    x_2 = lungo_usize_to_nat(2147483562u);
    x_3 = tagged_urn_formal__l_Nat_ddiv(x_1, x_2);
    x_4 = tagged_urn_formal__l_Nat_dmod(x_1, x_2);
    x_5 = lungo_usize_to_nat(2147483398u);
    x_6 = tagged_urn_formal__l_Nat_dmod(x_3, x_5);
    lungo_dec(x_3);
    x_7 = lungo_usize_to_nat(1u);
    x_8 = tagged_urn_formal__l_Nat_dadd(x_4, x_7);
    lungo_dec(x_4);
    x_9 = tagged_urn_formal__l_Nat_dadd(x_6, x_7);
    lungo_dec(x_6);
    x_10 = lungo_alloc_ctor(0, 2, 0);
    lungo_ctor_set(x_10, 0, x_8);
    lungo_ctor_set(x_10, 1, x_9);
    return x_10;
}

