/* Generated by lungo 1.84.11 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.UInt.Basic. */
#include "tagged_urn_formal_program.h"

/* Lean: UInt64.lor */
/* Source: <lean>/Init/Data/UInt/Basic.lean:647:1 */
uint64_t tagged_urn_formal__l_UInt64_dlor(uint64_t x_1, uint64_t x_2) {
    uint64_t r = lungo_lean_uint64_lor(x_1, x_2);
    return r;
}

/* Lean: UInt64.shiftLeft */
/* Source: <lean>/Init/Data/UInt/Basic.lean:667:1 */
uint64_t tagged_urn_formal__l_UInt64_dshiftLeft(uint64_t x_1, uint64_t x_2) {
    uint64_t r = lungo_lean_uint64_shift_left(x_1, x_2);
    return r;
}

