/* Generated by lungo 1.65.2807 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.Repr. */
#include "tagged_urn_formal_program.h"

/* Lean: Char.quoteCore */
/* Source: <lean>/Init/Data/Repr.lean:360:1 */
lungo_obj tagged_urn_formal__l_Char_dquoteCore(uint32_t x_1, uint8_t x_2) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_8;
    lungo_obj x_9;
    uint8_t x_10;
    uint32_t x_11;
    uint8_t x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    uint32_t x_15;
    uint8_t x_16;
    uint32_t x_17;
    uint8_t x_18;
    uint32_t x_19;
    uint8_t x_20;
    uint32_t x_21;
    uint8_t x_22;
    uint32_t x_23;
    uint8_t x_24;
    lungo_obj x_25;
    lungo_obj x_26;
    lungo_obj x_27;
    lungo_obj x_28;
    lungo_obj x_29;
    x_15 = (uint32_t)10u;
    x_16 = tagged_urn_formal__l_UInt32_ddecEq(x_1, x_15);
    switch (x_16) {
        case 0: {
            x_17 = (uint32_t)9u;
            x_18 = tagged_urn_formal__l_UInt32_ddecEq(x_1, x_17);
            switch (x_18) {
                case 0: {
                    x_19 = (uint32_t)92u;
                    x_20 = tagged_urn_formal__l_UInt32_ddecEq(x_1, x_19);
                    switch (x_20) {
                        case 0: {
                            x_21 = (uint32_t)34u;
                            x_22 = tagged_urn_formal__l_UInt32_ddecEq(x_1, x_21);
                            switch (x_22) {
                                case 0: {
                                    switch (x_2) {
                                        case 0: {
                                            x_23 = (uint32_t)39u;
                                            x_24 = tagged_urn_formal__l_UInt32_ddecEq(x_1, x_23);
                                            switch (x_24) {
                                                case 0: {
                                                    goto block_7;
                                                }
                                                default: {
                                                    x_25 = tagged_urn_formal__l_Char_dquoteCore_d__closed__1();
                                                    return x_25;
                                                }
                                            }
                                        }
                                        default: {
                                            goto block_7;
                                        }
                                    }
                                }
                                default: {
                                    x_26 = tagged_urn_formal__l_Char_dquoteCore_d__closed__2();
                                    return x_26;
                                }
                            }
                        }
                        default: {
                            x_27 = tagged_urn_formal__l_Char_dquoteCore_d__closed__3();
                            return x_27;
                        }
                    }
                }
                default: {
                    x_28 = tagged_urn_formal__l_Char_dquoteCore_d__closed__4();
                    return x_28;
                }
            }
        }
        default: {
            x_29 = tagged_urn_formal__l_Char_dquoteCore_d__closed__5();
            return x_29;
        }
    }
    block_7:;
    x_8 = tagged_urn_formal__l_UInt32_dtoNat(x_1);
    x_9 = lungo_usize_to_nat(31u);
    x_10 = tagged_urn_formal__l_Nat_ddecLe(x_8, x_9);
    lungo_dec(x_8);
    switch (x_10) {
        case 0: {
            x_11 = (uint32_t)127u;
            x_12 = tagged_urn_formal__l_UInt32_ddecEq(x_1, x_11);
            switch (x_12) {
                case 0: {
                    x_13 = tagged_urn_formal__l_hexDigitRepr_d__closed__0();
                    x_14 = tagged_urn_formal__l_String_dpush(x_13, x_1);
                    return x_14;
                }
                default: {
                    goto block_3;
                }
            }
        }
        default: {
            goto block_3;
        }
    }
    block_3:;
    x_4 = tagged_urn_formal__l_Char_dquoteCore_d__closed__0();
    x_5 = tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dChar_dquoteCore_dsmallCharToHex(x_1);
    x_6 = tagged_urn_formal__l_String_dInternal_dappend(x_4, x_5);
    lungo_dec_ref(x_5);
    return x_6;
}

/* Lean: Char.quoteCore._closed_0 */
/* Compiled from: Char.quoteCore */
/* Source: <lean>/Init/Data/Repr.lean:360:1 */
static lungo_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"\\x", 2, 2);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Char_dquoteCore_d__closed__0__cell, tagged_urn_formal__l_Char_dquoteCore_d__closed__0__init);
}

/* Lean: Char.quoteCore._closed_1 */
/* Compiled from: Char.quoteCore */
/* Source: <lean>/Init/Data/Repr.lean:360:1 */
static lungo_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__1__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"\\'", 2, 2);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__1__cell;
lungo_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Char_dquoteCore_d__closed__1__cell, tagged_urn_formal__l_Char_dquoteCore_d__closed__1__init);
}

/* Lean: Char.quoteCore._closed_2 */
/* Compiled from: Char.quoteCore */
/* Source: <lean>/Init/Data/Repr.lean:360:1 */
static lungo_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__2__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"\\\"", 2, 2);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__2__cell;
lungo_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__2(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Char_dquoteCore_d__closed__2__cell, tagged_urn_formal__l_Char_dquoteCore_d__closed__2__init);
}

/* Lean: Char.quoteCore._closed_3 */
/* Compiled from: Char.quoteCore */
/* Source: <lean>/Init/Data/Repr.lean:360:1 */
static lungo_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__3__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"\\\\", 2, 2);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__3__cell;
lungo_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__3(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Char_dquoteCore_d__closed__3__cell, tagged_urn_formal__l_Char_dquoteCore_d__closed__3__init);
}

/* Lean: Char.quoteCore._closed_4 */
/* Compiled from: Char.quoteCore */
/* Source: <lean>/Init/Data/Repr.lean:360:1 */
static lungo_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__4__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"\\t", 2, 2);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__4__cell;
lungo_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__4(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Char_dquoteCore_d__closed__4__cell, tagged_urn_formal__l_Char_dquoteCore_d__closed__4__init);
}

/* Lean: Char.quoteCore._closed_5 */
/* Compiled from: Char.quoteCore */
/* Source: <lean>/Init/Data/Repr.lean:360:1 */
static lungo_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__5__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"\\n", 2, 2);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__5__cell;
lungo_obj tagged_urn_formal__l_Char_dquoteCore_d__closed__5(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Char_dquoteCore_d__closed__5__cell, tagged_urn_formal__l_Char_dquoteCore_d__closed__5__init);
}

/* Lean: List.mapTR.loop._at_._private.Init.Data.Repr.0.Nat.reprArray.spec_0 */
/* Compiled from: List.mapTR.loop */
/* Source: <lean>/Init/Data/List/Basic.lean:2440:17 */
lungo_obj tagged_urn_formal__l_List_dmapTR_dloop_d__at___d__private_dInit_dData_dRepr_d0_dNat_dreprArray_dspec__0(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_7;
    uint8_t x_8;
    size_t x_9;
    lungo_obj x_10;
    lungo_obj x_12;
    lungo_obj x_14;
    uint8_t x_15;
    _start:
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_3 = tagged_urn_formal__l_List_dreverse_d__redArg(x_2);
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_1, 0);
            x_5 = lungo_ctor_get(x_1, 1);
            x_15 = !lungo_is_exclusive(x_1);
            switch (x_15) {
                case 0: {
                    x_7 = x_1;
                    x_8 = x_15;
                    goto block_6;
                }
                default: {
                    lungo_inc(x_5);
                    lungo_inc(x_4);
                    lungo_dec(x_1);
                    x_7 = lungo_box(0);
                    x_8 = x_15;
                    goto block_6;
                }
            }
            block_6:;
            x_9 = tagged_urn_formal__l_USize_dofNat(x_4);
            lungo_dec(x_4);
            x_10 = tagged_urn_formal__l_USize_drepr(x_9);
            switch (x_8) {
                case 0: {
                    lungo_ctor_set(x_7, 1, x_2);
                    lungo_ctor_set(x_7, 0, x_10);
                    x_12 = x_7;
                    goto block_11;
                }
                default: {
                    x_14 = lungo_alloc_ctor(1, 2, 0);
                    lungo_ctor_set(x_14, 0, x_10);
                    lungo_ctor_set(x_14, 1, x_2);
                    x_12 = x_14;
                    goto block_11;
                }
            }
            block_11:;
            {
                lungo_obj t_0 = x_5;
                lungo_obj t_1 = x_12;
                x_1 = t_0;
                x_2 = t_1;
                goto _start;
            }
        }
    }
}

/* Lean: Nat.digitChar */
/* Source: <lean>/Init/Data/Repr.lean:169:1 */
uint32_t tagged_urn_formal__l_Nat_ddigitChar(lungo_obj x_1) {
    lungo_obj x_2;
    uint8_t x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_8;
    uint8_t x_9;
    lungo_obj x_10;
    uint8_t x_11;
    lungo_obj x_12;
    uint8_t x_13;
    lungo_obj x_14;
    uint8_t x_15;
    lungo_obj x_16;
    uint8_t x_17;
    lungo_obj x_18;
    uint8_t x_19;
    lungo_obj x_20;
    uint8_t x_21;
    lungo_obj x_22;
    uint8_t x_23;
    lungo_obj x_24;
    uint8_t x_25;
    lungo_obj x_26;
    uint8_t x_27;
    lungo_obj x_28;
    uint8_t x_29;
    lungo_obj x_30;
    uint8_t x_31;
    lungo_obj x_32;
    uint8_t x_33;
    uint32_t x_34;
    uint32_t x_35;
    uint32_t x_36;
    uint32_t x_37;
    uint32_t x_38;
    uint32_t x_39;
    uint32_t x_40;
    uint32_t x_41;
    uint32_t x_42;
    uint32_t x_43;
    uint32_t x_44;
    uint32_t x_45;
    uint32_t x_46;
    uint32_t x_47;
    uint32_t x_48;
    uint32_t x_49;
    uint32_t x_50;
    x_2 = lungo_usize_to_nat(0u);
    x_3 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_2);
    switch (x_3) {
        case 0: {
            x_4 = lungo_usize_to_nat(1u);
            x_5 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_4);
            switch (x_5) {
                case 0: {
                    x_6 = lungo_usize_to_nat(2u);
                    x_7 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_6);
                    switch (x_7) {
                        case 0: {
                            x_8 = lungo_usize_to_nat(3u);
                            x_9 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_8);
                            switch (x_9) {
                                case 0: {
                                    x_10 = lungo_usize_to_nat(4u);
                                    x_11 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_10);
                                    switch (x_11) {
                                        case 0: {
                                            x_12 = lungo_usize_to_nat(5u);
                                            x_13 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_12);
                                            switch (x_13) {
                                                case 0: {
                                                    x_14 = lungo_usize_to_nat(6u);
                                                    x_15 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_14);
                                                    switch (x_15) {
                                                        case 0: {
                                                            x_16 = lungo_usize_to_nat(7u);
                                                            x_17 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_16);
                                                            switch (x_17) {
                                                                case 0: {
                                                                    x_18 = lungo_usize_to_nat(8u);
                                                                    x_19 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_18);
                                                                    switch (x_19) {
                                                                        case 0: {
                                                                            x_20 = lungo_usize_to_nat(9u);
                                                                            x_21 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_20);
                                                                            switch (x_21) {
                                                                                case 0: {
                                                                                    x_22 = lungo_usize_to_nat(10u);
                                                                                    x_23 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_22);
                                                                                    switch (x_23) {
                                                                                        case 0: {
                                                                                            x_24 = lungo_usize_to_nat(11u);
                                                                                            x_25 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_24);
                                                                                            switch (x_25) {
                                                                                                case 0: {
                                                                                                    x_26 = lungo_usize_to_nat(12u);
                                                                                                    x_27 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_26);
                                                                                                    switch (x_27) {
                                                                                                        case 0: {
                                                                                                            x_28 = lungo_usize_to_nat(13u);
                                                                                                            x_29 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_28);
                                                                                                            switch (x_29) {
                                                                                                                case 0: {
                                                                                                                    x_30 = lungo_usize_to_nat(14u);
                                                                                                                    x_31 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_30);
                                                                                                                    switch (x_31) {
                                                                                                                        case 0: {
                                                                                                                            x_32 = lungo_usize_to_nat(15u);
                                                                                                                            x_33 = tagged_urn_formal__l_Nat_ddecEq(x_1, x_32);
                                                                                                                            switch (x_33) {
                                                                                                                                case 0: {
                                                                                                                                    x_34 = (uint32_t)42u;
                                                                                                                                    return x_34;
                                                                                                                                }
                                                                                                                                default: {
                                                                                                                                    x_35 = (uint32_t)102u;
                                                                                                                                    return x_35;
                                                                                                                                }
                                                                                                                            }
                                                                                                                        }
                                                                                                                        default: {
                                                                                                                            x_36 = (uint32_t)101u;
                                                                                                                            return x_36;
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                                default: {
                                                                                                                    x_37 = (uint32_t)100u;
                                                                                                                    return x_37;
                                                                                                                }
                                                                                                            }
                                                                                                        }
                                                                                                        default: {
                                                                                                            x_38 = (uint32_t)99u;
                                                                                                            return x_38;
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                                default: {
                                                                                                    x_39 = (uint32_t)98u;
                                                                                                    return x_39;
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                        default: {
                                                                                            x_40 = (uint32_t)97u;
                                                                                            return x_40;
                                                                                        }
                                                                                    }
                                                                                }
                                                                                default: {
                                                                                    x_41 = (uint32_t)57u;
                                                                                    return x_41;
                                                                                }
                                                                            }
                                                                        }
                                                                        default: {
                                                                            x_42 = (uint32_t)56u;
                                                                            return x_42;
                                                                        }
                                                                    }
                                                                }
                                                                default: {
                                                                    x_43 = (uint32_t)55u;
                                                                    return x_43;
                                                                }
                                                            }
                                                        }
                                                        default: {
                                                            x_44 = (uint32_t)54u;
                                                            return x_44;
                                                        }
                                                    }
                                                }
                                                default: {
                                                    x_45 = (uint32_t)53u;
                                                    return x_45;
                                                }
                                            }
                                        }
                                        default: {
                                            x_46 = (uint32_t)52u;
                                            return x_46;
                                        }
                                    }
                                }
                                default: {
                                    x_47 = (uint32_t)51u;
                                    return x_47;
                                }
                            }
                        }
                        default: {
                            x_48 = (uint32_t)50u;
                            return x_48;
                        }
                    }
                }
                default: {
                    x_49 = (uint32_t)49u;
                    return x_49;
                }
            }
        }
        default: {
            x_50 = (uint32_t)48u;
            return x_50;
        }
    }
}

/* Lean: Nat.reprFast */
/* Source: <lean>/Init/Data/Repr.lean:238:1 */
lungo_obj tagged_urn_formal__l_Nat_dreprFast(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    uint8_t x_4;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    size_t x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    x_2 = tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray();
    x_3 = tagged_urn_formal__l_Nat_dreprFast_d__closed__0();
    x_4 = tagged_urn_formal__l_Nat_ddecLt(x_1, x_3);
    switch (x_4) {
        case 0: {
            x_5 = tagged_urn_formal__l_Nat_dreprFast_d__closed__1();
            x_6 = tagged_urn_formal__l_Nat_ddecLt(x_1, x_5);
            switch (x_6) {
                case 0: {
                    x_7 = lungo_usize_to_nat(10u);
                    x_8 = tagged_urn_formal__l_Nat_dtoDigits(x_7, x_1);
                    x_9 = tagged_urn_formal__l_String_dofList(x_8);
                    return x_9;
                }
                default: {
                    x_10 = tagged_urn_formal__l_USize_dofNatLT(x_1, lungo_box(0));
                    lungo_dec(x_1);
                    x_11 = tagged_urn_formal__l_USize_drepr(x_10);
                    return x_11;
                }
            }
        }
        default: {
            x_12 = tagged_urn_formal__l_Array_dgetInternalBorrowed(lungo_box(0), x_2, x_1, lungo_box(0));
            lungo_dec(x_1);
            lungo_inc(x_12);
            return x_12;
        }
    }
}

/* Lean: Nat.reprFast._closed_0 */
/* Compiled from: Nat.reprFast */
/* Source: <lean>/Init/Data/Repr.lean:238:1 */
static lungo_obj tagged_urn_formal__l_Nat_dreprFast_d__closed__0__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray();
    x_2 = tagged_urn_formal__l_Array_dsize(lungo_box(0), x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_Nat_dreprFast_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_Nat_dreprFast_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Nat_dreprFast_d__closed__0__cell, tagged_urn_formal__l_Nat_dreprFast_d__closed__0__init);
}

/* Lean: Nat.reprFast._closed_1 */
/* Compiled from: Nat.reprFast */
/* Source: <lean>/Init/Data/Repr.lean:238:1 */
static lungo_obj tagged_urn_formal__l_Nat_dreprFast_d__closed__1__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    x_1 = tagged_urn_formal__l_System_dPlatform_dnumBits();
    x_2 = lungo_usize_to_nat(2u);
    x_3 = tagged_urn_formal__l_Nat_dpow(x_2, x_1);
    return x_3;
}
static lungo_lazy_obj tagged_urn_formal__l_Nat_dreprFast_d__closed__1__cell;
lungo_obj tagged_urn_formal__l_Nat_dreprFast_d__closed__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Nat_dreprFast_d__closed__1__cell, tagged_urn_formal__l_Nat_dreprFast_d__closed__1__init);
}

/* Lean: Nat.toDigits */
/* Source: <lean>/Init/Data/Repr.lean:207:1 */
lungo_obj tagged_urn_formal__l_Nat_dtoDigits(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    x_3 = lungo_usize_to_nat(1u);
    x_4 = tagged_urn_formal__l_Nat_dadd(x_2, x_3);
    x_5 = lungo_box(0);
    x_6 = tagged_urn_formal__l_Nat_dtoDigitsCore(x_1, x_4, x_2, x_5);
    return x_6;
}

/* Lean: Nat.toDigitsCore */
/* Source: <lean>/Init/Data/Repr.lean:199:1 */
lungo_obj tagged_urn_formal__l_Nat_dtoDigitsCore(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    uint32_t x_8;
    lungo_obj x_9;
    uint8_t x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    lungo_obj x_16;
    lungo_obj x_17;
    _start:
    x_5 = lungo_usize_to_nat(0u);
    x_6 = tagged_urn_formal__l_Nat_ddecEq(x_2, x_5);
    switch (x_6) {
        case 1: {
            lungo_dec(x_3);
            lungo_dec(x_2);
            return x_4;
        }
        default: {
            x_7 = tagged_urn_formal__l_Nat_dmod(x_3, x_1);
            x_8 = tagged_urn_formal__l_Nat_ddigitChar(x_7);
            lungo_dec(x_7);
            x_9 = tagged_urn_formal__l_Nat_ddiv(x_3, x_1);
            lungo_dec(x_3);
            x_10 = tagged_urn_formal__l_Nat_ddecEq(x_9, x_5);
            switch (x_10) {
                case 0: {
                    x_11 = lungo_usize_to_nat(1u);
                    x_12 = tagged_urn_formal__l_Nat_dsub(x_2, x_11);
                    lungo_dec(x_2);
                    x_13 = lungo_box_uint32(x_8);
                    x_14 = lungo_alloc_ctor(1, 2, 0);
                    lungo_ctor_set(x_14, 0, x_13);
                    lungo_ctor_set(x_14, 1, x_4);
                    {
                        lungo_obj t_0 = x_1;
                        lungo_obj t_1 = x_12;
                        lungo_obj t_2 = x_9;
                        lungo_obj t_3 = x_14;
                        x_1 = t_0;
                        x_2 = t_1;
                        x_3 = t_2;
                        x_4 = t_3;
                        goto _start;
                    }
                }
                default: {
                    lungo_dec(x_9);
                    lungo_dec(x_2);
                    x_16 = lungo_box_uint32(x_8);
                    x_17 = lungo_alloc_ctor(1, 2, 0);
                    lungo_ctor_set(x_17, 0, x_16);
                    lungo_ctor_set(x_17, 1, x_4);
                    return x_17;
                }
            }
        }
    }
}

/* Lean: Repr.addAppParen */
/* Source: <lean>/Init/Data/Repr.lean:83:1 */
lungo_obj tagged_urn_formal__l_Repr_daddAppParen(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    uint8_t x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    uint8_t x_11;
    lungo_obj x_12;
    x_3 = lungo_usize_to_nat(1024u);
    x_4 = tagged_urn_formal__l_Nat_ddecLe(x_3, x_2);
    switch (x_4) {
        case 0: {
            return x_1;
        }
        default: {
            x_5 = tagged_urn_formal__l_Repr_daddAppParen_d__closed__3();
            x_6 = tagged_urn_formal__l_Repr_daddAppParen_d__closed__4();
            x_7 = lungo_alloc_ctor(5, 2, 0);
            lungo_ctor_set(x_7, 0, x_6);
            lungo_ctor_set(x_7, 1, x_1);
            x_8 = tagged_urn_formal__l_Repr_daddAppParen_d__closed__5();
            x_9 = lungo_alloc_ctor(5, 2, 0);
            lungo_ctor_set(x_9, 0, x_7);
            lungo_ctor_set(x_9, 1, x_8);
            x_10 = lungo_alloc_ctor(4, 2, 0);
            lungo_ctor_set(x_10, 0, x_5);
            lungo_ctor_set(x_10, 1, x_9);
            x_11 = (uint8_t)0u;
            x_12 = lungo_alloc_ctor(6, 1, 1);
            lungo_ctor_set(x_12, 0, x_10);
            lungo_ctor_set_uint8(x_12, 1 * sizeof(size_t), x_11);
            return x_12;
        }
    }
}

/* Lean: Repr.addAppParen._closed_0 */
/* Compiled from: Repr.addAppParen */
/* Source: <lean>/Init/Data/Repr.lean:83:1 */
static lungo_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"(", 1, 1);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Repr_daddAppParen_d__closed__0__cell, tagged_urn_formal__l_Repr_daddAppParen_d__closed__0__init);
}

/* Lean: Repr.addAppParen._closed_1 */
/* Compiled from: Repr.addAppParen */
/* Source: <lean>/Init/Data/Repr.lean:83:1 */
static lungo_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__1__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)")", 1, 1);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__1__cell;
lungo_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Repr_daddAppParen_d__closed__1__cell, tagged_urn_formal__l_Repr_daddAppParen_d__closed__1__init);
}

/* Lean: Repr.addAppParen._closed_2 */
/* Compiled from: Repr.addAppParen */
/* Source: <lean>/Init/Data/Repr.lean:83:1 */
static lungo_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__2__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_Repr_daddAppParen_d__closed__0();
    x_2 = tagged_urn_formal__l_String_dInternal_dlength(x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__2__cell;
lungo_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__2(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Repr_daddAppParen_d__closed__2__cell, tagged_urn_formal__l_Repr_daddAppParen_d__closed__2__init);
}

/* Lean: Repr.addAppParen._closed_3 */
/* Compiled from: Repr.addAppParen */
/* Source: <lean>/Init/Data/Repr.lean:83:1 */
static lungo_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__3__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_Repr_daddAppParen_d__closed__2();
    x_2 = tagged_urn_formal__l_Int_dofNat(x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__3__cell;
lungo_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__3(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Repr_daddAppParen_d__closed__3__cell, tagged_urn_formal__l_Repr_daddAppParen_d__closed__3__init);
}

/* Lean: Repr.addAppParen._closed_4 */
/* Compiled from: Repr.addAppParen */
/* Source: <lean>/Init/Data/Repr.lean:83:1 */
static lungo_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__4__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_Repr_daddAppParen_d__closed__0();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__4__cell;
lungo_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__4(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Repr_daddAppParen_d__closed__4__cell, tagged_urn_formal__l_Repr_daddAppParen_d__closed__4__init);
}

/* Lean: Repr.addAppParen._closed_5 */
/* Compiled from: Repr.addAppParen */
/* Source: <lean>/Init/Data/Repr.lean:83:1 */
static lungo_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__5__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_Repr_daddAppParen_d__closed__1();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__5__cell;
lungo_obj tagged_urn_formal__l_Repr_daddAppParen_d__closed__5(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Repr_daddAppParen_d__closed__5__cell, tagged_urn_formal__l_Repr_daddAppParen_d__closed__5__init);
}

/* Lean: String.quote */
/* Source: <lean>/Init/Data/Repr.lean:392:1 */
lungo_obj tagged_urn_formal__l_String_dquote(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_inc_ref(x_1);
    x_2 = tagged_urn_formal__l_String_dInternal_disEmpty(x_1);
    switch (x_2) {
        case 0: {
            x_3 = tagged_urn_formal__l_String_dquote_d__closed__0();
            x_4 = tagged_urn_formal__l_String_dquote_d__closed__1();
            x_5 = tagged_urn_formal__l_String_dInternal_dfoldl(x_3, x_4, x_1);
            x_6 = tagged_urn_formal__l_String_dInternal_dappend(x_5, x_4);
            return x_6;
        }
        default: {
            lungo_dec_ref(x_1);
            x_7 = tagged_urn_formal__l_String_dquote_d__closed__2();
            return x_7;
        }
    }
}

/* Lean: String.quote._closed_0 */
/* Compiled from: String.quote */
/* Source: <lean>/Init/Data/Repr.lean:392:1 */
static lungo_obj tagged_urn_formal__l_String_dquote_d__closed__0__init(void) {
    uint8_t x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    x_1 = (uint8_t)1u;
    x_2 = lungo_box((size_t)x_1);
    x_3 = lungo_alloc_closure((void *)tagged_urn_formal__l_String_dquote_d__lam__0_d__boxed, 3, 1);
    lungo_closure_set(x_3, 0, x_2);
    return x_3;
}
static lungo_lazy_obj tagged_urn_formal__l_String_dquote_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_String_dquote_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_String_dquote_d__closed__0__cell, tagged_urn_formal__l_String_dquote_d__closed__0__init);
}

/* Lean: String.quote._closed_1 */
/* Compiled from: String.quote */
/* Source: <lean>/Init/Data/Repr.lean:392:1 */
static lungo_obj tagged_urn_formal__l_String_dquote_d__closed__1__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"\"", 1, 1);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_String_dquote_d__closed__1__cell;
lungo_obj tagged_urn_formal__l_String_dquote_d__closed__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_String_dquote_d__closed__1__cell, tagged_urn_formal__l_String_dquote_d__closed__1__init);
}

/* Lean: String.quote._closed_2 */
/* Compiled from: String.quote */
/* Source: <lean>/Init/Data/Repr.lean:392:1 */
static lungo_obj tagged_urn_formal__l_String_dquote_d__closed__2__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"\"\"", 2, 2);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_String_dquote_d__closed__2__cell;
lungo_obj tagged_urn_formal__l_String_dquote_d__closed__2(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_String_dquote_d__closed__2__cell, tagged_urn_formal__l_String_dquote_d__closed__2__init);
}

/* Lean: String.quote._lam_0 */
/* Compiled from: String.quote */
/* Source: <lean>/Init/Data/Repr.lean:392:1 */
lungo_obj tagged_urn_formal__l_String_dquote_d__lam__0(uint8_t x_1, lungo_obj x_2, uint32_t x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    x_4 = tagged_urn_formal__l_Char_dquoteCore(x_3, x_1);
    x_5 = tagged_urn_formal__l_String_dInternal_dappend(x_2, x_4);
    lungo_dec_ref(x_4);
    return x_5;
}

/* Lean: String.quote._lam_0._boxed */
/* Compiled from: String.quote */
/* Source: <lean>/Init/Data/Repr.lean:392:1 */
lungo_obj tagged_urn_formal__l_String_dquote_d__lam__0_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    uint8_t x_4;
    uint32_t x_5;
    lungo_obj x_6;
    x_4 = (uint8_t)lungo_unbox(x_1);
    x_5 = lungo_unbox_uint32(x_3);
    lungo_dec(x_3);
    x_6 = tagged_urn_formal__l_String_dquote_d__lam__0(x_4, x_2, x_5);
    return x_6;
}

/* Lean: USize.repr */
/* Source: <lean>/Init/Data/Repr.lean:220:1 */
lungo_obj tagged_urn_formal__l_USize_drepr(size_t x_1) {
    lungo_obj r = lungo_lean_string_of_usize(x_1);
    return r;
}

/* Lean: _private.Init.Data.Repr.0.Char.quoteCore.smallCharToHex */
/* Source: <lean>/Init/Data/Repr.lean:369:3 */
lungo_obj tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dChar_dquoteCore_dsmallCharToHex(uint32_t x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    x_2 = tagged_urn_formal__l_UInt32_dtoNat(x_1);
    x_3 = lungo_usize_to_nat(16u);
    x_4 = lungo_usize_to_nat(4u);
    x_5 = tagged_urn_formal__l_Nat_dshiftRight(x_2, x_4);
    x_6 = tagged_urn_formal__l_Nat_dmod(x_2, x_3);
    lungo_dec(x_2);
    x_7 = tagged_urn_formal__l_hexDigitRepr(x_5);
    lungo_dec(x_5);
    x_8 = tagged_urn_formal__l_hexDigitRepr(x_6);
    lungo_dec(x_6);
    x_9 = tagged_urn_formal__l_String_dInternal_dappend(x_7, x_8);
    lungo_dec_ref(x_8);
    return x_9;
}

/* Lean: _private.Init.Data.Repr.0.Nat.reprArray */
/* Source: <lean>/Init/Data/Repr.lean:234:1 */
static lungo_obj tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray__init(void) {
    lungo_obj x_1;
    x_1 = tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__2();
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray__cell;
lungo_obj tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray__cell, tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray__init);
}

/* Lean: _private.Init.Data.Repr.0.Nat.reprArray._closed_0 */
/* Compiled from: _private.Init.Data.Repr.0.Nat.reprArray */
/* Source: <lean>/Init/Data/Repr.lean:234:1 */
static lungo_obj tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__0__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = lungo_usize_to_nat(128u);
    x_2 = tagged_urn_formal__l_List_drange(x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__0__cell;
lungo_obj tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__0__cell, tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__0__init);
}

/* Lean: _private.Init.Data.Repr.0.Nat.reprArray._closed_1 */
/* Compiled from: _private.Init.Data.Repr.0.Nat.reprArray */
/* Source: <lean>/Init/Data/Repr.lean:234:1 */
static lungo_obj tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__1__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    x_1 = lungo_box(0);
    x_2 = tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__0();
    x_3 = tagged_urn_formal__l_List_dmapTR_dloop_d__at___d__private_dInit_dData_dRepr_d0_dNat_dreprArray_dspec__0(x_2, x_1);
    return x_3;
}
static lungo_lazy_obj tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__1__cell;
lungo_obj tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__1__cell, tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__1__init);
}

/* Lean: _private.Init.Data.Repr.0.Nat.reprArray._closed_2 */
/* Compiled from: _private.Init.Data.Repr.0.Nat.reprArray */
/* Source: <lean>/Init/Data/Repr.lean:234:1 */
static lungo_obj tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__2__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__1();
    x_2 = tagged_urn_formal__l_Array_dmk(lungo_box(0), x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__2__cell;
lungo_obj tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__2(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__2__cell, tagged_urn_formal__l___private_dInit_dData_dRepr_d0_dNat_dreprArray_d__closed__2__init);
}

/* Lean: hexDigitRepr */
/* Source: <lean>/Init/Data/Repr.lean:357:1 */
lungo_obj tagged_urn_formal__l_hexDigitRepr(lungo_obj x_1) {
    uint32_t x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    x_2 = tagged_urn_formal__l_Nat_ddigitChar(x_1);
    x_3 = tagged_urn_formal__l_hexDigitRepr_d__closed__0();
    x_4 = tagged_urn_formal__l_String_dpush(x_3, x_2);
    return x_4;
}

/* Lean: hexDigitRepr._closed_0 */
/* Compiled from: hexDigitRepr */
/* Source: <lean>/Init/Data/Repr.lean:357:1 */
static lungo_obj tagged_urn_formal__l_hexDigitRepr_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"", 0, 0);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_hexDigitRepr_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_hexDigitRepr_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_hexDigitRepr_d__closed__0__cell, tagged_urn_formal__l_hexDigitRepr_d__closed__0__init);
}

