/* Generated by lungo 1.72.2908 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.String.Bootstrap. */
#include "tagged_urn_formal_program.h"

/* Lean: String.Internal.append */
/* Source: <lean>/Init/Data/String/Bootstrap.lean:77:1 */
lungo_obj tagged_urn_formal__l_String_dInternal_dappend(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj r = lungo_lean_string_append(x_1, x_2);
    return r;
}

/* Lean: String.Internal.foldl */
/* Source: <lean>/Init/Data/String/Bootstrap.lean:88:1 */
lungo_obj tagged_urn_formal__l_String_dInternal_dfoldl(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj r = tagged_urn_formal__l_String_dInternal_dfoldlImpl(x_1, x_2, x_3);
    return r;
}

/* Lean: String.Internal.isEmpty */
/* Source: <lean>/Init/Data/String/Bootstrap.lean:84:1 */
uint8_t tagged_urn_formal__l_String_dInternal_disEmpty(lungo_obj x_1) {
    uint8_t r = tagged_urn_formal__l_String_dInternal_disEmptyImpl(x_1);
    return r;
}

/* Lean: String.Internal.length */
/* Source: <lean>/Init/Data/String/Bootstrap.lean:70:1 */
lungo_obj tagged_urn_formal__l_String_dInternal_dlength(lungo_obj x_1) {
    lungo_obj r = lungo_lean_string_length(x_1);
    return r;
}

/* Lean: String.push */
/* Source: <lean>/Init/Data/String/Bootstrap.lean:23:1 */
lungo_obj tagged_urn_formal__l_String_dpush(lungo_obj x_1, uint32_t x_2) {
    lungo_obj r = lungo_lean_string_push(x_1, x_2);
    return r;
}

