/* Generated by lungo 1.87.175 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.System.IOError. */
#include "tagged_urn_formal_program.h"

/* Lean: IO.Error.fopenErrorToString */
/* Source: <lean>/Init/System/IOError.lean:256:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dfopenErrorToString(lungo_obj x_1, lungo_obj x_2, uint32_t x_3, lungo_obj x_4) {
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    lungo_obj x_15;
    lungo_obj x_16;
    lungo_obj x_17;
    lungo_obj x_18;
    lungo_obj x_19;
    lungo_obj x_20;
    lungo_obj x_21;
    lungo_obj x_22;
    lungo_obj x_23;
    lungo_obj x_24;
    lungo_obj x_25;
    lungo_obj x_26;
    lungo_obj x_27;
    switch (lungo_obj_tag(x_4)) {
        case 0: {
            x_5 = tagged_urn_formal__l___private_dInit_dSystem_dIOError_d0_dIO_dError_ddownCaseFirst(x_1);
            x_6 = tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__0();
            x_7 = tagged_urn_formal__l_String_dappend(x_5, x_6);
            x_8 = tagged_urn_formal__l_UInt32_dtoNat(x_3);
            x_9 = tagged_urn_formal__l_Nat_dreprFast(x_8);
            x_10 = tagged_urn_formal__l_String_dappend(x_7, x_9);
            lungo_dec_ref(x_9);
            x_11 = tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__1();
            x_12 = tagged_urn_formal__l_String_dappend(x_10, x_11);
            x_13 = tagged_urn_formal__l_String_dappend(x_12, x_2);
            return x_13;
        }
        default: {
            x_14 = lungo_ctor_get(x_4, 0);
            lungo_inc(x_14);
            lungo_dec_ref(x_4);
            x_15 = tagged_urn_formal__l___private_dInit_dSystem_dIOError_d0_dIO_dError_ddownCaseFirst(x_1);
            x_16 = tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__0();
            x_17 = tagged_urn_formal__l_String_dappend(x_15, x_16);
            x_18 = tagged_urn_formal__l_UInt32_dtoNat(x_3);
            x_19 = tagged_urn_formal__l_Nat_dreprFast(x_18);
            x_20 = tagged_urn_formal__l_String_dappend(x_17, x_19);
            lungo_dec_ref(x_19);
            x_21 = tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__2();
            x_22 = tagged_urn_formal__l_String_dappend(x_20, x_21);
            x_23 = tagged_urn_formal__l___private_dInit_dSystem_dIOError_d0_dIO_dError_ddownCaseFirst(x_14);
            x_24 = tagged_urn_formal__l_String_dappend(x_22, x_23);
            lungo_dec_ref(x_23);
            x_25 = tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__1();
            x_26 = tagged_urn_formal__l_String_dappend(x_24, x_25);
            x_27 = tagged_urn_formal__l_String_dappend(x_26, x_2);
            return x_27;
        }
    }
}

/* Lean: IO.Error.fopenErrorToString._closed_0 */
/* Compiled from: IO.Error.fopenErrorToString */
/* Source: <lean>/Init/System/IOError.lean:256:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)" (error code: ", 14, 14);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__0__cell, tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__0__init);
}

/* Lean: IO.Error.fopenErrorToString._closed_1 */
/* Compiled from: IO.Error.fopenErrorToString */
/* Source: <lean>/Init/System/IOError.lean:256:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__1__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)")\012  file: ", 10, 10);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__1__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__1__cell, tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__1__init);
}

/* Lean: IO.Error.fopenErrorToString._closed_2 */
/* Compiled from: IO.Error.fopenErrorToString */
/* Source: <lean>/Init/System/IOError.lean:256:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__2__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)", ", 2, 2);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__2__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__2(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__2__cell, tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__2__init);
}

/* Lean: IO.Error.mkAlreadyExists */
/* Source: <lean>/Init/System/IOError.lean:202:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkAlreadyExists(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    x_3 = lungo_box(0);
    x_4 = lungo_alloc_ctor(0, 2, 4);
    lungo_ctor_set(x_4, 0, x_3);
    lungo_ctor_set(x_4, 1, x_2);
    lungo_ctor_set_uint32(x_4, 2 * sizeof(size_t), x_1);
    return x_4;
}

/* Lean: IO.Error.mkAlreadyExistsFile */
/* Source: <lean>/Init/System/IOError.lean:158:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkAlreadyExistsFile(lungo_obj x_1, uint32_t x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    x_4 = lungo_alloc_ctor(1, 1, 0);
    lungo_ctor_set(x_4, 0, x_1);
    x_5 = lungo_alloc_ctor(0, 2, 4);
    lungo_ctor_set(x_5, 0, x_4);
    lungo_ctor_set(x_5, 1, x_3);
    lungo_ctor_set_uint32(x_5, 2 * sizeof(size_t), x_2);
    return x_5;
}

/* Lean: IO.Error.mkEofError */
/* Source: <lean>/Init/System/IOError.lean:162:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkEofError(lungo_obj x_1) {
    (void)x_1;
    lungo_obj x_2;
    x_2 = lungo_box(17);
    return x_2;
}

/* Lean: IO.Error.mkHardwareFault */
/* Source: <lean>/Init/System/IOError.lean:234:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkHardwareFault(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = lungo_alloc_ctor(5, 1, 4);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set_uint32(x_3, 1 * sizeof(size_t), x_1);
    return x_3;
}

/* Lean: IO.Error.mkIllegalOperation */
/* Source: <lean>/Init/System/IOError.lean:242:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkIllegalOperation(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = lungo_alloc_ctor(7, 1, 4);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set_uint32(x_3, 1 * sizeof(size_t), x_1);
    return x_3;
}

/* Lean: IO.Error.mkInappropriateType */
/* Source: <lean>/Init/System/IOError.lean:206:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkInappropriateType(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    x_3 = lungo_box(0);
    x_4 = lungo_alloc_ctor(15, 2, 4);
    lungo_ctor_set(x_4, 0, x_3);
    lungo_ctor_set(x_4, 1, x_2);
    lungo_ctor_set_uint32(x_4, 2 * sizeof(size_t), x_1);
    return x_4;
}

/* Lean: IO.Error.mkInappropriateTypeFile */
/* Source: <lean>/Init/System/IOError.lean:166:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkInappropriateTypeFile(lungo_obj x_1, uint32_t x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    x_4 = lungo_alloc_ctor(1, 1, 0);
    lungo_ctor_set(x_4, 0, x_1);
    x_5 = lungo_alloc_ctor(15, 2, 4);
    lungo_ctor_set(x_5, 0, x_4);
    lungo_ctor_set(x_5, 1, x_3);
    lungo_ctor_set_uint32(x_5, 2 * sizeof(size_t), x_2);
    return x_5;
}

/* Lean: IO.Error.mkInterrupted */
/* Source: <lean>/Init/System/IOError.lean:170:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkInterrupted(lungo_obj x_1, uint32_t x_2, lungo_obj x_3) {
    lungo_obj x_4;
    x_4 = lungo_alloc_ctor(10, 2, 4);
    lungo_ctor_set(x_4, 0, x_1);
    lungo_ctor_set(x_4, 1, x_3);
    lungo_ctor_set_uint32(x_4, 2 * sizeof(size_t), x_2);
    return x_4;
}

/* Lean: IO.Error.mkInvalidArgument */
/* Source: <lean>/Init/System/IOError.lean:222:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkInvalidArgument(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    x_3 = lungo_box(0);
    x_4 = lungo_alloc_ctor(12, 2, 4);
    lungo_ctor_set(x_4, 0, x_3);
    lungo_ctor_set(x_4, 1, x_2);
    lungo_ctor_set_uint32(x_4, 2 * sizeof(size_t), x_1);
    return x_4;
}

/* Lean: IO.Error.mkInvalidArgumentFile */
/* Source: <lean>/Init/System/IOError.lean:174:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkInvalidArgumentFile(lungo_obj x_1, uint32_t x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    x_4 = lungo_alloc_ctor(1, 1, 0);
    lungo_ctor_set(x_4, 0, x_1);
    x_5 = lungo_alloc_ctor(12, 2, 4);
    lungo_ctor_set(x_5, 0, x_4);
    lungo_ctor_set(x_5, 1, x_3);
    lungo_ctor_set_uint32(x_5, 2 * sizeof(size_t), x_2);
    return x_5;
}

/* Lean: IO.Error.mkNoFileOrDirectory */
/* Source: <lean>/Init/System/IOError.lean:178:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkNoFileOrDirectory(lungo_obj x_1, uint32_t x_2, lungo_obj x_3) {
    lungo_obj x_4;
    x_4 = lungo_alloc_ctor(11, 2, 4);
    lungo_ctor_set(x_4, 0, x_1);
    lungo_ctor_set(x_4, 1, x_3);
    lungo_ctor_set_uint32(x_4, 2 * sizeof(size_t), x_2);
    return x_4;
}

/* Lean: IO.Error.mkNoSuchThing */
/* Source: <lean>/Init/System/IOError.lean:210:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkNoSuchThing(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    x_3 = lungo_box(0);
    x_4 = lungo_alloc_ctor(16, 2, 4);
    lungo_ctor_set(x_4, 0, x_3);
    lungo_ctor_set(x_4, 1, x_2);
    lungo_ctor_set_uint32(x_4, 2 * sizeof(size_t), x_1);
    return x_4;
}

/* Lean: IO.Error.mkNoSuchThingFile */
/* Source: <lean>/Init/System/IOError.lean:182:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkNoSuchThingFile(lungo_obj x_1, uint32_t x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    x_4 = lungo_alloc_ctor(1, 1, 0);
    lungo_ctor_set(x_4, 0, x_1);
    x_5 = lungo_alloc_ctor(16, 2, 4);
    lungo_ctor_set(x_5, 0, x_4);
    lungo_ctor_set(x_5, 1, x_3);
    lungo_ctor_set_uint32(x_5, 2 * sizeof(size_t), x_2);
    return x_5;
}

/* Lean: IO.Error.mkOtherError */
/* Source: <lean>/Init/System/IOError.lean:226:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkOtherError(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = lungo_alloc_ctor(1, 1, 4);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set_uint32(x_3, 1 * sizeof(size_t), x_1);
    return x_3;
}

/* Lean: IO.Error.mkPermissionDenied */
/* Source: <lean>/Init/System/IOError.lean:230:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkPermissionDenied(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    x_3 = lungo_box(0);
    x_4 = lungo_alloc_ctor(13, 2, 4);
    lungo_ctor_set(x_4, 0, x_3);
    lungo_ctor_set(x_4, 1, x_2);
    lungo_ctor_set_uint32(x_4, 2 * sizeof(size_t), x_1);
    return x_4;
}

/* Lean: IO.Error.mkPermissionDeniedFile */
/* Source: <lean>/Init/System/IOError.lean:186:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkPermissionDeniedFile(lungo_obj x_1, uint32_t x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    x_4 = lungo_alloc_ctor(1, 1, 0);
    lungo_ctor_set(x_4, 0, x_1);
    x_5 = lungo_alloc_ctor(13, 2, 4);
    lungo_ctor_set(x_5, 0, x_4);
    lungo_ctor_set(x_5, 1, x_3);
    lungo_ctor_set_uint32(x_5, 2 * sizeof(size_t), x_2);
    return x_5;
}

/* Lean: IO.Error.mkProtocolError */
/* Source: <lean>/Init/System/IOError.lean:246:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkProtocolError(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = lungo_alloc_ctor(8, 1, 4);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set_uint32(x_3, 1 * sizeof(size_t), x_1);
    return x_3;
}

/* Lean: IO.Error.mkResourceBusy */
/* Source: <lean>/Init/System/IOError.lean:218:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkResourceBusy(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = lungo_alloc_ctor(2, 1, 4);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set_uint32(x_3, 1 * sizeof(size_t), x_1);
    return x_3;
}

/* Lean: IO.Error.mkResourceExhausted */
/* Source: <lean>/Init/System/IOError.lean:198:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkResourceExhausted(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    x_3 = lungo_box(0);
    x_4 = lungo_alloc_ctor(14, 2, 4);
    lungo_ctor_set(x_4, 0, x_3);
    lungo_ctor_set(x_4, 1, x_2);
    lungo_ctor_set_uint32(x_4, 2 * sizeof(size_t), x_1);
    return x_4;
}

/* Lean: IO.Error.mkResourceExhaustedFile */
/* Source: <lean>/Init/System/IOError.lean:190:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkResourceExhaustedFile(lungo_obj x_1, uint32_t x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    x_4 = lungo_alloc_ctor(1, 1, 0);
    lungo_ctor_set(x_4, 0, x_1);
    x_5 = lungo_alloc_ctor(14, 2, 4);
    lungo_ctor_set(x_5, 0, x_4);
    lungo_ctor_set(x_5, 1, x_3);
    lungo_ctor_set_uint32(x_5, 2 * sizeof(size_t), x_2);
    return x_5;
}

/* Lean: IO.Error.mkResourceVanished */
/* Source: <lean>/Init/System/IOError.lean:214:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkResourceVanished(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = lungo_alloc_ctor(3, 1, 4);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set_uint32(x_3, 1 * sizeof(size_t), x_1);
    return x_3;
}

/* Lean: IO.Error.mkTimeExpired */
/* Source: <lean>/Init/System/IOError.lean:250:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkTimeExpired(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = lungo_alloc_ctor(9, 1, 4);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set_uint32(x_3, 1 * sizeof(size_t), x_1);
    return x_3;
}

/* Lean: IO.Error.mkUnsatisfiedConstraints */
/* Source: <lean>/Init/System/IOError.lean:238:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkUnsatisfiedConstraints(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = lungo_alloc_ctor(6, 1, 4);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set_uint32(x_3, 1 * sizeof(size_t), x_1);
    return x_3;
}

/* Lean: IO.Error.mkUnsupportedOperation */
/* Source: <lean>/Init/System/IOError.lean:194:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dmkUnsupportedOperation(uint32_t x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = lungo_alloc_ctor(4, 1, 4);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set_uint32(x_3, 1 * sizeof(size_t), x_1);
    return x_3;
}

/* Lean: IO.Error.otherErrorToString */
/* Source: <lean>/Init/System/IOError.lean:260:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dotherErrorToString(lungo_obj x_1, uint32_t x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    lungo_obj x_15;
    lungo_obj x_16;
    lungo_obj x_17;
    lungo_obj x_18;
    lungo_obj x_19;
    lungo_obj x_20;
    lungo_obj x_21;
    lungo_obj x_22;
    lungo_obj x_23;
    lungo_obj x_24;
    switch (lungo_obj_tag(x_3)) {
        case 0: {
            x_4 = tagged_urn_formal__l___private_dInit_dSystem_dIOError_d0_dIO_dError_ddownCaseFirst(x_1);
            x_5 = tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__0();
            x_6 = tagged_urn_formal__l_String_dappend(x_4, x_5);
            x_7 = tagged_urn_formal__l_UInt32_dtoNat(x_2);
            x_8 = tagged_urn_formal__l_Nat_dreprFast(x_7);
            x_9 = tagged_urn_formal__l_String_dappend(x_6, x_8);
            lungo_dec_ref(x_8);
            x_10 = tagged_urn_formal__l_IO_dError_dotherErrorToString_d__closed__0();
            x_11 = tagged_urn_formal__l_String_dappend(x_9, x_10);
            return x_11;
        }
        default: {
            x_12 = lungo_ctor_get(x_3, 0);
            lungo_inc(x_12);
            lungo_dec_ref(x_3);
            x_13 = tagged_urn_formal__l___private_dInit_dSystem_dIOError_d0_dIO_dError_ddownCaseFirst(x_1);
            x_14 = tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__0();
            x_15 = tagged_urn_formal__l_String_dappend(x_13, x_14);
            x_16 = tagged_urn_formal__l_UInt32_dtoNat(x_2);
            x_17 = tagged_urn_formal__l_Nat_dreprFast(x_16);
            x_18 = tagged_urn_formal__l_String_dappend(x_15, x_17);
            lungo_dec_ref(x_17);
            x_19 = tagged_urn_formal__l_IO_dError_dfopenErrorToString_d__closed__2();
            x_20 = tagged_urn_formal__l_String_dappend(x_18, x_19);
            x_21 = tagged_urn_formal__l___private_dInit_dSystem_dIOError_d0_dIO_dError_ddownCaseFirst(x_12);
            x_22 = tagged_urn_formal__l_String_dappend(x_20, x_21);
            lungo_dec_ref(x_21);
            x_23 = tagged_urn_formal__l_IO_dError_dotherErrorToString_d__closed__0();
            x_24 = tagged_urn_formal__l_String_dappend(x_22, x_23);
            return x_24;
        }
    }
}

/* Lean: IO.Error.otherErrorToString._closed_0 */
/* Compiled from: IO.Error.otherErrorToString */
/* Source: <lean>/Init/System/IOError.lean:260:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dotherErrorToString_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)")", 1, 1);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dotherErrorToString_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dotherErrorToString_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dotherErrorToString_d__closed__0__cell, tagged_urn_formal__l_IO_dError_dotherErrorToString_d__closed__0__init);
}

/* Lean: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
lungo_obj tagged_urn_formal__l_IO_dError_dtoString(lungo_obj x_1) {
    uint32_t x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    uint32_t x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    uint32_t x_13;
    lungo_obj x_14;
    lungo_obj x_15;
    lungo_obj x_17;
    uint8_t x_18;
    lungo_obj x_19;
    lungo_obj x_21;
    lungo_obj x_22;
    lungo_obj x_23;
    uint8_t x_24;
    uint32_t x_25;
    lungo_obj x_26;
    uint32_t x_27;
    lungo_obj x_28;
    lungo_obj x_29;
    lungo_obj x_30;
    lungo_obj x_31;
    uint32_t x_32;
    lungo_obj x_33;
    lungo_obj x_34;
    lungo_obj x_35;
    lungo_obj x_36;
    uint32_t x_37;
    lungo_obj x_38;
    lungo_obj x_39;
    lungo_obj x_40;
    lungo_obj x_41;
    uint32_t x_42;
    lungo_obj x_43;
    lungo_obj x_44;
    lungo_obj x_45;
    uint32_t x_46;
    lungo_obj x_47;
    lungo_obj x_48;
    lungo_obj x_49;
    uint32_t x_50;
    lungo_obj x_51;
    lungo_obj x_52;
    lungo_obj x_53;
    lungo_obj x_54;
    uint32_t x_55;
    lungo_obj x_56;
    lungo_obj x_57;
    lungo_obj x_58;
    lungo_obj x_59;
    uint32_t x_60;
    lungo_obj x_61;
    lungo_obj x_62;
    lungo_obj x_63;
    lungo_obj x_64;
    lungo_obj x_65;
    uint32_t x_66;
    lungo_obj x_67;
    lungo_obj x_68;
    lungo_obj x_69;
    lungo_obj x_70;
    lungo_obj x_71;
    uint32_t x_72;
    lungo_obj x_73;
    lungo_obj x_74;
    lungo_obj x_75;
    lungo_obj x_76;
    uint32_t x_77;
    lungo_obj x_78;
    lungo_obj x_79;
    lungo_obj x_80;
    lungo_obj x_81;
    uint32_t x_82;
    lungo_obj x_83;
    lungo_obj x_84;
    lungo_obj x_86;
    uint8_t x_87;
    lungo_obj x_88;
    lungo_obj x_90;
    lungo_obj x_91;
    lungo_obj x_92;
    uint8_t x_93;
    lungo_obj x_94;
    uint32_t x_95;
    lungo_obj x_96;
    uint32_t x_97;
    lungo_obj x_98;
    lungo_obj x_99;
    lungo_obj x_100;
    lungo_obj x_101;
    lungo_obj x_102;
    uint32_t x_103;
    lungo_obj x_104;
    lungo_obj x_105;
    lungo_obj x_106;
    lungo_obj x_107;
    uint32_t x_108;
    lungo_obj x_109;
    lungo_obj x_110;
    lungo_obj x_112;
    uint8_t x_113;
    lungo_obj x_114;
    lungo_obj x_116;
    lungo_obj x_117;
    lungo_obj x_118;
    uint8_t x_119;
    lungo_obj x_120;
    uint32_t x_121;
    lungo_obj x_122;
    lungo_obj x_123;
    lungo_obj x_124;
    lungo_obj x_125;
    uint32_t x_126;
    lungo_obj x_127;
    lungo_obj x_128;
    lungo_obj x_130;
    uint8_t x_131;
    lungo_obj x_132;
    lungo_obj x_134;
    lungo_obj x_135;
    lungo_obj x_136;
    uint8_t x_137;
    lungo_obj x_138;
    uint32_t x_139;
    lungo_obj x_140;
    lungo_obj x_141;
    lungo_obj x_142;
    lungo_obj x_143;
    uint32_t x_144;
    lungo_obj x_145;
    lungo_obj x_146;
    lungo_obj x_148;
    uint8_t x_149;
    lungo_obj x_150;
    lungo_obj x_152;
    lungo_obj x_153;
    lungo_obj x_154;
    uint8_t x_155;
    lungo_obj x_156;
    lungo_obj x_157;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_7 = lungo_ctor_get(x_1, 0);
            lungo_inc(x_7);
            switch (lungo_obj_tag(x_7)) {
                case 0: {
                    x_8 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
                    x_9 = lungo_ctor_get(x_1, 1);
                    lungo_inc_ref(x_9);
                    lungo_dec_ref(x_1);
                    x_10 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__0();
                    x_11 = lungo_alloc_ctor(1, 1, 0);
                    lungo_ctor_set(x_11, 0, x_9);
                    x_12 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_10, x_8, x_11);
                    return x_12;
                }
                default: {
                    x_13 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
                    x_14 = lungo_ctor_get(x_1, 1);
                    lungo_inc_ref(x_14);
                    lungo_dec_ref(x_1);
                    x_15 = lungo_ctor_get(x_7, 0);
                    x_24 = !lungo_is_exclusive(x_7);
                    switch (x_24) {
                        case 0: {
                            x_17 = x_7;
                            x_18 = x_24;
                            goto block_16;
                        }
                        default: {
                            lungo_inc(x_15);
                            lungo_dec(x_7);
                            x_17 = lungo_box(0);
                            x_18 = x_24;
                            goto block_16;
                        }
                    }
                    block_16:;
                    x_19 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__0();
                    switch (x_18) {
                        case 0: {
                            lungo_ctor_set(x_17, 0, x_14);
                            x_21 = x_17;
                            goto block_20;
                        }
                        default: {
                            x_23 = lungo_alloc_ctor(1, 1, 0);
                            lungo_ctor_set(x_23, 0, x_14);
                            x_21 = x_23;
                            goto block_20;
                        }
                    }
                    block_20:;
                    x_22 = tagged_urn_formal__l_IO_dError_dfopenErrorToString(x_19, x_15, x_13, x_21);
                    lungo_dec(x_15);
                    return x_22;
                }
            }
        }
        case 1: {
            x_25 = lungo_ctor_get_uint32(x_1, 1 * sizeof(size_t));
            x_26 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_26);
            lungo_dec_ref(x_1);
            x_3 = x_25;
            x_4 = x_26;
            goto block_2;
        }
        case 2: {
            x_27 = lungo_ctor_get_uint32(x_1, 1 * sizeof(size_t));
            x_28 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_28);
            lungo_dec_ref(x_1);
            x_29 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__1();
            x_30 = lungo_alloc_ctor(1, 1, 0);
            lungo_ctor_set(x_30, 0, x_28);
            x_31 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_29, x_27, x_30);
            return x_31;
        }
        case 3: {
            x_32 = lungo_ctor_get_uint32(x_1, 1 * sizeof(size_t));
            x_33 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_33);
            lungo_dec_ref(x_1);
            x_34 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__2();
            x_35 = lungo_alloc_ctor(1, 1, 0);
            lungo_ctor_set(x_35, 0, x_33);
            x_36 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_34, x_32, x_35);
            return x_36;
        }
        case 4: {
            x_37 = lungo_ctor_get_uint32(x_1, 1 * sizeof(size_t));
            x_38 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_38);
            lungo_dec_ref(x_1);
            x_39 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__3();
            x_40 = lungo_alloc_ctor(1, 1, 0);
            lungo_ctor_set(x_40, 0, x_38);
            x_41 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_39, x_37, x_40);
            return x_41;
        }
        case 5: {
            x_42 = lungo_ctor_get_uint32(x_1, 1 * sizeof(size_t));
            lungo_dec_ref(x_1);
            x_43 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__4();
            x_44 = lungo_box(0);
            x_45 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_43, x_42, x_44);
            return x_45;
        }
        case 6: {
            x_46 = lungo_ctor_get_uint32(x_1, 1 * sizeof(size_t));
            lungo_dec_ref(x_1);
            x_47 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__5();
            x_48 = lungo_box(0);
            x_49 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_47, x_46, x_48);
            return x_49;
        }
        case 7: {
            x_50 = lungo_ctor_get_uint32(x_1, 1 * sizeof(size_t));
            x_51 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_51);
            lungo_dec_ref(x_1);
            x_52 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__6();
            x_53 = lungo_alloc_ctor(1, 1, 0);
            lungo_ctor_set(x_53, 0, x_51);
            x_54 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_52, x_50, x_53);
            return x_54;
        }
        case 8: {
            x_55 = lungo_ctor_get_uint32(x_1, 1 * sizeof(size_t));
            x_56 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_56);
            lungo_dec_ref(x_1);
            x_57 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__7();
            x_58 = lungo_alloc_ctor(1, 1, 0);
            lungo_ctor_set(x_58, 0, x_56);
            x_59 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_57, x_55, x_58);
            return x_59;
        }
        case 9: {
            x_60 = lungo_ctor_get_uint32(x_1, 1 * sizeof(size_t));
            x_61 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_61);
            lungo_dec_ref(x_1);
            x_62 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__8();
            x_63 = lungo_alloc_ctor(1, 1, 0);
            lungo_ctor_set(x_63, 0, x_61);
            x_64 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_62, x_60, x_63);
            return x_64;
        }
        case 10: {
            x_65 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_65);
            x_66 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
            x_67 = lungo_ctor_get(x_1, 1);
            lungo_inc_ref(x_67);
            lungo_dec_ref(x_1);
            x_68 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__9();
            x_69 = lungo_alloc_ctor(1, 1, 0);
            lungo_ctor_set(x_69, 0, x_67);
            x_70 = tagged_urn_formal__l_IO_dError_dfopenErrorToString(x_68, x_65, x_66, x_69);
            lungo_dec_ref(x_65);
            return x_70;
        }
        case 11: {
            x_71 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_71);
            x_72 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
            lungo_dec_ref(x_1);
            x_73 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__10();
            x_74 = lungo_box(0);
            x_75 = tagged_urn_formal__l_IO_dError_dfopenErrorToString(x_73, x_71, x_72, x_74);
            lungo_dec_ref(x_71);
            return x_75;
        }
        case 12: {
            x_76 = lungo_ctor_get(x_1, 0);
            lungo_inc(x_76);
            switch (lungo_obj_tag(x_76)) {
                case 0: {
                    x_77 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
                    x_78 = lungo_ctor_get(x_1, 1);
                    lungo_inc_ref(x_78);
                    lungo_dec_ref(x_1);
                    x_79 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__11();
                    x_80 = lungo_alloc_ctor(1, 1, 0);
                    lungo_ctor_set(x_80, 0, x_78);
                    x_81 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_79, x_77, x_80);
                    return x_81;
                }
                default: {
                    x_82 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
                    x_83 = lungo_ctor_get(x_1, 1);
                    lungo_inc_ref(x_83);
                    lungo_dec_ref(x_1);
                    x_84 = lungo_ctor_get(x_76, 0);
                    x_93 = !lungo_is_exclusive(x_76);
                    switch (x_93) {
                        case 0: {
                            x_86 = x_76;
                            x_87 = x_93;
                            goto block_85;
                        }
                        default: {
                            lungo_inc(x_84);
                            lungo_dec(x_76);
                            x_86 = lungo_box(0);
                            x_87 = x_93;
                            goto block_85;
                        }
                    }
                    block_85:;
                    x_88 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__11();
                    switch (x_87) {
                        case 0: {
                            lungo_ctor_set(x_86, 0, x_83);
                            x_90 = x_86;
                            goto block_89;
                        }
                        default: {
                            x_92 = lungo_alloc_ctor(1, 1, 0);
                            lungo_ctor_set(x_92, 0, x_83);
                            x_90 = x_92;
                            goto block_89;
                        }
                    }
                    block_89:;
                    x_91 = tagged_urn_formal__l_IO_dError_dfopenErrorToString(x_88, x_84, x_82, x_90);
                    lungo_dec(x_84);
                    return x_91;
                }
            }
        }
        case 13: {
            x_94 = lungo_ctor_get(x_1, 0);
            switch (lungo_obj_tag(x_94)) {
                case 0: {
                    x_95 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
                    x_96 = lungo_ctor_get(x_1, 1);
                    lungo_inc_ref(x_96);
                    lungo_dec_ref(x_1);
                    x_3 = x_95;
                    x_4 = x_96;
                    goto block_2;
                }
                default: {
                    lungo_inc_ref(x_94);
                    x_97 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
                    x_98 = lungo_ctor_get(x_1, 1);
                    lungo_inc_ref(x_98);
                    lungo_dec_ref(x_1);
                    x_99 = lungo_ctor_get(x_94, 0);
                    lungo_inc(x_99);
                    lungo_dec_ref(x_94);
                    x_100 = lungo_box(0);
                    x_101 = tagged_urn_formal__l_IO_dError_dfopenErrorToString(x_98, x_99, x_97, x_100);
                    lungo_dec(x_99);
                    return x_101;
                }
            }
        }
        case 14: {
            x_102 = lungo_ctor_get(x_1, 0);
            lungo_inc(x_102);
            switch (lungo_obj_tag(x_102)) {
                case 0: {
                    x_103 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
                    x_104 = lungo_ctor_get(x_1, 1);
                    lungo_inc_ref(x_104);
                    lungo_dec_ref(x_1);
                    x_105 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__12();
                    x_106 = lungo_alloc_ctor(1, 1, 0);
                    lungo_ctor_set(x_106, 0, x_104);
                    x_107 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_105, x_103, x_106);
                    return x_107;
                }
                default: {
                    x_108 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
                    x_109 = lungo_ctor_get(x_1, 1);
                    lungo_inc_ref(x_109);
                    lungo_dec_ref(x_1);
                    x_110 = lungo_ctor_get(x_102, 0);
                    x_119 = !lungo_is_exclusive(x_102);
                    switch (x_119) {
                        case 0: {
                            x_112 = x_102;
                            x_113 = x_119;
                            goto block_111;
                        }
                        default: {
                            lungo_inc(x_110);
                            lungo_dec(x_102);
                            x_112 = lungo_box(0);
                            x_113 = x_119;
                            goto block_111;
                        }
                    }
                    block_111:;
                    x_114 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__12();
                    switch (x_113) {
                        case 0: {
                            lungo_ctor_set(x_112, 0, x_109);
                            x_116 = x_112;
                            goto block_115;
                        }
                        default: {
                            x_118 = lungo_alloc_ctor(1, 1, 0);
                            lungo_ctor_set(x_118, 0, x_109);
                            x_116 = x_118;
                            goto block_115;
                        }
                    }
                    block_115:;
                    x_117 = tagged_urn_formal__l_IO_dError_dfopenErrorToString(x_114, x_110, x_108, x_116);
                    lungo_dec(x_110);
                    return x_117;
                }
            }
        }
        case 15: {
            x_120 = lungo_ctor_get(x_1, 0);
            lungo_inc(x_120);
            switch (lungo_obj_tag(x_120)) {
                case 0: {
                    x_121 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
                    x_122 = lungo_ctor_get(x_1, 1);
                    lungo_inc_ref(x_122);
                    lungo_dec_ref(x_1);
                    x_123 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__13();
                    x_124 = lungo_alloc_ctor(1, 1, 0);
                    lungo_ctor_set(x_124, 0, x_122);
                    x_125 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_123, x_121, x_124);
                    return x_125;
                }
                default: {
                    x_126 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
                    x_127 = lungo_ctor_get(x_1, 1);
                    lungo_inc_ref(x_127);
                    lungo_dec_ref(x_1);
                    x_128 = lungo_ctor_get(x_120, 0);
                    x_137 = !lungo_is_exclusive(x_120);
                    switch (x_137) {
                        case 0: {
                            x_130 = x_120;
                            x_131 = x_137;
                            goto block_129;
                        }
                        default: {
                            lungo_inc(x_128);
                            lungo_dec(x_120);
                            x_130 = lungo_box(0);
                            x_131 = x_137;
                            goto block_129;
                        }
                    }
                    block_129:;
                    x_132 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__13();
                    switch (x_131) {
                        case 0: {
                            lungo_ctor_set(x_130, 0, x_127);
                            x_134 = x_130;
                            goto block_133;
                        }
                        default: {
                            x_136 = lungo_alloc_ctor(1, 1, 0);
                            lungo_ctor_set(x_136, 0, x_127);
                            x_134 = x_136;
                            goto block_133;
                        }
                    }
                    block_133:;
                    x_135 = tagged_urn_formal__l_IO_dError_dfopenErrorToString(x_132, x_128, x_126, x_134);
                    lungo_dec(x_128);
                    return x_135;
                }
            }
        }
        case 16: {
            x_138 = lungo_ctor_get(x_1, 0);
            lungo_inc(x_138);
            switch (lungo_obj_tag(x_138)) {
                case 0: {
                    x_139 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
                    x_140 = lungo_ctor_get(x_1, 1);
                    lungo_inc_ref(x_140);
                    lungo_dec_ref(x_1);
                    x_141 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__14();
                    x_142 = lungo_alloc_ctor(1, 1, 0);
                    lungo_ctor_set(x_142, 0, x_140);
                    x_143 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_141, x_139, x_142);
                    return x_143;
                }
                default: {
                    x_144 = lungo_ctor_get_uint32(x_1, 2 * sizeof(size_t));
                    x_145 = lungo_ctor_get(x_1, 1);
                    lungo_inc_ref(x_145);
                    lungo_dec_ref(x_1);
                    x_146 = lungo_ctor_get(x_138, 0);
                    x_155 = !lungo_is_exclusive(x_138);
                    switch (x_155) {
                        case 0: {
                            x_148 = x_138;
                            x_149 = x_155;
                            goto block_147;
                        }
                        default: {
                            lungo_inc(x_146);
                            lungo_dec(x_138);
                            x_148 = lungo_box(0);
                            x_149 = x_155;
                            goto block_147;
                        }
                    }
                    block_147:;
                    x_150 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__14();
                    switch (x_149) {
                        case 0: {
                            lungo_ctor_set(x_148, 0, x_145);
                            x_152 = x_148;
                            goto block_151;
                        }
                        default: {
                            x_154 = lungo_alloc_ctor(1, 1, 0);
                            lungo_ctor_set(x_154, 0, x_145);
                            x_152 = x_154;
                            goto block_151;
                        }
                    }
                    block_151:;
                    x_153 = tagged_urn_formal__l_IO_dError_dfopenErrorToString(x_150, x_146, x_144, x_152);
                    lungo_dec(x_146);
                    return x_153;
                }
            }
        }
        case 17: {
            x_156 = tagged_urn_formal__l_IO_dError_dtoString_d__closed__15();
            return x_156;
        }
        default: {
            x_157 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_157);
            lungo_dec_ref(x_1);
            return x_157;
        }
    }
    block_2:;
    x_5 = lungo_box(0);
    x_6 = tagged_urn_formal__l_IO_dError_dotherErrorToString(x_4, x_3, x_5);
    return x_6;
}

/* Lean: IO.Error.toString._closed_0 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"already exists", 14, 14);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__0__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__0__init);
}

/* Lean: IO.Error.toString._closed_1 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__1__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"resource busy", 13, 13);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__1__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__1__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__1__init);
}

/* Lean: IO.Error.toString._closed_10 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__10__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"no such file or directory", 25, 25);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__10__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__10(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__10__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__10__init);
}

/* Lean: IO.Error.toString._closed_11 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__11__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"invalid argument", 16, 16);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__11__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__11(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__11__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__11__init);
}

/* Lean: IO.Error.toString._closed_12 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__12__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"resource exhausted", 18, 18);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__12__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__12(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__12__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__12__init);
}

/* Lean: IO.Error.toString._closed_13 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__13__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"inappropriate type", 18, 18);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__13__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__13(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__13__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__13__init);
}

/* Lean: IO.Error.toString._closed_14 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__14__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"no such thing", 13, 13);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__14__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__14(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__14__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__14__init);
}

/* Lean: IO.Error.toString._closed_15 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__15__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"end of file", 11, 11);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__15__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__15(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__15__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__15__init);
}

/* Lean: IO.Error.toString._closed_2 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__2__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"resource vanished", 17, 17);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__2__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__2(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__2__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__2__init);
}

/* Lean: IO.Error.toString._closed_3 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__3__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"unsupported operation", 21, 21);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__3__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__3(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__3__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__3__init);
}

/* Lean: IO.Error.toString._closed_4 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__4__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"hardware fault", 14, 14);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__4__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__4(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__4__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__4__init);
}

/* Lean: IO.Error.toString._closed_5 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__5__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"directory not empty", 19, 19);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__5__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__5(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__5__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__5__init);
}

/* Lean: IO.Error.toString._closed_6 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__6__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"illegal operation", 17, 17);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__6__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__6(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__6__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__6__init);
}

/* Lean: IO.Error.toString._closed_7 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__7__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"protocol error", 14, 14);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__7__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__7(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__7__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__7__init);
}

/* Lean: IO.Error.toString._closed_8 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__8__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"time expired", 12, 12);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__8__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__8(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__8__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__8__init);
}

/* Lean: IO.Error.toString._closed_9 */
/* Compiled from: IO.Error.toString */
/* Source: <lean>/Init/System/IOError.lean:264:1 */
static lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__9__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"interrupted system call", 23, 23);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__9__cell;
lungo_obj tagged_urn_formal__l_IO_dError_dtoString_d__closed__9(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_IO_dError_dtoString_d__closed__9__cell, tagged_urn_formal__l_IO_dError_dtoString_d__closed__9__init);
}

/* Lean: IO.userError */
/* Source: <lean>/Init/System/IOError.lean:145:1 */
lungo_obj tagged_urn_formal__l_IO_duserError(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = lungo_alloc_ctor(18, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}

/* Lean: _private.Init.System.IOError.0.IO.Error.downCaseFirst */
/* Source: <lean>/Init/System/IOError.lean:254:1 */
lungo_obj tagged_urn_formal__l___private_dInit_dSystem_dIOError_d0_dIO_dError_ddownCaseFirst(lungo_obj x_1) {
    lungo_obj x_2;
    uint32_t x_3;
    uint32_t x_4;
    uint8_t x_5;
    lungo_obj x_6;
    uint32_t x_7;
    uint8_t x_8;
    lungo_obj x_9;
    uint32_t x_10;
    uint32_t x_11;
    lungo_obj x_12;
    x_2 = lungo_usize_to_nat(0u);
    x_3 = tagged_urn_formal__l_String_dPos_dRaw_dget(x_1, x_2);
    x_4 = (uint32_t)65u;
    x_5 = tagged_urn_formal__l_UInt32_ddecLe(x_4, x_3);
    switch (x_5) {
        case 0: {
            x_6 = tagged_urn_formal__l_String_dPos_dRaw_dset(x_1, x_2, x_3);
            return x_6;
        }
        default: {
            x_7 = (uint32_t)90u;
            x_8 = tagged_urn_formal__l_UInt32_ddecLe(x_3, x_7);
            switch (x_8) {
                case 0: {
                    x_9 = tagged_urn_formal__l_String_dPos_dRaw_dset(x_1, x_2, x_3);
                    return x_9;
                }
                default: {
                    x_10 = (uint32_t)32u;
                    x_11 = tagged_urn_formal__l_UInt32_dadd(x_3, x_10);
                    x_12 = tagged_urn_formal__l_String_dPos_dRaw_dset(x_1, x_2, x_11);
                    return x_12;
                }
            }
        }
    }
}

