/* Generated by lungo 1.74.3213 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.ByteArray.Basic. */
#include "tagged_urn_formal_program.h"

/* Lean: ByteArray.get! */
/* Source: <lean>/Init/Data/ByteArray/Basic.lean:65:1 */
uint8_t tagged_urn_formal__l_ByteArray_dget_x21_(lungo_obj x_1, lungo_obj x_2) {
    uint8_t r = lungo_lean_byte_array_get(x_1, x_2);
    return r;
}

