/* Generated by lungo 1.81.24 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Data.String.Basic. */
#include "tagged_urn_formal_program.h"

/* Lean: String.Pos.Raw.get */
/* Source: <lean>/Init/Data/String/Basic.lean:1877:1 */
uint32_t tagged_urn_formal__l_String_dPos_dRaw_dget(lungo_obj x_1, lungo_obj x_2) {
    uint32_t r = lungo_lean_string_utf8_get(x_1, x_2);
    return r;
}

/* Lean: String.Pos.next */
/* Source: <lean>/Init/Data/String/Basic.lean:1663:1 */
lungo_obj tagged_urn_formal__l_String_dPos_dnext(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    (void)x_3;
    lungo_obj r = lungo_lean_string_utf8_next_fast(x_1, x_2);
    return r;
}

/* Lean: String.decidableLT */
/* Source: <lean>/Init/Data/String/Basic.lean:424:1 */
uint8_t tagged_urn_formal__l_String_ddecidableLT(lungo_obj x_1, lungo_obj x_2) {
    uint8_t r = lungo_lean_string_dec_lt(x_1, x_2);
    return r;
}

/* Lean: String.decodeChar */
/* Source: <lean>/Init/Data/String/Basic.lean:1152:1 */
uint32_t tagged_urn_formal__l_String_ddecodeChar(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    (void)x_3;
    uint32_t r = lungo_lean_string_utf8_get_fast(x_1, x_2);
    return r;
}

