/* Generated by lungo 1.75.3221 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.System.ST. */
#include "tagged_urn_formal_program.h"

/* Lean: ST.Prim.mkRef */
/* Source: <lean>/Init/System/ST.lean:186:1 */
lungo_obj tagged_urn_formal__l_ST_dPrim_dmkRef(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    (void)x_1;
    (void)x_2;
    lungo_obj r = lungo_lean_st_mk_ref(x_3);
    return r;
}

