/* Generated by lungo 1.156.5900 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module Init.Util. */
#include "tagged_urn_formal_program.h"

/* Lean: mkPanicMessage._closed_0 */
/* Compiled from: mkPanicMessage */
/* Source: <lean>/Init/Util.lean:44:1 */
static lungo_obj tagged_urn_formal__l_mkPanicMessage_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"PANIC at ", 9, 9);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_mkPanicMessage_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_mkPanicMessage_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_mkPanicMessage_d__closed__0__cell, tagged_urn_formal__l_mkPanicMessage_d__closed__0__init);
}

/* Lean: mkPanicMessage._closed_1 */
/* Compiled from: mkPanicMessage */
/* Source: <lean>/Init/Util.lean:44:1 */
static lungo_obj tagged_urn_formal__l_mkPanicMessage_d__closed__1__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)":", 1, 1);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_mkPanicMessage_d__closed__1__cell;
lungo_obj tagged_urn_formal__l_mkPanicMessage_d__closed__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_mkPanicMessage_d__closed__1__cell, tagged_urn_formal__l_mkPanicMessage_d__closed__1__init);
}

/* Lean: mkPanicMessage._closed_2 */
/* Compiled from: mkPanicMessage */
/* Source: <lean>/Init/Util.lean:44:1 */
static lungo_obj tagged_urn_formal__l_mkPanicMessage_d__closed__2__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)": ", 2, 2);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_mkPanicMessage_d__closed__2__cell;
lungo_obj tagged_urn_formal__l_mkPanicMessage_d__closed__2(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_mkPanicMessage_d__closed__2__cell, tagged_urn_formal__l_mkPanicMessage_d__closed__2__init);
}

/* Lean: mkPanicMessageWithDecl */
/* Source: <lean>/Init/Util.lean:62:1 */
lungo_obj tagged_urn_formal__l_mkPanicMessageWithDecl(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5) {
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    lungo_obj x_15;
    lungo_obj x_16;
    lungo_obj x_17;
    lungo_obj x_18;
    lungo_obj x_19;
    lungo_obj x_20;
    x_6 = tagged_urn_formal__l_mkPanicMessage_d__closed__0();
    x_7 = tagged_urn_formal__l_String_dInternal_dappend(x_6, x_2);
    x_8 = tagged_urn_formal__l_mkPanicMessageWithDecl_d__closed__0();
    x_9 = tagged_urn_formal__l_String_dInternal_dappend(x_7, x_8);
    x_10 = tagged_urn_formal__l_String_dInternal_dappend(x_9, x_1);
    x_11 = tagged_urn_formal__l_mkPanicMessage_d__closed__1();
    x_12 = tagged_urn_formal__l_String_dInternal_dappend(x_10, x_11);
    x_13 = tagged_urn_formal__l_Nat_dreprFast(x_3);
    x_14 = tagged_urn_formal__l_String_dInternal_dappend(x_12, x_13);
    lungo_dec_ref(x_13);
    x_15 = tagged_urn_formal__l_String_dInternal_dappend(x_14, x_11);
    x_16 = tagged_urn_formal__l_Nat_dreprFast(x_4);
    x_17 = tagged_urn_formal__l_String_dInternal_dappend(x_15, x_16);
    lungo_dec_ref(x_16);
    x_18 = tagged_urn_formal__l_mkPanicMessage_d__closed__2();
    x_19 = tagged_urn_formal__l_String_dInternal_dappend(x_17, x_18);
    x_20 = tagged_urn_formal__l_String_dInternal_dappend(x_19, x_5);
    return x_20;
}

/* Lean: mkPanicMessageWithDecl._closed_0 */
/* Compiled from: mkPanicMessageWithDecl */
/* Source: <lean>/Init/Util.lean:62:1 */
static lungo_obj tagged_urn_formal__l_mkPanicMessageWithDecl_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)" ", 1, 1);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_mkPanicMessageWithDecl_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_mkPanicMessageWithDecl_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_mkPanicMessageWithDecl_d__closed__0__cell, tagged_urn_formal__l_mkPanicMessageWithDecl_d__closed__0__init);
}

