/* Generated by lungo 1.84.11 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module TaggedUrn.Exec. */
#include "tagged_urn_formal_program.h"

/* Lean: TaggedUrn.Exec.comparable */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:51:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dExec_dcomparable(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dExec_drefines(x_1, x_2);
    switch (x_3) {
        case 0: {
            x_4 = tagged_urn_formal__l_TaggedUrn_dExec_drefines(x_2, x_1);
            return x_4;
        }
        default: {
            return x_3;
        }
    }
}

/* Lean: TaggedUrn.Exec.comparable._boxed */
/* Compiled from: TaggedUrn.Exec.comparable */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:51:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_dcomparable_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dExec_dcomparable(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.Exec.equivalent */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:45:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dExec_dequivalent(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dExec_drefines(x_1, x_2);
    switch (x_3) {
        case 0: {
            return x_3;
        }
        default: {
            x_4 = tagged_urn_formal__l_TaggedUrn_dExec_drefines(x_2, x_1);
            return x_4;
        }
    }
}

/* Lean: TaggedUrn.Exec.equivalent._boxed */
/* Compiled from: TaggedUrn.Exec.equivalent */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:45:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_dequivalent_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dExec_dequivalent(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.Exec.make */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:26:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_dmake(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_inc(x_2);
    x_3 = tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted(x_2);
    switch (x_3) {
        case 0: {
            lungo_dec(x_2);
            lungo_dec_ref(x_1);
            x_4 = lungo_box(0);
            return x_4;
        }
        default: {
            x_5 = lungo_alloc_ctor(0, 2, 0);
            lungo_ctor_set(x_5, 0, x_1);
            lungo_ctor_set(x_5, 1, x_2);
            x_6 = lungo_alloc_ctor(1, 1, 0);
            lungo_ctor_set(x_6, 0, x_5);
            return x_6;
        }
    }
}

/* Lean: TaggedUrn.Exec.meets */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:66:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dExec_dmeets(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_8;
    uint8_t x_9;
    x_3 = lungo_ctor_get(x_1, 0);
    lungo_inc_ref(x_3);
    x_4 = lungo_ctor_get(x_1, 1);
    lungo_inc(x_4);
    lungo_dec_ref(x_1);
    x_5 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_5);
    x_6 = lungo_ctor_get(x_2, 1);
    lungo_inc(x_6);
    lungo_dec_ref(x_2);
    x_7 = tagged_urn_formal__l_String_ddecEq(x_3, x_5);
    lungo_dec_ref(x_5);
    lungo_dec_ref(x_3);
    switch (x_7) {
        case 0: {
            lungo_dec(x_6);
            lungo_dec(x_4);
            return x_7;
        }
        default: {
            x_8 = tagged_urn_formal__l_TaggedUrn_dExec_dmeets_d__closed__0();
            x_9 = tagged_urn_formal__l_TaggedUrn_dmergeWith(x_8, x_4, x_6);
            return x_9;
        }
    }
}

/* Lean: TaggedUrn.Exec.meets._boxed */
/* Compiled from: TaggedUrn.Exec.meets */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:66:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_dmeets_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dExec_dmeets(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.Exec.meets._closed_0 */
/* Compiled from: TaggedUrn.Exec.meets */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:66:1 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_dmeets_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_alloc_closure((void *)tagged_urn_formal__l_TaggedUrn_dtagMeets_d__boxed, 2, 0);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dExec_dmeets_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_dmeets_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dExec_dmeets_d__closed__0__cell, tagged_urn_formal__l_TaggedUrn_dExec_dmeets_d__closed__0__init);
}

/* Lean: TaggedUrn.Exec.meetsClosed */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:89:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dExec_dmeetsClosed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_8;
    uint8_t x_9;
    x_3 = lungo_ctor_get(x_1, 0);
    lungo_inc_ref(x_3);
    x_4 = lungo_ctor_get(x_1, 1);
    lungo_inc(x_4);
    lungo_dec_ref(x_1);
    x_5 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_5);
    x_6 = lungo_ctor_get(x_2, 1);
    lungo_inc(x_6);
    lungo_dec_ref(x_2);
    x_7 = tagged_urn_formal__l_String_ddecEq(x_3, x_5);
    lungo_dec_ref(x_5);
    lungo_dec_ref(x_3);
    switch (x_7) {
        case 0: {
            lungo_dec(x_6);
            lungo_dec(x_4);
            return x_7;
        }
        default: {
            x_8 = tagged_urn_formal__l_TaggedUrn_dExec_dmeetsClosed_d__closed__0();
            x_9 = tagged_urn_formal__l_TaggedUrn_dmergeWith(x_8, x_4, x_6);
            return x_9;
        }
    }
}

/* Lean: TaggedUrn.Exec.meetsClosed._boxed */
/* Compiled from: TaggedUrn.Exec.meetsClosed */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:89:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_dmeetsClosed_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dExec_dmeetsClosed(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.Exec.meetsClosed._closed_0 */
/* Compiled from: TaggedUrn.Exec.meetsClosed */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:89:1 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_dmeetsClosed_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_alloc_closure((void *)tagged_urn_formal__l_TaggedUrn_dtagMeetsClosed_d__boxed, 2, 0);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dExec_dmeetsClosed_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_dmeetsClosed_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dExec_dmeetsClosed_d__closed__0__cell, tagged_urn_formal__l_TaggedUrn_dExec_dmeetsClosed_d__closed__0__init);
}

/* Lean: TaggedUrn.Exec.refines */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:38:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dExec_drefines(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    uint8_t x_8;
    x_3 = lungo_ctor_get(x_1, 0);
    x_4 = lungo_ctor_get(x_1, 1);
    x_5 = lungo_ctor_get(x_2, 0);
    x_6 = lungo_ctor_get(x_2, 1);
    x_7 = tagged_urn_formal__l_String_ddecEq(x_3, x_5);
    switch (x_7) {
        case 0: {
            return x_7;
        }
        default: {
            x_8 = tagged_urn_formal__l_TaggedUrn_dmergeTags(x_4, x_6);
            return x_8;
        }
    }
}

/* Lean: TaggedUrn.Exec.refines._boxed */
/* Compiled from: TaggedUrn.Exec.refines */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:38:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_drefines_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dExec_drefines(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.Exec.refinesClosed */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:79:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dExec_drefinesClosed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_8;
    uint8_t x_9;
    x_3 = lungo_ctor_get(x_1, 0);
    lungo_inc_ref(x_3);
    x_4 = lungo_ctor_get(x_1, 1);
    lungo_inc(x_4);
    lungo_dec_ref(x_1);
    x_5 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_5);
    x_6 = lungo_ctor_get(x_2, 1);
    lungo_inc(x_6);
    lungo_dec_ref(x_2);
    x_7 = tagged_urn_formal__l_String_ddecEq(x_3, x_5);
    lungo_dec_ref(x_5);
    lungo_dec_ref(x_3);
    switch (x_7) {
        case 0: {
            lungo_dec(x_6);
            lungo_dec(x_4);
            return x_7;
        }
        default: {
            x_8 = tagged_urn_formal__l_TaggedUrn_dExec_drefinesClosed_d__closed__0();
            x_9 = tagged_urn_formal__l_TaggedUrn_dmergeWith(x_8, x_4, x_6);
            return x_9;
        }
    }
}

/* Lean: TaggedUrn.Exec.refinesClosed._boxed */
/* Compiled from: TaggedUrn.Exec.refinesClosed */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:79:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_drefinesClosed_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dExec_drefinesClosed(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.Exec.refinesClosed._closed_0 */
/* Compiled from: TaggedUrn.Exec.refinesClosed */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:79:1 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_drefinesClosed_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_alloc_closure((void *)tagged_urn_formal__l_TaggedUrn_dtagMatchClosed_d__boxed, 2, 0);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dExec_drefinesClosed_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_drefinesClosed_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dExec_drefinesClosed_d__closed__0__cell, tagged_urn_formal__l_TaggedUrn_dExec_drefinesClosed_d__closed__0__init);
}

/* Lean: TaggedUrn.Exec.specificity */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:57:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_dspecificity(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = tagged_urn_formal__l_TaggedUrn_durnScore(x_1);
    return x_2;
}

/* Lean: TaggedUrn.Exec.valuesMatch */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:60:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dExec_dvaluesMatch(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    x_3 = tagged_urn_formal__l_TaggedUrn_dtagMatch(x_1, x_2);
    return x_3;
}

/* Lean: TaggedUrn.Exec.valuesMatch._boxed */
/* Compiled from: TaggedUrn.Exec.valuesMatch */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:60:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_dvaluesMatch_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dExec_dvaluesMatch(x_1, x_2);
    lungo_dec(x_2);
    lungo_dec(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.Exec.valuesMatchClosed */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:98:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dExec_dvaluesMatchClosed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    x_3 = tagged_urn_formal__l_TaggedUrn_dtagMatchClosed(x_1, x_2);
    return x_3;
}

/* Lean: TaggedUrn.Exec.valuesMatchClosed._boxed */
/* Compiled from: TaggedUrn.Exec.valuesMatchClosed */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:98:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_dvaluesMatchClosed_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dExec_dvaluesMatchClosed(x_1, x_2);
    lungo_dec(x_2);
    lungo_dec(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.Exec.valuesMeet */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:73:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dExec_dvaluesMeet(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    x_3 = tagged_urn_formal__l_TaggedUrn_dtagMeets(x_1, x_2);
    return x_3;
}

/* Lean: TaggedUrn.Exec.valuesMeet._boxed */
/* Compiled from: TaggedUrn.Exec.valuesMeet */
/* Source: ../../../../formal/TaggedUrn/Exec.lean:73:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dExec_dvaluesMeet_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dExec_dvaluesMeet(x_1, x_2);
    lungo_dec(x_2);
    lungo_dec(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

