/* Generated by lungo 1.77.3244 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module TaggedUrn.Urn. */
#include "tagged_urn_formal_program.h"

/* Lean: List.find?._at_.TaggedUrn.Urn.tag.spec_0 */
/* Compiled from: List.find? */
/* Source: <lean>/Init/Data/List/Basic.lean:1606:1 */
lungo_obj tagged_urn_formal__l_List_dfind_x3f__d__at___dTaggedUrn_dUrn_dtag_dspec__0(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_9;
    _start:
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            x_3 = lungo_box(0);
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_2, 0);
            x_5 = lungo_ctor_get(x_2, 1);
            x_6 = lungo_ctor_get(x_4, 0);
            x_7 = tagged_urn_formal__l_String_ddecEq(x_6, x_1);
            switch (x_7) {
                case 0: {
                    {
                        lungo_obj t_0 = x_1;
                        lungo_obj t_1 = x_5;
                        x_1 = t_0;
                        x_2 = t_1;
                        goto _start;
                    }
                }
                default: {
                    lungo_inc(x_4);
                    x_9 = lungo_alloc_ctor(1, 1, 0);
                    lungo_ctor_set(x_9, 0, x_4);
                    return x_9;
                }
            }
        }
    }
}

/* Lean: List.find?._at_.TaggedUrn.Urn.tag.spec_0._boxed */
/* Compiled from: List.find? */
/* Source: <lean>/Init/Data/List/Basic.lean:1606:1 */
lungo_obj tagged_urn_formal__l_List_dfind_x3f__d__at___dTaggedUrn_dUrn_dtag_dspec__0_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = tagged_urn_formal__l_List_dfind_x3f__d__at___dTaggedUrn_dUrn_dtag_dspec__0(x_1, x_2);
    lungo_dec(x_2);
    lungo_dec_ref(x_1);
    return x_3;
}

/* Lean: List.foldl._at_.List.foldl._at_.Std.Format.joinSep._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_1.spec_2.spec_3 */
/* Compiled from: List.foldl */
/* Source: <lean>/Init/Prelude.lean:3102:1 */
lungo_obj tagged_urn_formal__l_List_dfoldl_d__at___dList_dfoldl_d__at___dStd_dFormat_djoinSep_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__1_dspec__2_dspec__3(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_14;
    uint8_t x_15;
    _start:
    switch (lungo_obj_tag(x_3)) {
        case 0: {
            lungo_dec(x_1);
            return x_2;
        }
        default: {
            x_4 = lungo_ctor_get(x_3, 0);
            x_5 = lungo_ctor_get(x_3, 1);
            x_15 = !lungo_is_exclusive(x_3);
            switch (x_15) {
                case 0: {
                    x_7 = x_3;
                    x_8 = x_15;
                    goto block_6;
                }
                default: {
                    lungo_inc(x_5);
                    lungo_inc(x_4);
                    lungo_dec(x_3);
                    x_7 = lungo_box(0);
                    x_8 = x_15;
                    goto block_6;
                }
            }
            block_6:;
            lungo_inc(x_1);
            switch (x_8) {
                case 0: {
                    lungo_ctor_set_tag(x_7, 5);
                    lungo_ctor_set(x_7, 1, x_1);
                    lungo_ctor_set(x_7, 0, x_2);
                    x_10 = x_7;
                    goto block_9;
                }
                default: {
                    x_14 = lungo_alloc_ctor(5, 2, 0);
                    lungo_ctor_set(x_14, 0, x_2);
                    lungo_ctor_set(x_14, 1, x_1);
                    x_10 = x_14;
                    goto block_9;
                }
            }
            block_9:;
            x_11 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg(x_4);
            x_12 = lungo_alloc_ctor(5, 2, 0);
            lungo_ctor_set(x_12, 0, x_10);
            lungo_ctor_set(x_12, 1, x_11);
            {
                lungo_obj t_0 = x_1;
                lungo_obj t_1 = x_12;
                lungo_obj t_2 = x_5;
                x_1 = t_0;
                x_2 = t_1;
                x_3 = t_2;
                goto _start;
            }
        }
    }
}

/* Lean: List.foldl._at_.Std.Format.joinSep._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_1.spec_2 */
/* Compiled from: List.foldl */
/* Source: <lean>/Init/Prelude.lean:3102:1 */
lungo_obj tagged_urn_formal__l_List_dfoldl_d__at___dStd_dFormat_djoinSep_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__1_dspec__2(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    uint8_t x_15;
    switch (lungo_obj_tag(x_3)) {
        case 0: {
            lungo_dec(x_1);
            return x_2;
        }
        default: {
            x_4 = lungo_ctor_get(x_3, 0);
            x_5 = lungo_ctor_get(x_3, 1);
            x_15 = !lungo_is_exclusive(x_3);
            switch (x_15) {
                case 0: {
                    x_7 = x_3;
                    x_8 = x_15;
                    goto block_6;
                }
                default: {
                    lungo_inc(x_5);
                    lungo_inc(x_4);
                    lungo_dec(x_3);
                    x_7 = lungo_box(0);
                    x_8 = x_15;
                    goto block_6;
                }
            }
            block_6:;
            lungo_inc(x_1);
            switch (x_8) {
                case 0: {
                    lungo_ctor_set_tag(x_7, 5);
                    lungo_ctor_set(x_7, 1, x_1);
                    lungo_ctor_set(x_7, 0, x_2);
                    x_10 = x_7;
                    goto block_9;
                }
                default: {
                    x_14 = lungo_alloc_ctor(5, 2, 0);
                    lungo_ctor_set(x_14, 0, x_2);
                    lungo_ctor_set(x_14, 1, x_1);
                    x_10 = x_14;
                    goto block_9;
                }
            }
            block_9:;
            x_11 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg(x_4);
            x_12 = lungo_alloc_ctor(5, 2, 0);
            lungo_ctor_set(x_12, 0, x_10);
            lungo_ctor_set(x_12, 1, x_11);
            x_13 = tagged_urn_formal__l_List_dfoldl_d__at___dList_dfoldl_d__at___dStd_dFormat_djoinSep_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__1_dspec__2_dspec__3(x_1, x_12, x_5);
            return x_13;
        }
    }
}

/* Lean: List.foldr._at_.List.sum._at_.TaggedUrn.urnScore.spec_1.spec_1 */
/* Compiled from: List.foldr */
/* Source: <lean>/Init/Data/List/Basic.lean:533:1 */
lungo_obj tagged_urn_formal__l_List_dfoldr_d__at___dList_dsum_d__at___dTaggedUrn_durnScore_dspec__1_dspec__1(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_inc(x_1);
            return x_1;
        }
        default: {
            x_3 = lungo_ctor_get(x_2, 0);
            x_4 = lungo_ctor_get(x_2, 1);
            x_5 = tagged_urn_formal__l_List_dfoldr_d__at___dList_dsum_d__at___dTaggedUrn_durnScore_dspec__1_dspec__1(x_1, x_4);
            x_6 = tagged_urn_formal__l_Nat_dadd(x_3, x_5);
            lungo_dec(x_5);
            return x_6;
        }
    }
}

/* Lean: List.foldr._at_.List.sum._at_.TaggedUrn.urnScore.spec_1.spec_1._boxed */
/* Compiled from: List.foldr */
/* Source: <lean>/Init/Data/List/Basic.lean:533:1 */
lungo_obj tagged_urn_formal__l_List_dfoldr_d__at___dList_dsum_d__at___dTaggedUrn_durnScore_dspec__1_dspec__1_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = tagged_urn_formal__l_List_dfoldr_d__at___dList_dsum_d__at___dTaggedUrn_durnScore_dspec__1_dspec__1(x_1, x_2);
    lungo_dec(x_2);
    lungo_dec(x_1);
    return x_3;
}

/* Lean: List.mapTR.loop._at_.TaggedUrn.Urn.keys.spec_0 */
/* Compiled from: List.mapTR.loop */
/* Source: <lean>/Init/Data/List/Basic.lean:2440:17 */
lungo_obj tagged_urn_formal__l_List_dmapTR_dloop_d__at___dTaggedUrn_dUrn_dkeys_dspec__0(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_9;
    lungo_obj x_11;
    lungo_obj x_13;
    uint8_t x_14;
    _start:
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_3 = tagged_urn_formal__l_List_dreverse_d__redArg(x_2);
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_1, 0);
            x_5 = lungo_ctor_get(x_1, 1);
            x_14 = !lungo_is_exclusive(x_1);
            switch (x_14) {
                case 0: {
                    x_7 = x_1;
                    x_8 = x_14;
                    goto block_6;
                }
                default: {
                    lungo_inc(x_5);
                    lungo_inc(x_4);
                    lungo_dec(x_1);
                    x_7 = lungo_box(0);
                    x_8 = x_14;
                    goto block_6;
                }
            }
            block_6:;
            x_9 = lungo_ctor_get(x_4, 0);
            lungo_inc(x_9);
            lungo_dec(x_4);
            switch (x_8) {
                case 0: {
                    lungo_ctor_set(x_7, 1, x_2);
                    lungo_ctor_set(x_7, 0, x_9);
                    x_11 = x_7;
                    goto block_10;
                }
                default: {
                    x_13 = lungo_alloc_ctor(1, 2, 0);
                    lungo_ctor_set(x_13, 0, x_9);
                    lungo_ctor_set(x_13, 1, x_2);
                    x_11 = x_13;
                    goto block_10;
                }
            }
            block_10:;
            {
                lungo_obj t_0 = x_5;
                lungo_obj t_1 = x_11;
                x_1 = t_0;
                x_2 = t_1;
                goto _start;
            }
        }
    }
}

/* Lean: List.mapTR.loop._at_.TaggedUrn.urnScore.spec_0 */
/* Compiled from: List.mapTR.loop */
/* Source: <lean>/Init/Data/List/Basic.lean:2440:17 */
lungo_obj tagged_urn_formal__l_List_dmapTR_dloop_d__at___dTaggedUrn_durnScore_dspec__0(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_7;
    uint8_t x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_12;
    lungo_obj x_14;
    uint8_t x_15;
    _start:
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_3 = tagged_urn_formal__l_List_dreverse_d__redArg(x_2);
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_1, 0);
            x_5 = lungo_ctor_get(x_1, 1);
            x_15 = !lungo_is_exclusive(x_1);
            switch (x_15) {
                case 0: {
                    x_7 = x_1;
                    x_8 = x_15;
                    goto block_6;
                }
                default: {
                    lungo_inc(x_5);
                    lungo_inc(x_4);
                    lungo_dec(x_1);
                    x_7 = lungo_box(0);
                    x_8 = x_15;
                    goto block_6;
                }
            }
            block_6:;
            x_9 = lungo_ctor_get(x_4, 1);
            lungo_inc(x_9);
            lungo_dec(x_4);
            x_10 = tagged_urn_formal__l_TaggedUrn_dtagScore(x_9);
            lungo_dec(x_9);
            switch (x_8) {
                case 0: {
                    lungo_ctor_set(x_7, 1, x_2);
                    lungo_ctor_set(x_7, 0, x_10);
                    x_12 = x_7;
                    goto block_11;
                }
                default: {
                    x_14 = lungo_alloc_ctor(1, 2, 0);
                    lungo_ctor_set(x_14, 0, x_10);
                    lungo_ctor_set(x_14, 1, x_2);
                    x_12 = x_14;
                    goto block_11;
                }
            }
            block_11:;
            {
                lungo_obj t_0 = x_5;
                lungo_obj t_1 = x_12;
                x_1 = t_0;
                x_2 = t_1;
                goto _start;
            }
        }
    }
}

/* Lean: List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0 */
/* Compiled from: List.repr */
/* Source: <lean>/Init/Data/Repr.lean:431:1 */
lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0(lungo_obj x_1, lungo_obj x_2) {
    (void)x_2;
    lungo_obj x_3;
    x_3 = tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg(x_1);
    return x_3;
}

/* Lean: List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0._boxed */
/* Compiled from: List.repr */
/* Source: <lean>/Init/Data/Repr.lean:431:1 */
lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0(x_1, x_2);
    lungo_dec(x_2);
    return x_3;
}

/* Lean: List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0._redArg */
/* Compiled from: List.repr */
/* Source: <lean>/Init/Data/Repr.lean:431:1 */
lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    uint8_t x_11;
    lungo_obj x_12;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_2 = tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__1();
            return x_2;
        }
        default: {
            x_3 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__3();
            x_4 = tagged_urn_formal__l_Std_dFormat_djoinSep_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__1(x_1, x_3);
            x_5 = tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__5();
            x_6 = tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__6();
            x_7 = lungo_alloc_ctor(5, 2, 0);
            lungo_ctor_set(x_7, 0, x_6);
            lungo_ctor_set(x_7, 1, x_4);
            x_8 = tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__7();
            x_9 = lungo_alloc_ctor(5, 2, 0);
            lungo_ctor_set(x_9, 0, x_7);
            lungo_ctor_set(x_9, 1, x_8);
            x_10 = lungo_alloc_ctor(4, 2, 0);
            lungo_ctor_set(x_10, 0, x_5);
            lungo_ctor_set(x_10, 1, x_9);
            x_11 = (uint8_t)0u;
            x_12 = lungo_alloc_ctor(6, 1, 1);
            lungo_ctor_set(x_12, 0, x_10);
            lungo_ctor_set_uint8(x_12, 1 * sizeof(size_t), x_11);
            return x_12;
        }
    }
}

/* Lean: List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0._redArg._closed_0 */
/* Compiled from: List.repr */
/* Source: <lean>/Init/Data/Repr.lean:431:1 */
static lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"[]", 2, 2);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__0__cell, tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__0__init);
}

/* Lean: List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0._redArg._closed_1 */
/* Compiled from: List.repr */
/* Source: <lean>/Init/Data/Repr.lean:431:1 */
static lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__1__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__0();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__1__cell;
lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__1__cell, tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__1__init);
}

/* Lean: List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0._redArg._closed_2 */
/* Compiled from: List.repr */
/* Source: <lean>/Init/Data/Repr.lean:431:1 */
static lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__2__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"[", 1, 1);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__2__cell;
lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__2(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__2__cell, tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__2__init);
}

/* Lean: List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0._redArg._closed_3 */
/* Compiled from: List.repr */
/* Source: <lean>/Init/Data/Repr.lean:431:1 */
static lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__3__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"]", 1, 1);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__3__cell;
lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__3(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__3__cell, tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__3__init);
}

/* Lean: List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0._redArg._closed_4 */
/* Compiled from: List.repr */
/* Source: <lean>/Init/Data/Repr.lean:431:1 */
static lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__4__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__2();
    x_2 = tagged_urn_formal__l_String_dInternal_dlength(x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__4__cell;
lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__4(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__4__cell, tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__4__init);
}

/* Lean: List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0._redArg._closed_5 */
/* Compiled from: List.repr */
/* Source: <lean>/Init/Data/Repr.lean:431:1 */
static lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__5__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__4();
    x_2 = tagged_urn_formal__l_Int_dofNat(x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__5__cell;
lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__5(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__5__cell, tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__5__init);
}

/* Lean: List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0._redArg._closed_6 */
/* Compiled from: List.repr */
/* Source: <lean>/Init/Data/Repr.lean:431:1 */
static lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__6__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__2();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__6__cell;
lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__6(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__6__cell, tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__6__init);
}

/* Lean: List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0._redArg._closed_7 */
/* Compiled from: List.repr */
/* Source: <lean>/Init/Data/Repr.lean:431:1 */
static lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__7__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__3();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__7__cell;
lungo_obj tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__7(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__7__cell, tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg_d__closed__7__init);
}

/* Lean: List.sum._at_.TaggedUrn.urnScore.spec_1 */
/* Compiled from: List.sum */
/* Source: <lean>/Init/Data/List/Basic.lean:2062:1 */
lungo_obj tagged_urn_formal__l_List_dsum_d__at___dTaggedUrn_durnScore_dspec__1(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    x_2 = lungo_usize_to_nat(0u);
    x_3 = tagged_urn_formal__l_List_dfoldr_d__at___dList_dsum_d__at___dTaggedUrn_durnScore_dspec__1_dspec__1(x_2, x_1);
    return x_3;
}

/* Lean: List.sum._at_.TaggedUrn.urnScore.spec_1._boxed */
/* Compiled from: List.sum */
/* Source: <lean>/Init/Data/List/Basic.lean:2062:1 */
lungo_obj tagged_urn_formal__l_List_dsum_d__at___dTaggedUrn_durnScore_dspec__1_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = tagged_urn_formal__l_List_dsum_d__at___dTaggedUrn_durnScore_dspec__1(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: Prod.repr._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_0 */
/* Compiled from: Prod.repr */
/* Source: <lean>/Init/Data/Repr.lean:147:1 */
lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0(lungo_obj x_1, lungo_obj x_2) {
    (void)x_2;
    lungo_obj x_3;
    x_3 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg(x_1);
    return x_3;
}

/* Lean: Prod.repr._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_0._boxed */
/* Compiled from: Prod.repr */
/* Source: <lean>/Init/Data/Repr.lean:147:1 */
lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0(x_1, x_2);
    lungo_dec(x_2);
    return x_3;
}

/* Lean: Prod.repr._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_0._redArg */
/* Compiled from: Prod.repr */
/* Source: <lean>/Init/Data/Repr.lean:147:1 */
lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    lungo_obj x_15;
    lungo_obj x_16;
    lungo_obj x_17;
    lungo_obj x_18;
    lungo_obj x_19;
    lungo_obj x_20;
    lungo_obj x_21;
    lungo_obj x_22;
    lungo_obj x_23;
    uint8_t x_24;
    lungo_obj x_25;
    lungo_obj x_26;
    uint8_t x_27;
    x_2 = lungo_ctor_get(x_1, 0);
    x_3 = lungo_ctor_get(x_1, 1);
    x_27 = !lungo_is_exclusive(x_1);
    switch (x_27) {
        case 0: {
            x_5 = x_1;
            x_6 = x_27;
            goto block_4;
        }
        default: {
            lungo_inc(x_3);
            lungo_inc(x_2);
            lungo_dec(x_1);
            x_5 = lungo_box(0);
            x_6 = x_27;
            goto block_4;
        }
    }
    block_4:;
    x_7 = tagged_urn_formal__l_String_dquote(x_2);
    x_8 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_8, 0, x_7);
    x_9 = lungo_box(0);
    switch (x_6) {
        case 0: {
            lungo_ctor_set_tag(x_5, 1);
            lungo_ctor_set(x_5, 1, x_9);
            lungo_ctor_set(x_5, 0, x_8);
            x_11 = x_5;
            goto block_10;
        }
        default: {
            x_26 = lungo_alloc_ctor(1, 2, 0);
            lungo_ctor_set(x_26, 0, x_8);
            lungo_ctor_set(x_26, 1, x_9);
            x_11 = x_26;
            goto block_10;
        }
    }
    block_10:;
    x_12 = lungo_usize_to_nat(0u);
    x_13 = tagged_urn_formal__l_TaggedUrn_dinstReprConstraint_drepr(x_3, x_12);
    x_14 = lungo_alloc_ctor(1, 2, 0);
    lungo_ctor_set(x_14, 0, x_13);
    lungo_ctor_set(x_14, 1, x_11);
    x_15 = tagged_urn_formal__l_List_dreverse_d__redArg(x_14);
    x_16 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__3();
    x_17 = tagged_urn_formal__l_Std_dFormat_djoinSep_d__at___dLean_dSyntax_dformatStxAux_dspec__2(x_15, x_16);
    x_18 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__6();
    x_19 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__7();
    x_20 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_20, 0, x_19);
    lungo_ctor_set(x_20, 1, x_17);
    x_21 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__8();
    x_22 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_22, 0, x_20);
    lungo_ctor_set(x_22, 1, x_21);
    x_23 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_23, 0, x_18);
    lungo_ctor_set(x_23, 1, x_22);
    x_24 = (uint8_t)0u;
    x_25 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_25, 0, x_23);
    lungo_ctor_set_uint8(x_25, 1 * sizeof(size_t), x_24);
    return x_25;
}

/* Lean: Prod.repr._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_0._redArg._closed_0 */
/* Compiled from: Prod.repr */
/* Source: <lean>/Init/Data/Repr.lean:147:1 */
static lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"(", 1, 1);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__0__cell, tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__0__init);
}

/* Lean: Prod.repr._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_0._redArg._closed_1 */
/* Compiled from: Prod.repr */
/* Source: <lean>/Init/Data/Repr.lean:147:1 */
static lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__1__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)",", 1, 1);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__1__cell;
lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__1__cell, tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__1__init);
}

/* Lean: Prod.repr._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_0._redArg._closed_2 */
/* Compiled from: Prod.repr */
/* Source: <lean>/Init/Data/Repr.lean:147:1 */
static lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__2__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__1();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__2__cell;
lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__2(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__2__cell, tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__2__init);
}

/* Lean: Prod.repr._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_0._redArg._closed_3 */
/* Compiled from: Prod.repr */
/* Source: <lean>/Init/Data/Repr.lean:147:1 */
static lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__3__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    x_1 = lungo_box(1);
    x_2 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__2();
    x_3 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set(x_3, 1, x_1);
    return x_3;
}
static lungo_lazy_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__3__cell;
lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__3(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__3__cell, tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__3__init);
}

/* Lean: Prod.repr._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_0._redArg._closed_4 */
/* Compiled from: Prod.repr */
/* Source: <lean>/Init/Data/Repr.lean:147:1 */
static lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__4__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)")", 1, 1);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__4__cell;
lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__4(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__4__cell, tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__4__init);
}

/* Lean: Prod.repr._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_0._redArg._closed_5 */
/* Compiled from: Prod.repr */
/* Source: <lean>/Init/Data/Repr.lean:147:1 */
static lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__5__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__0();
    x_2 = tagged_urn_formal__l_String_dInternal_dlength(x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__5__cell;
lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__5(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__5__cell, tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__5__init);
}

/* Lean: Prod.repr._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_0._redArg._closed_6 */
/* Compiled from: Prod.repr */
/* Source: <lean>/Init/Data/Repr.lean:147:1 */
static lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__6__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__5();
    x_2 = tagged_urn_formal__l_Int_dofNat(x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__6__cell;
lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__6(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__6__cell, tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__6__init);
}

/* Lean: Prod.repr._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_0._redArg._closed_7 */
/* Compiled from: Prod.repr */
/* Source: <lean>/Init/Data/Repr.lean:147:1 */
static lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__7__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__0();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__7__cell;
lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__7(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__7__cell, tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__7__init);
}

/* Lean: Prod.repr._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_0._redArg._closed_8 */
/* Compiled from: Prod.repr */
/* Source: <lean>/Init/Data/Repr.lean:147:1 */
static lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__8__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__4();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__8__cell;
lungo_obj tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__8(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__8__cell, tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__8__init);
}

/* Lean: Std.Format.joinSep._at_.List.repr._at_.TaggedUrn.instReprUrn.repr.spec_0.spec_1 */
/* Compiled from: Std.Format.joinSep */
/* Source: <lean>/Init/Data/Format/Basic.lean:443:1 */
lungo_obj tagged_urn_formal__l_Std_dFormat_djoinSep_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__1(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec(x_2);
            x_3 = lungo_box(0);
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_1, 1);
            switch (lungo_obj_tag(x_4)) {
                case 0: {
                    lungo_dec(x_2);
                    x_5 = lungo_ctor_get(x_1, 0);
                    lungo_inc(x_5);
                    lungo_dec_ref(x_1);
                    x_6 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg(x_5);
                    return x_6;
                }
                default: {
                    lungo_inc(x_4);
                    x_7 = lungo_ctor_get(x_1, 0);
                    lungo_inc(x_7);
                    lungo_dec_ref(x_1);
                    x_8 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg(x_7);
                    x_9 = tagged_urn_formal__l_List_dfoldl_d__at___dStd_dFormat_djoinSep_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__1_dspec__2(x_2, x_8, x_4);
                    return x_9;
                }
            }
        }
    }
}

/* Lean: TaggedUrn.Urn.keys */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:25:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dUrn_dkeys(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    x_2 = lungo_ctor_get(x_1, 1);
    lungo_inc(x_2);
    lungo_dec_ref(x_1);
    x_3 = lungo_box(0);
    x_4 = tagged_urn_formal__l_List_dmapTR_dloop_d__at___dTaggedUrn_dUrn_dkeys_dspec__0(x_2, x_3);
    return x_4;
}

/* Lean: TaggedUrn.Urn.tag */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:22:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dUrn_dtag(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    x_3 = lungo_ctor_get(x_1, 1);
    x_4 = tagged_urn_formal__l_List_dfind_x3f__d__at___dTaggedUrn_dUrn_dtag_dspec__0(x_2, x_3);
    switch (lungo_obj_tag(x_4)) {
        case 0: {
            x_5 = lungo_box(0);
            return x_5;
        }
        default: {
            x_6 = lungo_ctor_get(x_4, 0);
            lungo_inc(x_6);
            lungo_dec_ref(x_4);
            x_7 = lungo_ctor_get(x_6, 1);
            lungo_inc(x_7);
            lungo_dec(x_6);
            return x_7;
        }
    }
}

/* Lean: TaggedUrn.Urn.tag._boxed */
/* Compiled from: TaggedUrn.Urn.tag */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:22:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dUrn_dtag_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = tagged_urn_formal__l_TaggedUrn_dUrn_dtag(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    return x_3;
}

/* Lean: TaggedUrn.instDecidableEqUrn */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:18 */
uint8_t tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    x_3 = tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq(x_1, x_2);
    return x_3;
}

/* Lean: TaggedUrn.instDecidableEqUrn._boxed */
/* Compiled from: TaggedUrn.instDecidableEqUrn */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:18 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.instDecidableEqUrn.decEq */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:18 */
uint8_t tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    lungo_obj x_8;
    uint8_t x_9;
    x_3 = lungo_ctor_get(x_1, 0);
    lungo_inc_ref(x_3);
    x_4 = lungo_ctor_get(x_1, 1);
    lungo_inc(x_4);
    lungo_dec_ref(x_1);
    x_5 = lungo_ctor_get(x_2, 0);
    lungo_inc_ref(x_5);
    x_6 = lungo_ctor_get(x_2, 1);
    lungo_inc(x_6);
    lungo_dec_ref(x_2);
    x_7 = tagged_urn_formal__l_String_ddecEq(x_3, x_5);
    lungo_dec_ref(x_5);
    lungo_dec_ref(x_3);
    switch (x_7) {
        case 0: {
            lungo_dec(x_6);
            lungo_dec(x_4);
            return x_7;
        }
        default: {
            x_8 = tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq_d__closed__0();
            x_9 = tagged_urn_formal__l_instDecidableEqList_d__redArg(x_8, x_4, x_6);
            return x_9;
        }
    }
}

/* Lean: TaggedUrn.instDecidableEqUrn.decEq._boxed */
/* Compiled from: TaggedUrn.instDecidableEqUrn.decEq */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:18 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.instDecidableEqUrn.decEq._closed_0 */
/* Compiled from: TaggedUrn.instDecidableEqUrn.decEq */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:18 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_alloc_closure((void *)tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq_d__lam__0_d__boxed, 2, 0);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq_d__closed__0__cell, tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq_d__closed__0__init);
}

/* Lean: TaggedUrn.instDecidableEqUrn.decEq._lam_0 */
/* Compiled from: TaggedUrn.instDecidableEqUrn.decEq */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:18 */
uint8_t tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq_d__lam__0(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    x_3 = lungo_alloc_closure((void *)tagged_urn_formal__l_instDecidableEqString_d__boxed, 2, 0);
    x_4 = lungo_alloc_closure((void *)tagged_urn_formal__l_TaggedUrn_dinstDecidableEqConstraint_d__boxed, 2, 0);
    x_5 = tagged_urn_formal__l_instDecidableEqProd_d__redArg(x_3, x_4, x_1, x_2);
    return x_5;
}

/* Lean: TaggedUrn.instDecidableEqUrn.decEq._lam_0._boxed */
/* Compiled from: TaggedUrn.instDecidableEqUrn.decEq */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:18 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq_d__lam__0_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dinstDecidableEqUrn_ddecEq_d__lam__0(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.instDecidableEquivalent */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:74:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dinstDecidableEquivalent(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    lungo_inc_ref(x_1);
    lungo_inc_ref(x_2);
    x_3 = tagged_urn_formal__l_TaggedUrn_dinstDecidableRefines(x_2, x_1);
    x_4 = tagged_urn_formal__l_TaggedUrn_dinstDecidableRefines(x_1, x_2);
    switch (x_4) {
        case 0: {
            return x_4;
        }
        default: {
            return x_3;
        }
    }
}

/* Lean: TaggedUrn.instDecidableEquivalent._boxed */
/* Compiled from: TaggedUrn.instDecidableEquivalent */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:74:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableEquivalent_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dinstDecidableEquivalent(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.instDecidableRefines */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:32:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dinstDecidableRefines(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    uint8_t x_10;
    x_3 = lungo_ctor_get(x_1, 0);
    x_4 = lungo_ctor_get(x_2, 0);
    x_5 = tagged_urn_formal__l_String_ddecEq(x_3, x_4);
    switch (x_5) {
        case 0: {
            lungo_dec_ref(x_2);
            lungo_dec_ref(x_1);
            return x_5;
        }
        default: {
            lungo_inc_ref(x_2);
            lungo_inc_ref(x_1);
            x_6 = lungo_alloc_closure((void *)tagged_urn_formal__l_TaggedUrn_dinstDecidableRefines_d__lam__0_d__boxed, 3, 2);
            lungo_closure_set(x_6, 0, x_1);
            lungo_closure_set(x_6, 1, x_2);
            x_7 = tagged_urn_formal__l_TaggedUrn_dUrn_dkeys(x_1);
            x_8 = tagged_urn_formal__l_TaggedUrn_dUrn_dkeys(x_2);
            x_9 = tagged_urn_formal__l_List_dappendTR_d__redArg(x_7, x_8);
            x_10 = tagged_urn_formal__l_List_ddecidableBAll_d__redArg(x_6, x_9);
            return x_10;
        }
    }
}

/* Lean: TaggedUrn.instDecidableRefines._boxed */
/* Compiled from: TaggedUrn.instDecidableRefines */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:32:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableRefines_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dinstDecidableRefines(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.instDecidableRefines._lam_0 */
/* Compiled from: TaggedUrn.instDecidableRefines */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:32:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dinstDecidableRefines_d__lam__0(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    uint8_t x_6;
    x_4 = tagged_urn_formal__l_TaggedUrn_dUrn_dtag(x_1, x_3);
    x_5 = tagged_urn_formal__l_TaggedUrn_dUrn_dtag(x_2, x_3);
    x_6 = tagged_urn_formal__l_TaggedUrn_dtagMatch(x_4, x_5);
    lungo_dec(x_5);
    lungo_dec(x_4);
    return x_6;
}

/* Lean: TaggedUrn.instDecidableRefines._lam_0._boxed */
/* Compiled from: TaggedUrn.instDecidableRefines */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:32:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableRefines_d__lam__0_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    uint8_t x_4;
    lungo_obj x_5;
    x_4 = tagged_urn_formal__l_TaggedUrn_dinstDecidableRefines_d__lam__0(x_1, x_2, x_3);
    lungo_dec_ref(x_3);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_5 = lungo_box((size_t)x_4);
    return x_5;
}

/* Lean: TaggedUrn.instReprUrn */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn__init(void) {
    lungo_obj x_1;
    x_1 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_d__closed__0();
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn__init);
}

/* Lean: TaggedUrn.instReprUrn._closed_0 */
/* Compiled from: TaggedUrn.instReprUrn */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_alloc_closure((void *)tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__boxed, 2, 0);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_d__closed__0__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_d__closed__0__init);
}

/* Lean: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr(lungo_obj x_1, lungo_obj x_2) {
    (void)x_2;
    lungo_obj x_3;
    x_3 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg(x_1);
    return x_3;
}

/* Lean: TaggedUrn.instReprUrn.repr._boxed */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr(x_1, x_2);
    lungo_dec(x_2);
    return x_3;
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_5;
    uint8_t x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_13;
    uint8_t x_14;
    lungo_obj x_15;
    lungo_obj x_16;
    lungo_obj x_17;
    lungo_obj x_18;
    lungo_obj x_19;
    lungo_obj x_20;
    lungo_obj x_21;
    lungo_obj x_22;
    lungo_obj x_23;
    lungo_obj x_24;
    lungo_obj x_25;
    lungo_obj x_26;
    lungo_obj x_27;
    lungo_obj x_28;
    lungo_obj x_29;
    lungo_obj x_30;
    lungo_obj x_31;
    lungo_obj x_32;
    lungo_obj x_33;
    lungo_obj x_34;
    lungo_obj x_35;
    lungo_obj x_36;
    uint8_t x_37;
    x_2 = lungo_ctor_get(x_1, 0);
    x_3 = lungo_ctor_get(x_1, 1);
    x_37 = !lungo_is_exclusive(x_1);
    switch (x_37) {
        case 0: {
            x_5 = x_1;
            x_6 = x_37;
            goto block_4;
        }
        default: {
            lungo_inc(x_3);
            lungo_inc(x_2);
            lungo_dec(x_1);
            x_5 = lungo_box(0);
            x_6 = x_37;
            goto block_4;
        }
    }
    block_4:;
    x_7 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__5();
    x_8 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__6();
    x_9 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__7();
    x_10 = tagged_urn_formal__l_String_dquote(x_2);
    x_11 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_11, 0, x_10);
    switch (x_6) {
        case 0: {
            lungo_ctor_set_tag(x_5, 4);
            lungo_ctor_set(x_5, 1, x_11);
            lungo_ctor_set(x_5, 0, x_9);
            x_13 = x_5;
            goto block_12;
        }
        default: {
            x_36 = lungo_alloc_ctor(4, 2, 0);
            lungo_ctor_set(x_36, 0, x_9);
            lungo_ctor_set(x_36, 1, x_11);
            x_13 = x_36;
            goto block_12;
        }
    }
    block_12:;
    x_14 = (uint8_t)0u;
    x_15 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_15, 0, x_13);
    lungo_ctor_set_uint8(x_15, 1 * sizeof(size_t), x_14);
    x_16 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_16, 0, x_8);
    lungo_ctor_set(x_16, 1, x_15);
    x_17 = tagged_urn_formal__l_Prod_drepr_d__at___dList_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_dspec__0_d__redArg_d__closed__2();
    x_18 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_18, 0, x_16);
    lungo_ctor_set(x_18, 1, x_17);
    x_19 = lungo_box(1);
    x_20 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_20, 0, x_18);
    lungo_ctor_set(x_20, 1, x_19);
    x_21 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__9();
    x_22 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_22, 0, x_20);
    lungo_ctor_set(x_22, 1, x_21);
    x_23 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_23, 0, x_22);
    lungo_ctor_set(x_23, 1, x_7);
    x_24 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__10();
    x_25 = tagged_urn_formal__l_List_drepr_d__at___dTaggedUrn_dinstReprUrn_drepr_dspec__0_d__redArg(x_3);
    x_26 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_26, 0, x_24);
    lungo_ctor_set(x_26, 1, x_25);
    x_27 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_27, 0, x_26);
    lungo_ctor_set_uint8(x_27, 1 * sizeof(size_t), x_14);
    x_28 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_28, 0, x_23);
    lungo_ctor_set(x_28, 1, x_27);
    x_29 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__13();
    x_30 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__14();
    x_31 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_31, 0, x_30);
    lungo_ctor_set(x_31, 1, x_28);
    x_32 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__15();
    x_33 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_33, 0, x_31);
    lungo_ctor_set(x_33, 1, x_32);
    x_34 = lungo_alloc_ctor(4, 2, 0);
    lungo_ctor_set(x_34, 0, x_29);
    lungo_ctor_set(x_34, 1, x_33);
    x_35 = lungo_alloc_ctor(6, 1, 1);
    lungo_ctor_set(x_35, 0, x_34);
    lungo_ctor_set_uint8(x_35, 1 * sizeof(size_t), x_14);
    return x_35;
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_0 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"{ ", 2, 2);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__0__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__0__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_1 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__1__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"scheme", 6, 6);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__1__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__1(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__1__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__1__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_10 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__10__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = lungo_usize_to_nat(8u);
    x_2 = tagged_urn_formal__l_Int_dofNat(x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__10__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__10(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__10__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__10__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_11 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__11__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)" }", 2, 2);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__11__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__11(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__11__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__11__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_12 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__12__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__0();
    x_2 = tagged_urn_formal__l_String_dInternal_dlength(x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__12__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__12(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__12__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__12__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_13 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__13__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__12();
    x_2 = tagged_urn_formal__l_Int_dofNat(x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__13__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__13(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__13__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__13__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_14 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__14__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__0();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__14__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__14(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__14__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__14__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_15 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__15__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__11();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__15__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__15(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__15__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__15__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_2 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__2__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__1();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__2__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__2(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__2__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__2__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_3 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__3__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    x_1 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__2();
    x_2 = lungo_box(0);
    x_3 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set(x_3, 1, x_1);
    return x_3;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__3__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__3(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__3__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__3__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_4 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__4__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)" := ", 4, 4);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__4__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__4(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__4__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__4__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_5 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__5__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__4();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__5__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__5(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__5__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__5__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_6 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__6__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    lungo_obj x_3;
    x_1 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__5();
    x_2 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__3();
    x_3 = lungo_alloc_ctor(5, 2, 0);
    lungo_ctor_set(x_3, 0, x_2);
    lungo_ctor_set(x_3, 1, x_1);
    return x_3;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__6__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__6(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__6__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__6__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_7 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__7__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = lungo_usize_to_nat(10u);
    x_2 = tagged_urn_formal__l_Int_dofNat(x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__7__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__7(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__7__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__7__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_8 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__8__init(void) {
    lungo_obj x_1;
    x_1 = lungo_mk_string_unchecked((const uint8_t *)"tags", 4, 4);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__8__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__8(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__8__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__8__init);
}

/* Lean: TaggedUrn.instReprUrn.repr._redArg._closed_9 */
/* Compiled from: TaggedUrn.instReprUrn.repr */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:20:12 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__9__init(void) {
    lungo_obj x_1;
    lungo_obj x_2;
    x_1 = tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__8();
    x_2 = lungo_alloc_ctor(3, 1, 0);
    lungo_ctor_set(x_2, 0, x_1);
    return x_2;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__9__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__9(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__9__cell, tagged_urn_formal__l_TaggedUrn_dinstReprUrn_drepr_d__redArg_d__closed__9__init);
}

/* Lean: TaggedUrn.tagScore */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:106:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dtagScore(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    switch (lungo_obj_tag(x_1)) {
        case 2: {
            x_2 = lungo_usize_to_nat(1u);
            return x_2;
        }
        case 3: {
            x_3 = lungo_usize_to_nat(2u);
            return x_3;
        }
        case 4: {
            x_4 = lungo_usize_to_nat(3u);
            return x_4;
        }
        case 5: {
            x_5 = lungo_usize_to_nat(4u);
            return x_5;
        }
        case 6: {
            x_6 = lungo_usize_to_nat(5u);
            return x_6;
        }
        default: {
            x_7 = lungo_usize_to_nat(0u);
            return x_7;
        }
    }
}

/* Lean: TaggedUrn.tagScore._boxed */
/* Compiled from: TaggedUrn.tagScore */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:106:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dtagScore_d__boxed(lungo_obj x_1) {
    lungo_obj x_2;
    x_2 = tagged_urn_formal__l_TaggedUrn_dtagScore(x_1);
    lungo_dec(x_1);
    return x_2;
}

/* Lean: TaggedUrn.urnScore */
/* Source: ../../../../formal/TaggedUrn/Urn.lean:115:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_durnScore(lungo_obj x_1) {
    lungo_obj x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    x_2 = lungo_ctor_get(x_1, 1);
    lungo_inc(x_2);
    lungo_dec_ref(x_1);
    x_3 = lungo_box(0);
    x_4 = tagged_urn_formal__l_List_dmapTR_dloop_d__at___dTaggedUrn_durnScore_dspec__0(x_2, x_3);
    x_5 = tagged_urn_formal__l_List_dsum_d__at___dTaggedUrn_durnScore_dspec__1(x_4);
    lungo_dec(x_4);
    return x_5;
}

/* Lean: _private.TaggedUrn.Urn.0.TaggedUrn.Constraint.norm.match_1.splitter */
/* Source: ../../../../formal/TaggedUrn/Urn.lean */
lungo_obj tagged_urn_formal__l___private_dTaggedUrn_dUrn_d0_dTaggedUrn_dConstraint_dnorm_dmatch__1_dsplitter(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4) {
    (void)x_1;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    switch (lungo_obj_tag(x_2)) {
        case 1: {
            lungo_dec(x_4);
            x_5 = lungo_box(0);
            x_6 = lungo_apply_1(x_3, x_5);
            return x_6;
        }
        default: {
            lungo_dec(x_3);
            x_7 = lungo_apply_2(x_4, x_2, lungo_box(0));
            return x_7;
        }
    }
}

/* Lean: _private.TaggedUrn.Urn.0.TaggedUrn.Constraint.norm.match_1.splitter._redArg */
/* Compiled from: _private.TaggedUrn.Urn.0.TaggedUrn.Constraint.norm.match_1.splitter */
/* Source: ../../../../formal/TaggedUrn/Urn.lean */
lungo_obj tagged_urn_formal__l___private_dTaggedUrn_dUrn_d0_dTaggedUrn_dConstraint_dnorm_dmatch__1_dsplitter_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    switch (lungo_obj_tag(x_1)) {
        case 1: {
            lungo_dec(x_3);
            x_4 = lungo_box(0);
            x_5 = lungo_apply_1(x_2, x_4);
            return x_5;
        }
        default: {
            lungo_dec(x_2);
            x_6 = lungo_apply_2(x_3, x_1, lungo_box(0));
            return x_6;
        }
    }
}

/* Lean: _private.TaggedUrn.Urn.0.TaggedUrn.tagScore.match_1.splitter */
/* Source: ../../../../formal/TaggedUrn/Urn.lean */
lungo_obj tagged_urn_formal__l___private_dTaggedUrn_dUrn_d0_dTaggedUrn_dtagScore_dmatch__1_dsplitter(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5, lungo_obj x_6, lungo_obj x_7, lungo_obj x_8, lungo_obj x_9) {
    (void)x_1;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    lungo_obj x_15;
    lungo_obj x_16;
    lungo_obj x_17;
    lungo_obj x_18;
    lungo_obj x_19;
    lungo_obj x_20;
    lungo_obj x_21;
    lungo_obj x_22;
    lungo_obj x_23;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec(x_9);
            lungo_dec(x_8);
            lungo_dec(x_7);
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_4);
            x_10 = lungo_box(0);
            x_11 = lungo_apply_1(x_3, x_10);
            return x_11;
        }
        case 1: {
            lungo_dec(x_9);
            lungo_dec(x_8);
            lungo_dec(x_7);
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_3);
            x_12 = lungo_box(0);
            x_13 = lungo_apply_1(x_4, x_12);
            return x_13;
        }
        case 2: {
            lungo_dec(x_9);
            lungo_dec(x_8);
            lungo_dec(x_7);
            lungo_dec(x_6);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_14 = lungo_ctor_get(x_2, 0);
            lungo_inc_ref(x_14);
            lungo_dec_ref(x_2);
            x_15 = lungo_apply_1(x_5, x_14);
            return x_15;
        }
        case 3: {
            lungo_dec(x_9);
            lungo_dec(x_8);
            lungo_dec(x_7);
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_16 = lungo_box(0);
            x_17 = lungo_apply_1(x_6, x_16);
            return x_17;
        }
        case 4: {
            lungo_dec(x_9);
            lungo_dec(x_8);
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_18 = lungo_ctor_get(x_2, 0);
            lungo_inc_ref(x_18);
            lungo_dec_ref(x_2);
            x_19 = lungo_apply_1(x_7, x_18);
            return x_19;
        }
        case 5: {
            lungo_dec(x_9);
            lungo_dec(x_7);
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_20 = lungo_ctor_get(x_2, 0);
            lungo_inc_ref(x_20);
            lungo_dec_ref(x_2);
            x_21 = lungo_apply_1(x_8, x_20);
            return x_21;
        }
        default: {
            lungo_dec(x_8);
            lungo_dec(x_7);
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_22 = lungo_box(0);
            x_23 = lungo_apply_1(x_9, x_22);
            return x_23;
        }
    }
}

/* Lean: _private.TaggedUrn.Urn.0.TaggedUrn.tagScore.match_1.splitter._redArg */
/* Compiled from: _private.TaggedUrn.Urn.0.TaggedUrn.tagScore.match_1.splitter */
/* Source: ../../../../formal/TaggedUrn/Urn.lean */
lungo_obj tagged_urn_formal__l___private_dTaggedUrn_dUrn_d0_dTaggedUrn_dtagScore_dmatch__1_dsplitter_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5, lungo_obj x_6, lungo_obj x_7, lungo_obj x_8) {
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    lungo_obj x_15;
    lungo_obj x_16;
    lungo_obj x_17;
    lungo_obj x_18;
    lungo_obj x_19;
    lungo_obj x_20;
    lungo_obj x_21;
    lungo_obj x_22;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec(x_8);
            lungo_dec(x_7);
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_3);
            x_9 = lungo_box(0);
            x_10 = lungo_apply_1(x_2, x_9);
            return x_10;
        }
        case 1: {
            lungo_dec(x_8);
            lungo_dec(x_7);
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_2);
            x_11 = lungo_box(0);
            x_12 = lungo_apply_1(x_3, x_11);
            return x_12;
        }
        case 2: {
            lungo_dec(x_8);
            lungo_dec(x_7);
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_3);
            lungo_dec(x_2);
            x_13 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_13);
            lungo_dec_ref(x_1);
            x_14 = lungo_apply_1(x_4, x_13);
            return x_14;
        }
        case 3: {
            lungo_dec(x_8);
            lungo_dec(x_7);
            lungo_dec(x_6);
            lungo_dec(x_4);
            lungo_dec(x_3);
            lungo_dec(x_2);
            x_15 = lungo_box(0);
            x_16 = lungo_apply_1(x_5, x_15);
            return x_16;
        }
        case 4: {
            lungo_dec(x_8);
            lungo_dec(x_7);
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_3);
            lungo_dec(x_2);
            x_17 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_17);
            lungo_dec_ref(x_1);
            x_18 = lungo_apply_1(x_6, x_17);
            return x_18;
        }
        case 5: {
            lungo_dec(x_8);
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_3);
            lungo_dec(x_2);
            x_19 = lungo_ctor_get(x_1, 0);
            lungo_inc_ref(x_19);
            lungo_dec_ref(x_1);
            x_20 = lungo_apply_1(x_7, x_19);
            return x_20;
        }
        default: {
            lungo_dec(x_7);
            lungo_dec(x_6);
            lungo_dec(x_5);
            lungo_dec(x_4);
            lungo_dec(x_3);
            lungo_dec(x_2);
            x_21 = lungo_box(0);
            x_22 = lungo_apply_1(x_8, x_21);
            return x_22;
        }
    }
}

