/* Generated by lungo 1.83.79 from Lean 4.34.1 (Bridge IR 3). Do not edit. */
/* Compiled Lean module TaggedUrn.Sorted. */
#include "tagged_urn_formal_program.h"

/* Lean: List.all._at_.TaggedUrn.mergeTags.spec_0 */
/* Compiled from: List.all */
/* Source: <lean>/Init/Data/List/Basic.lean:1915:1 */
uint8_t tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeTags_dspec__0(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    _start:
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_2 = (uint8_t)1u;
            return x_2;
        }
        default: {
            x_3 = lungo_ctor_get(x_1, 0);
            x_4 = lungo_ctor_get(x_1, 1);
            x_5 = lungo_ctor_get(x_3, 1);
            x_6 = lungo_box(0);
            x_7 = tagged_urn_formal__l_TaggedUrn_dtagMatch(x_6, x_5);
            switch (x_7) {
                case 0: {
                    return x_7;
                }
                default: {
                    {
                        lungo_obj t_0 = x_4;
                        x_1 = t_0;
                        goto _start;
                    }
                }
            }
        }
    }
}

/* Lean: List.all._at_.TaggedUrn.mergeTags.spec_0._boxed */
/* Compiled from: List.all */
/* Source: <lean>/Init/Data/List/Basic.lean:1915:1 */
lungo_obj tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeTags_dspec__0_d__boxed(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    x_2 = tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeTags_dspec__0(x_1);
    lungo_dec(x_1);
    x_3 = lungo_box((size_t)x_2);
    return x_3;
}

/* Lean: List.all._at_.TaggedUrn.mergeTags.spec_1 */
/* Compiled from: List.all */
/* Source: <lean>/Init/Data/List/Basic.lean:1915:1 */
uint8_t tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeTags_dspec__1(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    uint8_t x_7;
    _start:
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_2 = (uint8_t)1u;
            return x_2;
        }
        default: {
            x_3 = lungo_ctor_get(x_1, 0);
            x_4 = lungo_ctor_get(x_1, 1);
            x_5 = lungo_ctor_get(x_3, 1);
            x_6 = lungo_box(0);
            x_7 = tagged_urn_formal__l_TaggedUrn_dtagMatch(x_5, x_6);
            switch (x_7) {
                case 0: {
                    return x_7;
                }
                default: {
                    {
                        lungo_obj t_0 = x_4;
                        x_1 = t_0;
                        goto _start;
                    }
                }
            }
        }
    }
}

/* Lean: List.all._at_.TaggedUrn.mergeTags.spec_1._boxed */
/* Compiled from: List.all */
/* Source: <lean>/Init/Data/List/Basic.lean:1915:1 */
lungo_obj tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeTags_dspec__1_d__boxed(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    x_2 = tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeTags_dspec__1(x_1);
    lungo_dec(x_1);
    x_3 = lungo_box((size_t)x_2);
    return x_3;
}

/* Lean: List.all._at_.TaggedUrn.mergeWith.spec_0 */
/* Compiled from: List.all */
/* Source: <lean>/Init/Data/List/Basic.lean:1915:1 */
uint8_t tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeWith_dspec__0(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    uint8_t x_9;
    uint8_t x_10;
    _start:
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec_ref(x_1);
            x_3 = (uint8_t)1u;
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_2, 0);
            lungo_inc(x_4);
            x_5 = lungo_ctor_get(x_2, 1);
            lungo_inc(x_5);
            lungo_dec_ref(x_2);
            x_6 = lungo_ctor_get(x_4, 1);
            lungo_inc(x_6);
            lungo_dec(x_4);
            x_7 = lungo_box(0);
            lungo_inc_ref(x_1);
            x_8 = lungo_apply_2(x_1, x_7, x_6);
            x_9 = (uint8_t)lungo_unbox(x_8);
            switch (x_9) {
                case 0: {
                    lungo_dec(x_5);
                    lungo_dec_ref(x_1);
                    x_10 = (uint8_t)lungo_unbox(x_8);
                    return x_10;
                }
                default: {
                    {
                        lungo_obj t_0 = x_1;
                        lungo_obj t_1 = x_5;
                        x_1 = t_0;
                        x_2 = t_1;
                        goto _start;
                    }
                }
            }
        }
    }
}

/* Lean: List.all._at_.TaggedUrn.mergeWith.spec_0._boxed */
/* Compiled from: List.all */
/* Source: <lean>/Init/Data/List/Basic.lean:1915:1 */
lungo_obj tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeWith_dspec__0_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeWith_dspec__0(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: List.all._at_.TaggedUrn.mergeWith.spec_1 */
/* Compiled from: List.all */
/* Source: <lean>/Init/Data/List/Basic.lean:1915:1 */
uint8_t tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeWith_dspec__1(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    uint8_t x_9;
    uint8_t x_10;
    _start:
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec_ref(x_1);
            x_3 = (uint8_t)1u;
            return x_3;
        }
        default: {
            x_4 = lungo_ctor_get(x_2, 0);
            lungo_inc(x_4);
            x_5 = lungo_ctor_get(x_2, 1);
            lungo_inc(x_5);
            lungo_dec_ref(x_2);
            x_6 = lungo_ctor_get(x_4, 1);
            lungo_inc(x_6);
            lungo_dec(x_4);
            x_7 = lungo_box(0);
            lungo_inc_ref(x_1);
            x_8 = lungo_apply_2(x_1, x_6, x_7);
            x_9 = (uint8_t)lungo_unbox(x_8);
            switch (x_9) {
                case 0: {
                    lungo_dec(x_5);
                    lungo_dec_ref(x_1);
                    x_10 = (uint8_t)lungo_unbox(x_8);
                    return x_10;
                }
                default: {
                    {
                        lungo_obj t_0 = x_1;
                        lungo_obj t_1 = x_5;
                        x_1 = t_0;
                        x_2 = t_1;
                        goto _start;
                    }
                }
            }
        }
    }
}

/* Lean: List.all._at_.TaggedUrn.mergeWith.spec_1._boxed */
/* Compiled from: List.all */
/* Source: <lean>/Init/Data/List/Basic.lean:1915:1 */
lungo_obj tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeWith_dspec__1_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeWith_dspec__1(x_1, x_2);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.instDecidableSorted */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:29:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted(lungo_obj x_1) {
    lungo_obj x_2;
    uint8_t x_3;
    x_2 = tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted_d__closed__0();
    x_3 = tagged_urn_formal__l_List_dinstDecidablePairwise_d__redArg(x_2, x_1);
    return x_3;
}

/* Lean: TaggedUrn.instDecidableSorted._boxed */
/* Compiled from: TaggedUrn.instDecidableSorted */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:29:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted_d__boxed(lungo_obj x_1) {
    uint8_t x_2;
    lungo_obj x_3;
    x_2 = tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted(x_1);
    x_3 = lungo_box((size_t)x_2);
    return x_3;
}

/* Lean: TaggedUrn.instDecidableSorted._closed_0 */
/* Compiled from: TaggedUrn.instDecidableSorted */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:29:1 */
static lungo_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted_d__closed__0__init(void) {
    lungo_obj x_1;
    x_1 = lungo_alloc_closure((void *)tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted_d__lam__0_d__boxed, 2, 0);
    return x_1;
}
static lungo_lazy_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted_d__closed__0__cell;
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted_d__closed__0(void) {
    return lungo_lazy_obj_get(&tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted_d__closed__0__cell, tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted_d__closed__0__init);
}

/* Lean: TaggedUrn.instDecidableSorted._lam_0 */
/* Compiled from: TaggedUrn.instDecidableSorted */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:29:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted_d__lam__0(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    uint8_t x_5;
    x_3 = lungo_ctor_get(x_1, 0);
    x_4 = lungo_ctor_get(x_2, 0);
    x_5 = tagged_urn_formal__l_String_ddecidableLT(x_3, x_4);
    return x_5;
}

/* Lean: TaggedUrn.instDecidableSorted._lam_0._boxed */
/* Compiled from: TaggedUrn.instDecidableSorted */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:29:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted_d__lam__0_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dinstDecidableSorted_d__lam__0(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec_ref(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.lookup */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:20:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dlookup(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    lungo_obj x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    x_3 = tagged_urn_formal__l_List_dfind_x3f__d__at___dTaggedUrn_dUrn_dtag_dspec__0(x_2, x_1);
    switch (lungo_obj_tag(x_3)) {
        case 0: {
            x_4 = lungo_box(0);
            return x_4;
        }
        default: {
            x_5 = lungo_ctor_get(x_3, 0);
            lungo_inc(x_5);
            lungo_dec_ref(x_3);
            x_6 = lungo_ctor_get(x_5, 1);
            lungo_inc(x_6);
            lungo_dec(x_5);
            return x_6;
        }
    }
}

/* Lean: TaggedUrn.lookup._boxed */
/* Compiled from: TaggedUrn.lookup */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:20:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dlookup_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    x_3 = tagged_urn_formal__l_TaggedUrn_dlookup(x_1, x_2);
    lungo_dec_ref(x_2);
    lungo_dec(x_1);
    return x_3;
}

/* Lean: TaggedUrn.mergeTags */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:81:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dmergeTags(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    uint8_t x_4;
    lungo_obj x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    uint8_t x_13;
    uint8_t x_14;
    uint8_t x_15;
    lungo_obj x_17;
    uint8_t x_18;
    lungo_obj x_20;
    uint8_t x_21;
    _start:
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            x_3 = tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeTags_dspec__0(x_2);
            return x_3;
        }
        default: {
            switch (lungo_obj_tag(x_2)) {
                case 0: {
                    x_4 = tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeTags_dspec__1(x_1);
                    return x_4;
                }
                default: {
                    x_5 = lungo_ctor_get(x_2, 0);
                    x_6 = lungo_ctor_get(x_1, 0);
                    x_7 = lungo_ctor_get(x_1, 1);
                    x_8 = lungo_ctor_get(x_2, 1);
                    x_9 = lungo_ctor_get(x_5, 0);
                    x_10 = lungo_ctor_get(x_5, 1);
                    x_11 = lungo_ctor_get(x_6, 0);
                    x_12 = lungo_ctor_get(x_6, 1);
                    x_13 = tagged_urn_formal__l_String_ddecidableLT(x_11, x_9);
                    switch (x_13) {
                        case 0: {
                            x_14 = tagged_urn_formal__l_String_ddecidableLT(x_9, x_11);
                            switch (x_14) {
                                case 0: {
                                    x_15 = tagged_urn_formal__l_TaggedUrn_dtagMatch(x_12, x_10);
                                    switch (x_15) {
                                        case 0: {
                                            return x_15;
                                        }
                                        default: {
                                            {
                                                lungo_obj t_0 = x_7;
                                                lungo_obj t_1 = x_8;
                                                x_1 = t_0;
                                                x_2 = t_1;
                                                goto _start;
                                            }
                                        }
                                    }
                                }
                                default: {
                                    x_17 = lungo_box(0);
                                    x_18 = tagged_urn_formal__l_TaggedUrn_dtagMatch(x_17, x_10);
                                    switch (x_18) {
                                        case 0: {
                                            return x_18;
                                        }
                                        default: {
                                            {
                                                lungo_obj t_0 = x_1;
                                                lungo_obj t_1 = x_8;
                                                x_1 = t_0;
                                                x_2 = t_1;
                                                goto _start;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        default: {
                            x_20 = lungo_box(0);
                            x_21 = tagged_urn_formal__l_TaggedUrn_dtagMatch(x_12, x_20);
                            switch (x_21) {
                                case 0: {
                                    return x_21;
                                }
                                default: {
                                    {
                                        lungo_obj t_0 = x_7;
                                        lungo_obj t_1 = x_2;
                                        x_1 = t_0;
                                        x_2 = t_1;
                                        goto _start;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

/* Lean: TaggedUrn.mergeTags._boxed */
/* Compiled from: TaggedUrn.mergeTags */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:81:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dmergeTags_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dmergeTags(x_1, x_2);
    lungo_dec(x_2);
    lungo_dec(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.mergeWith */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:209:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dmergeWith(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    uint8_t x_4;
    uint8_t x_5;
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    uint8_t x_14;
    uint8_t x_15;
    lungo_obj x_16;
    uint8_t x_17;
    uint8_t x_18;
    lungo_obj x_20;
    lungo_obj x_21;
    uint8_t x_22;
    uint8_t x_23;
    lungo_obj x_25;
    lungo_obj x_26;
    uint8_t x_27;
    uint8_t x_28;
    _start:
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            x_4 = tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeWith_dspec__0(x_1, x_3);
            return x_4;
        }
        default: {
            switch (lungo_obj_tag(x_3)) {
                case 0: {
                    x_5 = tagged_urn_formal__l_List_dall_d__at___dTaggedUrn_dmergeWith_dspec__1(x_1, x_2);
                    return x_5;
                }
                default: {
                    x_6 = lungo_ctor_get(x_3, 0);
                    x_7 = lungo_ctor_get(x_2, 0);
                    x_8 = lungo_ctor_get(x_2, 1);
                    x_9 = lungo_ctor_get(x_3, 1);
                    x_10 = lungo_ctor_get(x_6, 0);
                    x_11 = lungo_ctor_get(x_6, 1);
                    x_12 = lungo_ctor_get(x_7, 0);
                    x_13 = lungo_ctor_get(x_7, 1);
                    x_14 = tagged_urn_formal__l_String_ddecidableLT(x_12, x_10);
                    switch (x_14) {
                        case 0: {
                            lungo_inc(x_11);
                            lungo_inc(x_10);
                            lungo_inc(x_9);
                            lungo_dec_ref(x_3);
                            x_15 = tagged_urn_formal__l_String_ddecidableLT(x_10, x_12);
                            lungo_dec(x_10);
                            switch (x_15) {
                                case 0: {
                                    lungo_inc(x_13);
                                    lungo_inc(x_8);
                                    lungo_dec_ref(x_2);
                                    lungo_inc_ref(x_1);
                                    x_16 = lungo_apply_2(x_1, x_13, x_11);
                                    x_17 = (uint8_t)lungo_unbox(x_16);
                                    switch (x_17) {
                                        case 0: {
                                            lungo_dec(x_9);
                                            lungo_dec(x_8);
                                            lungo_dec_ref(x_1);
                                            x_18 = (uint8_t)lungo_unbox(x_16);
                                            return x_18;
                                        }
                                        default: {
                                            {
                                                lungo_obj t_0 = x_1;
                                                lungo_obj t_1 = x_8;
                                                lungo_obj t_2 = x_9;
                                                x_1 = t_0;
                                                x_2 = t_1;
                                                x_3 = t_2;
                                                goto _start;
                                            }
                                        }
                                    }
                                }
                                default: {
                                    x_20 = lungo_box(0);
                                    lungo_inc_ref(x_1);
                                    x_21 = lungo_apply_2(x_1, x_20, x_11);
                                    x_22 = (uint8_t)lungo_unbox(x_21);
                                    switch (x_22) {
                                        case 0: {
                                            lungo_dec(x_9);
                                            lungo_dec_ref(x_2);
                                            lungo_dec_ref(x_1);
                                            x_23 = (uint8_t)lungo_unbox(x_21);
                                            return x_23;
                                        }
                                        default: {
                                            {
                                                lungo_obj t_0 = x_1;
                                                lungo_obj t_1 = x_2;
                                                lungo_obj t_2 = x_9;
                                                x_1 = t_0;
                                                x_2 = t_1;
                                                x_3 = t_2;
                                                goto _start;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        default: {
                            lungo_inc(x_13);
                            lungo_inc(x_8);
                            lungo_dec_ref(x_2);
                            x_25 = lungo_box(0);
                            lungo_inc_ref(x_1);
                            x_26 = lungo_apply_2(x_1, x_13, x_25);
                            x_27 = (uint8_t)lungo_unbox(x_26);
                            switch (x_27) {
                                case 0: {
                                    lungo_dec(x_8);
                                    lungo_dec_ref(x_3);
                                    lungo_dec_ref(x_1);
                                    x_28 = (uint8_t)lungo_unbox(x_26);
                                    return x_28;
                                }
                                default: {
                                    {
                                        lungo_obj t_0 = x_1;
                                        lungo_obj t_1 = x_8;
                                        lungo_obj t_2 = x_3;
                                        x_1 = t_0;
                                        x_2 = t_1;
                                        x_3 = t_2;
                                        goto _start;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

/* Lean: TaggedUrn.mergeWith._boxed */
/* Compiled from: TaggedUrn.mergeWith */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:209:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dmergeWith_d__boxed(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3) {
    uint8_t x_4;
    lungo_obj x_5;
    x_4 = tagged_urn_formal__l_TaggedUrn_dmergeWith(x_1, x_2, x_3);
    x_5 = lungo_box((size_t)x_4);
    return x_5;
}

/* Lean: TaggedUrn.tagMatchClosed */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:315:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dtagMatchClosed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    uint8_t x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dConstraint_dclosed(x_1);
    x_4 = tagged_urn_formal__l_TaggedUrn_dtagMatch(x_3, x_2);
    lungo_dec(x_3);
    return x_4;
}

/* Lean: TaggedUrn.tagMatchClosed._boxed */
/* Compiled from: TaggedUrn.tagMatchClosed */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:315:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dtagMatchClosed_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dtagMatchClosed(x_1, x_2);
    lungo_dec(x_2);
    lungo_dec(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: TaggedUrn.tagMeetsClosed */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:318:1 */
uint8_t tagged_urn_formal__l_TaggedUrn_dtagMeetsClosed(lungo_obj x_1, lungo_obj x_2) {
    lungo_obj x_3;
    uint8_t x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dConstraint_dclosed(x_1);
    x_4 = tagged_urn_formal__l_TaggedUrn_dtagMeets(x_3, x_2);
    lungo_dec(x_3);
    return x_4;
}

/* Lean: TaggedUrn.tagMeetsClosed._boxed */
/* Compiled from: TaggedUrn.tagMeetsClosed */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean:318:1 */
lungo_obj tagged_urn_formal__l_TaggedUrn_dtagMeetsClosed_d__boxed(lungo_obj x_1, lungo_obj x_2) {
    uint8_t x_3;
    lungo_obj x_4;
    x_3 = tagged_urn_formal__l_TaggedUrn_dtagMeetsClosed(x_1, x_2);
    lungo_dec(x_2);
    lungo_dec(x_1);
    x_4 = lungo_box((size_t)x_3);
    return x_4;
}

/* Lean: _private.TaggedUrn.Sorted.0.TaggedUrn.mergeTags.match_1.splitter */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean */
lungo_obj tagged_urn_formal__l___private_dTaggedUrn_dSorted_d0_dTaggedUrn_dmergeTags_dmatch__1_dsplitter(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5, lungo_obj x_6) {
    (void)x_1;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    lungo_obj x_15;
    lungo_obj x_16;
    lungo_obj x_17;
    switch (lungo_obj_tag(x_2)) {
        case 0: {
            lungo_dec(x_6);
            lungo_dec(x_5);
            x_7 = lungo_apply_1(x_4, x_3);
            return x_7;
        }
        default: {
            lungo_dec(x_4);
            switch (lungo_obj_tag(x_3)) {
                case 0: {
                    lungo_dec(x_6);
                    x_8 = lungo_apply_2(x_5, x_2, lungo_box(0));
                    return x_8;
                }
                default: {
                    lungo_dec(x_5);
                    x_9 = lungo_ctor_get(x_3, 0);
                    lungo_inc(x_9);
                    x_10 = lungo_ctor_get(x_2, 0);
                    lungo_inc(x_10);
                    x_11 = lungo_ctor_get(x_2, 1);
                    lungo_inc(x_11);
                    lungo_dec_ref(x_2);
                    x_12 = lungo_ctor_get(x_3, 1);
                    lungo_inc(x_12);
                    lungo_dec_ref(x_3);
                    x_13 = lungo_ctor_get(x_9, 0);
                    lungo_inc(x_13);
                    x_14 = lungo_ctor_get(x_9, 1);
                    lungo_inc(x_14);
                    lungo_dec(x_9);
                    x_15 = lungo_ctor_get(x_10, 0);
                    lungo_inc(x_15);
                    x_16 = lungo_ctor_get(x_10, 1);
                    lungo_inc(x_16);
                    lungo_dec(x_10);
                    x_17 = lungo_apply_6(x_6, x_15, x_16, x_11, x_13, x_14, x_12);
                    return x_17;
                }
            }
        }
    }
}

/* Lean: _private.TaggedUrn.Sorted.0.TaggedUrn.mergeTags.match_1.splitter._redArg */
/* Compiled from: _private.TaggedUrn.Sorted.0.TaggedUrn.mergeTags.match_1.splitter */
/* Source: ../../../../formal/TaggedUrn/Sorted.lean */
lungo_obj tagged_urn_formal__l___private_dTaggedUrn_dSorted_d0_dTaggedUrn_dmergeTags_dmatch__1_dsplitter_d__redArg(lungo_obj x_1, lungo_obj x_2, lungo_obj x_3, lungo_obj x_4, lungo_obj x_5) {
    lungo_obj x_6;
    lungo_obj x_7;
    lungo_obj x_8;
    lungo_obj x_9;
    lungo_obj x_10;
    lungo_obj x_11;
    lungo_obj x_12;
    lungo_obj x_13;
    lungo_obj x_14;
    lungo_obj x_15;
    lungo_obj x_16;
    switch (lungo_obj_tag(x_1)) {
        case 0: {
            lungo_dec(x_5);
            lungo_dec(x_4);
            x_6 = lungo_apply_1(x_3, x_2);
            return x_6;
        }
        default: {
            lungo_dec(x_3);
            switch (lungo_obj_tag(x_2)) {
                case 0: {
                    lungo_dec(x_5);
                    x_7 = lungo_apply_2(x_4, x_1, lungo_box(0));
                    return x_7;
                }
                default: {
                    lungo_dec(x_4);
                    x_8 = lungo_ctor_get(x_2, 0);
                    lungo_inc(x_8);
                    x_9 = lungo_ctor_get(x_1, 0);
                    lungo_inc(x_9);
                    x_10 = lungo_ctor_get(x_1, 1);
                    lungo_inc(x_10);
                    lungo_dec_ref(x_1);
                    x_11 = lungo_ctor_get(x_2, 1);
                    lungo_inc(x_11);
                    lungo_dec_ref(x_2);
                    x_12 = lungo_ctor_get(x_8, 0);
                    lungo_inc(x_12);
                    x_13 = lungo_ctor_get(x_8, 1);
                    lungo_inc(x_13);
                    lungo_dec(x_8);
                    x_14 = lungo_ctor_get(x_9, 0);
                    lungo_inc(x_14);
                    x_15 = lungo_ctor_get(x_9, 1);
                    lungo_inc(x_15);
                    lungo_dec(x_9);
                    x_16 = lungo_apply_6(x_5, x_14, x_15, x_10, x_12, x_13, x_11);
                    return x_16;
                }
            }
        }
    }
}

